table Dim_Machine
	lineageTag: 60762ebd-65ee-5a43-984b-2d12ea5d06a1

	column Machine_ID
		dataType: string
		lineageTag: 24b28b2b-f9aa-5102-bffc-da44e14f4f5f
		summarizeBy: none
		sourceColumn: Machine_ID

		annotation SummarizationSetBy = Automatic

	column Machine_Name
		dataType: string
		lineageTag: 24690348-b2a7-5c90-b2f6-ebef315d5140
		summarizeBy: none
		sourceColumn: Machine_Name

		annotation SummarizationSetBy = Automatic

	column Cell_ID
		dataType: string
		lineageTag: ec679a7f-d12d-5acb-aff1-72f1f54068a0
		summarizeBy: none
		sourceColumn: Cell_ID

		annotation SummarizationSetBy = Automatic

	column Machine_Family
		dataType: string
		lineageTag: a75d92b2-1470-5b3c-b97b-cc572fb329fd
		summarizeBy: none
		sourceColumn: Machine_Family

		annotation SummarizationSetBy = Automatic

	column Serial_No
		dataType: string
		lineageTag: 6e9c91c6-ae02-5d9c-909d-d39f16ea2600
		summarizeBy: none
		sourceColumn: Serial_No

		annotation SummarizationSetBy = Automatic

	column Location_Tag
		dataType: string
		lineageTag: aedbc024-a6a4-520f-8551-b4e081c908c2
		summarizeBy: none
		sourceColumn: Location_Tag

		annotation SummarizationSetBy = Automatic

	column Checklist_ID
		dataType: string
		lineageTag: e7cd8c3a-57e4-5c4e-b961-2dc88a721295
		summarizeBy: none
		sourceColumn: Checklist_ID

		annotation SummarizationSetBy = Automatic

	column QR_Payload_URL
		dataType: string
		lineageTag: 77bf273d-fd8e-5467-b5cc-e6f7e058e182
		summarizeBy: none
		sourceColumn: QR_Payload_URL

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: c5de0030-c9aa-5a41-9e28-0dea9ca78e1e
		summarizeBy: none
		sourceColumn: Criticality
		sortByColumn: Criticality_Sort

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: boolean
		lineageTag: c9a83342-0d2d-58a7-b533-9bcf29667e40
		summarizeBy: none
		sourceColumn: Active
		formatString: "TRUE";;"FALSE"

		annotation SummarizationSetBy = Automatic

	column Machine_Label
		dataType: string
		lineageTag: 828154fb-51c5-515d-83e9-88f231359630
		summarizeBy: none
		sourceColumn: Machine_Label

		annotation SummarizationSetBy = Automatic

	column Criticality_Sort
		dataType: int64
		isHidden: true
		lineageTag: 1aca839b-f085-53db-9906-3038c31a1a3e
		summarizeBy: none
		sourceColumn: Criticality_Sort
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	partition Dim_Machine = m
		mode: import
		source = ```
				// ===========================================================================
				// Dim_Machine  <- Machine_Master
				// ---------------------------------------------------------------------------
				// One row per machine. Carries the QR payload the sticker encodes.
				//
				// The four per-machine form URLs are gone. They were 120 hyperlinks typed into a
				// spreadsheet - one per machine per form - and every one of them a chance to point
				// a button at the wrong machine. The Machine Hub now builds each link from the
				// row it is drawing, so there is nothing per-machine left to maintain or to load.
				//
				// Cell_Name is gone too: it is reachable through Dim_Cell, and the QR label
				// generator prints Cell_ID, so nothing needed the denormalised copy.
				// ===========================================================================
				let
				    Source = fnGetTable("Machine_Master", "01_PM_Master_Data.xlsx", "Machine_Master"),

				    Keys = fnCleanKeys(Source, {"Machine_ID", "Cell_ID", "Checklist_ID"}),
				    Bools = fnYesNo(Keys, {"Active"}),

				    // SharePoint returns a Hyperlink column as a record {Url, Description}.
				    // Excel returns plain text. Flatten to text so both look the same downstream.
				    UrlColumns = {"QR_Payload_URL"},
				    Flattened = Table.TransformColumns(
				        Bools,
				        List.Transform(
				            List.Intersect({Table.ColumnNames(Bools), UrlColumns}),
				            each {_, (v) => if v = null then null
				                            else if v is record then Record.FieldOrDefault(v, "Url", null)
				                            else Text.Trim(Text.From(v)),
				                  type nullable text})),

				    Typed = Table.TransformColumnTypes(Flattened, {
				        {"Machine_ID",             type text},
				        {"Machine_Name",           type text},
				        {"Cell_ID",                type text},
				        {"Machine_Family",         type text},
				        {"Serial_No",              type text},
				        {"Location_Tag",           type text},
				        {"Checklist_ID",           type text},
				        {"QR_Payload_URL",         type text},
				        {"Criticality",            type text},
				        {"Active",                 type logical}
				    }),

				    Trimmed = Table.TransformColumns(Typed, {
				        {"Machine_Name",   each if _ = null then null else Text.Trim(_), type nullable text},
				        {"Machine_Family", each if _ = null then null else Text.Trim(_), type nullable text},
				        {"Criticality",    each if _ = null then null else Text.Upper(Text.Trim(_)), type nullable text}
				    }),

				    // A display label that is useful on a crowded axis without a tooltip.
				    WithLabel = Table.AddColumn(
				        Trimmed, "Machine_Label",
				        each Text.From([Machine_ID]) & " - " & Text.From([Machine_Name]),
				        type text),

				    WithSort = Table.AddColumn(
				        WithLabel, "Criticality_Sort",
				        each if [Criticality] = "A" then 1 else if [Criticality] = "B" then 2 else 3,
				        Int64.Type),

				    Final = Table.SelectRows(WithSort, each [Machine_ID] <> null)
				in
				    Final
				```

	annotation PBI_ResultType = Table
