table Dim_Cell
	lineageTag: 44516d00-6a50-54eb-84f3-2f2140453f5e

	column Cell_ID
		dataType: string
		lineageTag: 66db7f1a-2a65-54b3-be2d-af9681c293b8
		summarizeBy: none
		sourceColumn: Cell_ID

		annotation SummarizationSetBy = Automatic

	column Cell_Name
		dataType: string
		lineageTag: 8a1481b4-b531-53c1-8afa-2292a9119195
		summarizeBy: none
		sourceColumn: Cell_Name

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: a0b17df8-bfed-53b4-af85-77352e67c222
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Process_Area
		dataType: string
		lineageTag: 7a6cd2a6-1635-5a66-bee5-a1514ba84b61
		summarizeBy: none
		sourceColumn: Process_Area

		annotation SummarizationSetBy = Automatic

	column Machine_Count
		dataType: int64
		lineageTag: b762a92c-c184-501e-9c1a-0ad94978a65f
		summarizeBy: none
		sourceColumn: Machine_Count
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column PM_Trigger_Hours
		dataType: int64
		lineageTag: fde03aaf-0075-5454-a01d-933b21221420
		summarizeBy: none
		sourceColumn: PM_Trigger_Hours
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column Calendar_Backstop_Months
		dataType: int64
		lineageTag: 05e34829-ddfe-5108-9961-2ab48b3aaaff
		summarizeBy: none
		sourceColumn: Calendar_Backstop_Months
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column Cum_Std_Hours_Since_PM
		dataType: double
		lineageTag: 4eee56bb-f5a6-56f6-be6c-ec9fb72358e6
		summarizeBy: none
		sourceColumn: Cum_Std_Hours_Since_PM
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column Last_PM_Date
		dataType: dateTime
		lineageTag: 23aabb44-ab3c-500e-8ac3-55843ba2843c
		summarizeBy: none
		sourceColumn: Last_PM_Date
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Last_PM_WO_No
		dataType: string
		lineageTag: c8fc54f7-feed-50c5-be95-acec50d8d2ce
		summarizeBy: none
		sourceColumn: Last_PM_WO_No

		annotation SummarizationSetBy = Automatic

	column Next_PM_Due_Date_Calendar
		dataType: dateTime
		lineageTag: f03a9f32-13d9-56a3-af95-358ff3dd6ab1
		summarizeBy: none
		sourceColumn: Next_PM_Due_Date_Calendar
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Avg_Monthly_Std_Hours_L3M
		dataType: double
		lineageTag: 46b598c8-5cec-5171-ad59-bc019567b2dc
		summarizeBy: none
		sourceColumn: Avg_Monthly_Std_Hours_L3M
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column Owner_Supervisor
		dataType: string
		lineageTag: 630e4cd4-d2b8-5e8a-9961-2589af0b5333
		summarizeBy: none
		sourceColumn: Owner_Supervisor

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 28d290af-b198-59fe-9c04-12146a260f37
		summarizeBy: none
		sourceColumn: Criticality
		sortByColumn: Criticality_Sort

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: boolean
		lineageTag: 4b769965-bb89-53b7-a2f6-056684e7ceb2
		summarizeBy: none
		sourceColumn: Active
		formatString: "TRUE";;"FALSE"

		annotation SummarizationSetBy = Automatic

	column Calendar_Due_Date
		dataType: dateTime
		lineageTag: 169366e2-e321-5d22-8fa6-ba73936b8d15
		summarizeBy: none
		sourceColumn: Calendar_Due_Date
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Amber_Threshold_Hours
		dataType: double
		isHidden: true
		lineageTag: 8c47acf1-61b0-5d55-9c32-06d8c1b8da3c
		summarizeBy: none
		sourceColumn: Amber_Threshold_Hours
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column Criticality_Sort
		dataType: int64
		isHidden: true
		lineageTag: 3fbbad5e-9d5e-53fe-992e-d38a4384d182
		summarizeBy: none
		sourceColumn: Criticality_Sort
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	partition Dim_Cell = m
		mode: import
		source = ```
				// ===========================================================================
				// Dim_Cell  <- Cell_Master
				// ---------------------------------------------------------------------------
				// The heart of the model. One row per production cell, carrying the running
				// 4,000-hour counter that triggers PM.
				//
				// Cum_Std_Hours_Since_PM is a SNAPSHOT, not a history. It is whatever the
				// counter reads at refresh time. That matters for how it is aggregated: summing
				// it across cells is meaningful (total hours currently banked), but summing it
				// across time is not, because there is no time in it. The measures treat it
				// accordingly - see "Cum Std Hours" in dax/measures.dax.
				// ===========================================================================
				let
				    Source = fnGetTable("Cell_Master", "01_PM_Master_Data.xlsx", "Cell_Master"),

				    Keys = fnCleanKeys(Source, {"Cell_ID", "Last_PM_WO_No"}),
				    Bools = fnYesNo(Keys, {"Active"}),

				    Typed = Table.TransformColumnTypes(Bools, {
				        {"Cell_ID",                   type text},
				        {"Cell_Name",                 type text},
				        {"Plant",                     type text},
				        {"Process_Area",              type text},
				        {"Machine_Count",             Int64.Type},
				        {"PM_Trigger_Hours",          Int64.Type},
				        {"Calendar_Backstop_Months",  Int64.Type},
				        {"Cum_Std_Hours_Since_PM",    type number},
				        {"Last_PM_Date",              type date},
				        {"Last_PM_WO_No",             type text},
				        {"Next_PM_Due_Date_Calendar", type date},
				        {"Avg_Monthly_Std_Hours_L3M", type number},
				        {"Owner_Supervisor",          type text},
				        {"Criticality",               type text},
				        {"Active",                    type logical}
				    }),

				    // Trim text that is displayed rather than joined on. A trailing space in a
				    // cell name is harmless until it appears twice in a slicer.
				    Trimmed = Table.TransformColumns(Typed, {
				        {"Cell_Name",        each if _ = null then null else Text.Trim(_), type nullable text},
				        {"Process_Area",     each if _ = null then null else Text.Trim(_), type nullable text},
				        {"Owner_Supervisor", each if _ = null then null else Text.Trim(_), type nullable text},
				        {"Criticality",      each if _ = null then null else Text.Upper(Text.Trim(_)), type nullable text}
				    }),

				    // Derived here rather than in DAX because it is a property of the cell, not
				    // of a filter context: the calendar clock does not care what is on screen.
				    WithBackstop = Table.AddColumn(
				        Trimmed, "Calendar_Due_Date",
				        each if [Last_PM_Date] = null or [Calendar_Backstop_Months] = null then null
				             else Date.AddMonths([Last_PM_Date], [Calendar_Backstop_Months]),
				        type nullable date),

				    // The amber line. Held per cell so a retuned PM_Trigger_Hours moves its own
				    // warning threshold with it, rather than leaving a stale 3,600 behind.
				    WithAmber = Table.AddColumn(
				        WithBackstop, "Amber_Threshold_Hours",
				        each if [PM_Trigger_Hours] = null then null else [PM_Trigger_Hours] * 0.9,
				        type nullable number),

				    // A sort key so slicers and axes read A, B, C rather than alphabetically by
				    // whatever label the choice happens to carry.
				    WithSort = Table.AddColumn(
				        WithAmber, "Criticality_Sort",
				        each if [Criticality] = "A" then 1 else if [Criticality] = "B" then 2 else 3,
				        Int64.Type),

				    Final = Table.SelectRows(WithSort, each [Cell_ID] <> null)
				in
				    Final
				```

	annotation PBI_ResultType = Table
