table Fact_ScanLog
	lineageTag: 48dc61c9-b198-5dfb-b7ff-54748785094c

	column Scan_ID
		dataType: string
		lineageTag: 4980b944-203d-57a7-a79d-d7e7bbc87873
		summarizeBy: none
		sourceColumn: Scan_ID

		annotation SummarizationSetBy = Automatic

	column Scan_DateTime
		dataType: dateTime
		lineageTag: 86708495-e20e-5109-a5ac-5f9f83449f0b
		summarizeBy: none
		sourceColumn: Scan_DateTime
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Machine_ID
		dataType: string
		lineageTag: 778bad26-9fa6-5434-83e2-3c45ad3dce13
		summarizeBy: none
		sourceColumn: Machine_ID

		annotation SummarizationSetBy = Automatic

	column Cell_ID
		dataType: string
		lineageTag: 4a9b3151-38fa-5786-b50a-a3a682de8725
		summarizeBy: none
		sourceColumn: Cell_ID

		annotation SummarizationSetBy = Automatic

	column Tech_ID
		dataType: string
		lineageTag: 3e41d369-1d6a-5d64-91f9-8afc82318393
		summarizeBy: none
		sourceColumn: Tech_ID

		annotation SummarizationSetBy = Automatic

	column Scan_Action
		dataType: string
		lineageTag: f7f1a5ee-6e92-5223-9dfa-904c75da2c98
		summarizeBy: none
		sourceColumn: Scan_Action

		annotation SummarizationSetBy = Automatic

	column Device
		dataType: string
		lineageTag: c4acbad4-5955-5180-9b1e-ed7372aa9b6a
		summarizeBy: none
		sourceColumn: Device

		annotation SummarizationSetBy = Automatic

	column WO_No
		dataType: string
		lineageTag: 89ad0eec-3db5-5e34-ba48-12cca87df226
		summarizeBy: none
		sourceColumn: WO_No

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 133eb74e-1155-5f05-92ee-8283c80a8788
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column Scan_Date
		dataType: dateTime
		lineageTag: 158b17ba-d3fe-53b8-a783-8f7e5b45d163
		summarizeBy: none
		sourceColumn: Scan_Date
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Scan_Hour
		dataType: int64
		lineageTag: e3c74b3d-ec42-57f6-98c2-cb0d8e162608
		summarizeBy: none
		sourceColumn: Scan_Hour
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column Is_Orphan_Scan
		dataType: boolean
		lineageTag: 0079621c-b0a3-52a2-980f-9a6464d77e6c
		summarizeBy: none
		sourceColumn: Is_Orphan_Scan
		formatString: "TRUE";;"FALSE"

		annotation SummarizationSetBy = Automatic

	partition Fact_ScanLog = m
		mode: import
		source = ```
				// ===========================================================================
				// Fact_ScanLog  <- Scan_Log
				// ---------------------------------------------------------------------------
				// Raw QR events.
				//
				// Worth keeping even though PM_Machine_Task already carries timestamps, because
				// this table records the scans that did NOT lead to a completion: the
				// technician who started and walked away, the machine scanned with no open work
				// order. That gap is where adoption problems show up first, months before they
				// show up in compliance percentages.
				// ===========================================================================
				let
				    Source = fnGetTable("Scan_Log", "03_PM_Transactions_Dummy.xlsx", "Scan_Log"),

				    Keys = fnCleanKeys(Source, {"Scan_ID", "Machine_ID", "Cell_ID", "Tech_ID", "WO_No"}),

				    Typed = Table.TransformColumnTypes(Keys, {
				        {"Scan_ID",       type text},
				        {"Scan_DateTime", type datetime},
				        {"Machine_ID",    type text},
				        {"Cell_ID",       type text},
				        {"Tech_ID",       type text},
				        {"Scan_Action",   type text},
				        {"Device",        type text},
				        {"WO_No",         type text},
				        {"Comments",      type text}
				    }),

				    WithDate = Table.AddColumn(
				        Typed, "Scan_Date",
				        each if [Scan_DateTime] = null then null else DateTime.Date([Scan_DateTime]),
				        type nullable date),

				    // Hour of day, for the shift-pattern view. A cluster of scans in the last
				    // ten minutes of a shift is a different behaviour from an even spread.
				    WithHour = Table.AddColumn(
				        WithDate, "Scan_Hour",
				        each if [Scan_DateTime] = null then null else Time.Hour(DateTime.Time([Scan_DateTime])),
				        Int64.Type),

				    // A scan with no work order in force. Not an error - a technician may look
				    // a machine up out of curiosity - but a rising count means people are
				    // scanning stickers that have no work behind them.
				    WithOrphan = Table.AddColumn(
				        WithHour, "Is_Orphan_Scan",
				        each [WO_No] = null,
				        type logical),

				    Final = Table.SelectRows(WithOrphan, each [Scan_ID] <> null)
				in
				    Final
				```

	annotation PBI_ResultType = Table
