table Fact_Breakdown
	lineageTag: 6c019760-2f65-5c26-ae70-16a52835d69d

	column BD_ID
		dataType: string
		lineageTag: fbc534ce-e5de-5b8f-be55-83e2a6980085
		summarizeBy: none
		sourceColumn: BD_ID

		annotation SummarizationSetBy = Automatic

	column Reported_DateTime
		dataType: dateTime
		lineageTag: 590c91b1-5118-5968-9e36-2b703e5c1be8
		summarizeBy: none
		sourceColumn: Reported_DateTime
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Machine_ID
		dataType: string
		lineageTag: dace00c0-e7c2-54e0-959a-33e89c865729
		summarizeBy: none
		sourceColumn: Machine_ID

		annotation SummarizationSetBy = Automatic

	column Cell_ID
		dataType: string
		lineageTag: 7281cde5-a51d-5033-89c3-fe5929fe5671
		summarizeBy: none
		sourceColumn: Cell_ID

		annotation SummarizationSetBy = Automatic

	column Reported_By_Tech_ID
		dataType: string
		lineageTag: c6a95384-35a7-574c-a4ee-edeab0195195
		summarizeBy: none
		sourceColumn: Reported_By_Tech_ID

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: cbda304e-2390-5fa4-a65d-94a66480e967
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column Breakdown_Type
		dataType: string
		lineageTag: e9fdef82-599e-503e-9b4a-99fe179de165
		summarizeBy: none
		sourceColumn: Breakdown_Type

		annotation SummarizationSetBy = Automatic

	column Symptom
		dataType: string
		lineageTag: 769a6272-0e27-5a77-bc1e-b73e43b52c33
		summarizeBy: none
		sourceColumn: Symptom

		annotation SummarizationSetBy = Automatic

	column Root_Cause
		dataType: string
		lineageTag: 2a85dc58-fba7-517d-9f88-96894e11f6c7
		summarizeBy: none
		sourceColumn: Root_Cause

		annotation SummarizationSetBy = Automatic

	column Action_Taken
		dataType: string
		lineageTag: b7074daa-9fad-5502-88f1-e02242fdd9f4
		summarizeBy: none
		sourceColumn: Action_Taken

		annotation SummarizationSetBy = Automatic

	column Response_DateTime
		dataType: dateTime
		lineageTag: d5bc1860-0767-5932-8774-fedb9984c279
		summarizeBy: none
		sourceColumn: Response_DateTime
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Repair_Start
		dataType: dateTime
		lineageTag: 691dcbe1-fc4e-5fb4-b166-856e9eaf5b22
		summarizeBy: none
		sourceColumn: Repair_Start
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Repair_End
		dataType: dateTime
		lineageTag: bbd4d526-6b8e-5ce9-bf57-d74a4ea1f99a
		summarizeBy: none
		sourceColumn: Repair_End
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column Production_Loss_Min
		dataType: int64
		lineageTag: 6f45705d-1c62-5fa0-bd18-8a785b718dd0
		summarizeBy: none
		sourceColumn: Production_Loss_Min
		formatString: #,##0

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1c56c402-91fb-51d7-846d-a4d1ba221433
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Recurrence_Flag
		dataType: boolean
		lineageTag: 155e8b1f-7fd6-56ec-9baf-0dff0f62da3b
		summarizeBy: none
		sourceColumn: Recurrence_Flag
		formatString: "TRUE";;"FALSE"

		annotation SummarizationSetBy = Automatic

	column Reported_Date
		dataType: dateTime
		lineageTag: 7bda57a8-874b-5f60-9bfa-1425b0090627
		summarizeBy: none
		sourceColumn: Reported_Date
		formatString: yyyy-mm-dd
		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	column MTTR_Min
		dataType: double
		lineageTag: d51c20b1-a154-5a72-a4ae-008533a2ae86
		summarizeBy: none
		sourceColumn: MTTR_Min
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column Response_Time_Min
		dataType: double
		lineageTag: dc0adfc9-27ab-5280-acd7-6a24211e2af9
		summarizeBy: none
		sourceColumn: Response_Time_Min
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column Production_Loss_Hrs
		dataType: double
		lineageTag: 58cc4c65-fdf1-5379-bb7a-8a07318e7ed2
		summarizeBy: none
		sourceColumn: Production_Loss_Hrs
		formatString: #,##0.00

		annotation SummarizationSetBy = Automatic

	column Is_Open
		dataType: boolean
		lineageTag: 4f1e90d2-80ea-50f4-8b6f-171d7d33631f
		summarizeBy: none
		sourceColumn: Is_Open
		formatString: "TRUE";;"FALSE"

		annotation SummarizationSetBy = Automatic

	partition Fact_Breakdown = m
		mode: import
		source = ```
				// ===========================================================================
				// Fact_Breakdown  <- Breakdown_Log
				// ---------------------------------------------------------------------------
				// Unplanned stoppages.
				//
				// Production_Loss_Min and MTTR_Min are deliberately separate and must stay that
				// way. MTTR is wrench time; production loss includes waiting for a technician,
				// waiting for a spare, and restarting the line. Production loss is almost always
				// the larger number, and using MTTR for availability makes availability look
				// flattering and wrong.
				//
				// Linked_PM_WO has been removed. The "Breakdowns After PM (7d)" measure always
				// derived the relationship from dates rather than trusting that column, so nothing
				// depended on it - it was a stored answer to a question the model already asks.
				// ===========================================================================
				let
				    Source = fnGetTable("Breakdown_Log", "03_PM_Transactions_Dummy.xlsx", "Breakdown_Log"),

				    Keys = fnCleanKeys(Source, {"BD_ID", "Machine_ID", "Cell_ID", "Reported_By_Tech_ID"}),
				    Bools = fnYesNo(Keys, {"Recurrence_Flag"}),

				    Typed = Table.TransformColumnTypes(Bools, {
				        {"BD_ID",               type text},
				        {"Reported_DateTime",   type datetime},
				        {"Machine_ID",          type text},
				        {"Cell_ID",             type text},
				        {"Reported_By_Tech_ID", type text},
				        {"Shift",               type text},
				        {"Breakdown_Type",      type text},
				        {"Symptom",             type text},
				        {"Root_Cause",          type text},
				        {"Action_Taken",        type text},
				        {"Response_DateTime",   type datetime},
				        {"Repair_Start",        type datetime},
				        {"Repair_End",          type datetime},
				        {"Production_Loss_Min", Int64.Type},
				        {"Status",              type text},
				        {"Recurrence_Flag",     type logical}
				    }),

				    WithDate = Table.AddColumn(
				        Typed, "Reported_Date",
				        each if [Reported_DateTime] = null then null else DateTime.Date([Reported_DateTime]),
				        type nullable date),

				    // Computed from the timestamps, not stored. Flow 6 used to calculate and write
				    // both; the timestamps are the evidence, so the model derives the numbers from
				    // them and there is nothing to fall out of step.
				    WithCalc = Table.AddColumn(
				        WithDate, "MTTR_Min",
				        each if [Repair_Start] = null or [Repair_End] = null then null
				             else Duration.TotalMinutes([Repair_End] - [Repair_Start]),
				        type nullable number),

				    WithResp = Table.AddColumn(
				        WithCalc, "Response_Time_Min",
				        each if [Reported_DateTime] = null or [Response_DateTime] = null then null
				             else Duration.TotalMinutes([Response_DateTime] - [Reported_DateTime]),
				        type nullable number),

				    WithLoss = Table.AddColumn(
				        WithResp, "Production_Loss_Hrs",
				        each if [Production_Loss_Min] = null then null else [Production_Loss_Min] / 60,
				        type nullable number),

				    WithOpen = Table.AddColumn(
				        WithLoss, "Is_Open",
				        each [Status] <> "Closed",
				        type logical),

				    Final = Table.SelectRows(WithOpen, each [BD_ID] <> null)
				in
				    Final
				```

	annotation PBI_ResultType = Table
