/// Key/value configuration. Read by measures via LOOKUPVALUE.
table Config
	lineageTag: 43148fa4-8d4a-446b-8a6e-f0d8561c0bde
	isHidden

	column ConfigKey
		dataType: string
		lineageTag: a945e84f-924c-4517-b711-20392c97a68e
		summarizeBy: none
		sourceColumn: ConfigKey

		annotation SummarizationSetBy = Automatic

	column ConfigValue
		dataType: string
		lineageTag: 8f1f962d-8808-418f-96c0-4ef7e86ab6e9
		summarizeBy: none
		sourceColumn: ConfigValue

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: string
		lineageTag: 908ae356-371a-401c-b6d5-ee194491c733
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 19874dfc-ed4b-4ba3-800b-a3062280fb0d
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Config = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Config"),
				    Typed = Table.TransformColumnTypes(Source, {{"ConfigKey", type text}, {"ConfigValue", type text}, {"DataType", type text}, {"Description", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
