/// Key/value configuration. Read by measures via LOOKUPVALUE.
table Config
	lineageTag: b172f51e-cca9-48f7-8989-a4a6912d61a6
	isHidden

	column ConfigKey
		dataType: string
		lineageTag: d4ddb7dd-d563-4249-8cfe-602516ecb4e3
		summarizeBy: none
		sourceColumn: ConfigKey

		annotation SummarizationSetBy = Automatic

	column ConfigValue
		dataType: string
		lineageTag: 36c21939-ee62-44c8-ab96-8caab2726e4e
		summarizeBy: none
		sourceColumn: ConfigValue

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: string
		lineageTag: d659fa32-d335-4648-8aba-2c41cf62e3df
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 76d97efa-3ef3-4aa8-a5d9-a4b295db8fa9
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Config = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Config"),
				    Typed = Table.TransformColumnTypes(Source, {{"ConfigKey", type text}, {"ConfigValue", type text}, {"DataType", type text}, {"Description", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
