/// Key/value configuration. Read by measures via LOOKUPVALUE.
table Config
	lineageTag: e9f84966-fff3-4c37-a5b5-d3d9b79dbc8a
	isHidden

	column ConfigKey
		dataType: string
		lineageTag: 19f91bd8-e135-469d-877b-bdcf1db3a3c4
		summarizeBy: none
		sourceColumn: ConfigKey

		annotation SummarizationSetBy = Automatic

	column ConfigValue
		dataType: string
		lineageTag: b973ed84-4f32-4b8c-82a7-aab279abadc8
		summarizeBy: none
		sourceColumn: ConfigValue

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: string
		lineageTag: 7d0f185b-a6ac-4895-a77e-aaa378b23a95
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 255d06fd-8b2e-4400-a7b9-d81c62c1a8cd
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Config = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Config"),
				    Typed = Table.TransformColumnTypes(Source, {{"ConfigKey", type text}, {"ConfigValue", type text}, {"DataType", type text}, {"Description", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
