/// Key/value configuration. Read by measures via LOOKUPVALUE.
table Config
	lineageTag: bcabf064-08a2-4bc0-af0b-367bade12e7f
	isHidden

	column ConfigKey
		dataType: string
		lineageTag: e6b9d628-0770-4465-a3b9-3444d69b55db
		summarizeBy: none
		sourceColumn: ConfigKey

		annotation SummarizationSetBy = Automatic

	column ConfigValue
		dataType: string
		lineageTag: ff971e86-1e8c-43af-a56c-4e6f85776fdf
		summarizeBy: none
		sourceColumn: ConfigValue

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: string
		lineageTag: 865116de-55a6-457d-be54-9d6889de5608
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: ea0be232-0f3e-4ace-a49d-38441d67cfae
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Config = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Config"),
				    Typed = Table.TransformColumnTypes(Source, {{"ConfigKey", type text}, {"ConfigValue", type text}, {"DataType", type text}, {"Description", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
