/// Key/value configuration. Read by measures via LOOKUPVALUE.
table Config
	lineageTag: 8b665d2b-3b92-41df-a940-b26e3a3cc8a1
	isHidden

	column ConfigKey
		dataType: string
		lineageTag: bc61351b-7a17-4889-bf2b-828602472d88
		summarizeBy: none
		sourceColumn: ConfigKey

		annotation SummarizationSetBy = Automatic

	column ConfigValue
		dataType: string
		lineageTag: ccf1c34a-a35a-4372-a4c2-3714fb35ede7
		summarizeBy: none
		sourceColumn: ConfigValue

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: string
		lineageTag: cc096458-8f8e-478a-8567-17ed807122f2
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 3e560d43-7100-477c-8787-1fda47aa3d92
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Config = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Config"),
				    Typed = Table.TransformColumnTypes(Source, {{"ConfigKey", type text}, {"ConfigValue", type text}, {"DataType", type text}, {"Description", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
