/// Key/value configuration. Read by measures via LOOKUPVALUE.
table Config
	lineageTag: 9fa96e73-d951-4806-9d03-19800ff07f78
	isHidden

	column ConfigKey
		dataType: string
		lineageTag: c2d6df7f-a412-4a55-a347-327842d9bc45
		summarizeBy: none
		sourceColumn: ConfigKey

		annotation SummarizationSetBy = Automatic

	column ConfigValue
		dataType: string
		lineageTag: 4e67e4fc-da82-40e2-8c70-3362e7b8370d
		summarizeBy: none
		sourceColumn: ConfigValue

		annotation SummarizationSetBy = Automatic

	column DataType
		dataType: string
		lineageTag: c2da790e-0ed8-41aa-98dd-80e2e6289be1
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: ab6094da-753a-4b34-8ea8-109687a75c74
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	partition Config = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Config"),
				    Typed = Table.TransformColumnTypes(Source, {{"ConfigKey", type text}, {"ConfigValue", type text}, {"DataType", type text}, {"Description", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
