/// Marked date table. One row per day, 2024-01-01 to 2028-12-31.
table Dim_Date
	dataCategory: Time
	lineageTag: b8f93ab0-afdd-4931-951a-0b4ab1e364eb

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 0048e635-7657-47a7-959b-1b86a9bee5a4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: 31ad7dc3-2fcc-41c8-baa2-fcf0e73703e7
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 010a834f-c0f1-45e4-bbeb-c0fd97343379
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: b6d15e40-f66c-4a11-b756-65e7dd59c85c
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: string
		lineageTag: 076c13cd-aa06-4770-8a83-b15fff7d34f2
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: #,0
		lineageTag: 9b2d5b4d-b4cf-4c77-8856-81e5639fbaf8
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: #,0
		lineageTag: 23ef3052-d50a-490c-a2aa-0bfda4f93a31
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: 350f8efa-8efb-4e09-9e44-b1c49edc3ed0
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: #,0
		lineageTag: 13abb718-e422-4eb9-b7d5-425d45f5a619
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: string
		lineageTag: 4c6440f4-feef-4920-be2d-f8d80c4c9a56
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: string
		lineageTag: 47bb44f5-b655-4684-b52f-8c6b539526c2
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 68526645-89c6-4c00-9e65-cbe61753766c
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 993fd1d2-a6ef-49d9-a91c-52208e25729e
		summarizeBy: none
		sourceColumn: FiscalMonthNo

		annotation SummarizationSetBy = Automatic

	column MonthSort
		dataType: string
		lineageTag: 8b260ab5-41e3-4ec5-a19a-56a560790a87
		summarizeBy: none
		sourceColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column RelativeToToday
		dataType: string
		lineageTag: 1e8354a4-a3b8-45df-9a1f-62f74f4fa119
		summarizeBy: none
		sourceColumn: RelativeToToday

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source = ```
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2028, 12, 31),
				    Holidays = {
				        #date(2025,1,14), #date(2025,1,26), #date(2025,4,14), #date(2025,8,15),
				        #date(2025,10,20), #date(2025,10,21), #date(2025,12,25),
				        #date(2026,1,14), #date(2026,1,26), #date(2026,4,14), #date(2026,8,15),
				        #date(2026,11,8), #date(2026,12,25),
				        #date(2027,1,14), #date(2027,1,26), #date(2027,4,14)
				    },
				    Days = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				    Base = Table.FromList(Days, Splitter.SplitByNothing(), {"Date"}),
				    T0 = Table.TransformColumnTypes(Base, {{"Date", type date}}),
				    T1 = Table.AddColumn(T0, "Year", each Date.Year([Date]), Int64.Type),
				    T2 = Table.AddColumn(T1, "MonthNo", each Date.Month([Date]), Int64.Type),
				    T3 = Table.AddColumn(T2, "MonthShort", each Date.ToText([Date], "MMM"), type text),
				    T4 = Table.AddColumn(T3, "MonthKey", each Date.ToText([Date], "yyyy-MM"), type text),
				    T5 = Table.AddColumn(T4, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    T6 = Table.AddColumn(T5, "Day", each Date.Day([Date]), Int64.Type),
				    T7 = Table.AddColumn(T6, "DayShort", each Date.ToText([Date], "ddd"), type text),
				    T8 = Table.AddColumn(T7, "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    T9 = Table.AddColumn(T8, "IsWeekend", each if Date.DayOfWeek([Date], Day.Monday) >= 5 then "Yes" else "No", type text),
				    TA = Table.AddColumn(T9, "IsHoliday", each if List.Contains(Holidays, [Date]) then "Yes" else "No", type text),
				    TB = Table.AddColumn(TA, "FinancialYear", each
				            let y = if Date.Month([Date]) >= 4 then Date.Year([Date]) else Date.Year([Date]) - 1
				            in "FY" & Text.End(Text.From(y), 2) & "-" & Text.End(Text.From(y + 1), 2), type text),
				    TC = Table.AddColumn(TB, "FiscalMonthNo", each Number.Mod(Date.Month([Date]) - 4, 12) + 1, Int64.Type),
				    TD = Table.AddColumn(TC, "MonthSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    TE = Table.AddColumn(TD, "RelativeToToday", each
				            if [Date] < Date.From(DateTime.LocalNow()) then "Past"
				            else if [Date] = Date.From(DateTime.LocalNow()) then "Today"
				            else "Future", type text)
				in
				    TE
				```

	annotation PBI_ResultType = Table
