/// Machines. Every QR code resolves to a row here.
table Dim_Machine
	lineageTag: edcf7d65-faca-4855-8f04-b722b90475d9

	column MachineID
		dataType: string
		lineageTag: d26116a6-5190-4866-a318-866b65218bdf
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: f4ddceba-2a76-4e51-b619-fe1e3c194ed2
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 17e479f0-a469-4364-b7b4-67c936b2e514
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 45466f28-3034-40c5-9036-b3a51cc3882f
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Make
		dataType: string
		lineageTag: f39c62c8-28a5-44c9-be75-80b7bb501297
		summarizeBy: none
		sourceColumn: Make

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: 656d0dde-4fec-4601-a051-c5a805eb40a1
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column SerialNo
		dataType: string
		lineageTag: 56a130b1-3383-4b15-ad4c-314baf697781
		summarizeBy: none
		sourceColumn: SerialNo

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c9596c30-6a43-4660-a83b-988381c2d5b2
		summarizeBy: none
		sourceColumn: InstallDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Criticality
		dataType: string
		lineageTag: b5df3111-9f81-4e8d-b9a1-1cc4c91a7e7e
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: bf41959d-6baf-4802-9a17-f005cfeda14c
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: f0c7bbf4-cada-4a5e-8b8d-823607f7d2d7
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column PMStdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: c2900ec4-b846-47f2-8d89-a8a58fae46fc
		summarizeBy: none
		sourceColumn: PMStdMinutes

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: 70baa413-35c1-4cc6-993a-937254edf9f4
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: dfeb61a2-39c5-4f36-b0b7-d2d2b5ebb659
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Machine = m
		mode: import
		source = ```
				let
				    Source = fnSource("Machine_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"Make", type text}, {"Model", type text}, {"SerialNo", type text}, {"InstallDate", type date}, {"Criticality", type text}, {"Location", type text}, {"ChecklistID", type text}, {"PMStdMinutes", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
