/// Maintenance technicians. Each has a personal QR code.
table Dim_Technician
	lineageTag: 4ce35295-892f-4d1d-a868-e1e150d7ba15

	column TechID
		dataType: string
		lineageTag: b71040e6-b3d1-45bd-b6d8-2a6db07c5199
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: f59c99f0-7669-4253-bed2-f8c8829e1b5b
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: e2b23a90-70f6-4e53-a638-0938eef63b4c
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: 9995c7e3-5827-496a-a2cd-b4b33ae70bd7
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column SkillGroup
		dataType: string
		lineageTag: 2d014472-c23e-4012-9d61-875e1f23f5af
		summarizeBy: none
		sourceColumn: SkillGroup

		annotation SummarizationSetBy = Automatic

	column PrimaryArea
		dataType: string
		lineageTag: 20c382c3-0d40-4b1a-a2d2-337b90f9527a
		summarizeBy: none
		sourceColumn: PrimaryArea

		annotation SummarizationSetBy = Automatic

	column DailyCapacityMin
		dataType: int64
		formatString: #,0
		lineageTag: 2b50d5b3-fa24-48a2-81f6-025a2dd27815
		summarizeBy: none
		sourceColumn: DailyCapacityMin

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: eeda41fb-1a4d-4810-a1d6-5ddbd7c9f214
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 2c3b2022-c6c1-4bab-958e-9d21f535ebf5
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Technician = m
		mode: import
		source = ```
				let
				    Source = fnSource("Technician_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"TechID", type text}, {"TechName", type text}, {"Email", type text}, {"Shift", type text}, {"SkillGroup", type text}, {"PrimaryArea", type text}, {"DailyCapacityMin", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
