/// Maintenance technicians. Each has a personal QR code.
table Dim_Technician
	lineageTag: 93324d15-8bcf-4c0a-ab07-d079d06c1d9d

	column TechID
		dataType: string
		lineageTag: b2ffd681-d57d-49cc-9cd9-eb5fb0dd0b73
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: 1411c865-9075-44ef-882e-042009cffb7e
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: fd828e00-4356-4a30-a8ac-0c931b5ed7ad
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: 89e40a93-1e28-48fd-9105-feaa039943c7
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column SkillGroup
		dataType: string
		lineageTag: 5c8475c6-0ace-48e8-bde0-ccac192bf582
		summarizeBy: none
		sourceColumn: SkillGroup

		annotation SummarizationSetBy = Automatic

	column PrimaryArea
		dataType: string
		lineageTag: 770f6b2d-ba13-4ebe-b04c-8e3880d41d64
		summarizeBy: none
		sourceColumn: PrimaryArea

		annotation SummarizationSetBy = Automatic

	column DailyCapacityMin
		dataType: int64
		formatString: #,0
		lineageTag: a26a38ed-043d-4a23-8e2c-9f680418a3a4
		summarizeBy: none
		sourceColumn: DailyCapacityMin

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: 86b1a6d8-6162-40e7-b5df-1c464e7551a1
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: c5e1b801-d6ee-4ea8-8a7f-7e89fa7028b2
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Technician = m
		mode: import
		source = ```
				let
				    Source = fnSource("Technician_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"TechID", type text}, {"TechName", type text}, {"Email", type text}, {"Shift", type text}, {"SkillGroup", type text}, {"PrimaryArea", type text}, {"DailyCapacityMin", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
