/// Machines. Every QR code resolves to a row here.
table Dim_Machine
	lineageTag: 6ea96a47-be5a-480a-939b-d2766dcc6707

	column MachineID
		dataType: string
		lineageTag: 471c3356-5dca-439a-b842-d96e17f7a8f2
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: e9b84d54-70e3-4009-8c15-9e6ceb8163e4
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 28a2c939-78bf-4ab7-ab47-91d8f5a4b667
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 54753fad-dd89-42b4-adb6-016be9d9b8a0
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Make
		dataType: string
		lineageTag: df484159-936c-4f56-9619-f332f945a81c
		summarizeBy: none
		sourceColumn: Make

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: ff0000d3-83b4-47da-a895-7c2d14bc86c5
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column SerialNo
		dataType: string
		lineageTag: e4b3ab57-3500-4c54-b8a9-b3c79df811fc
		summarizeBy: none
		sourceColumn: SerialNo

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: bb8ccc0c-3b12-4fbf-9079-019a5d43849f
		summarizeBy: none
		sourceColumn: InstallDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Criticality
		dataType: string
		lineageTag: 37613286-c4f2-4574-8f59-f19ce30ed720
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 82e354c5-7068-48d9-8e2b-75b45dcc181e
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: de6bffc0-6221-42e9-b213-cc40362524f8
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column PMStdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 5837ca64-f423-4e78-b774-189b4b33e802
		summarizeBy: none
		sourceColumn: PMStdMinutes

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: 66ffcad2-31fd-4513-bdea-9bebb67c3108
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 742ae0ed-a52d-41c8-a73c-ef67acbcceac
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Machine = m
		mode: import
		source = ```
				let
				    Source = fnSource("Machine_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"Make", type text}, {"Model", type text}, {"SerialNo", type text}, {"InstallDate", type date}, {"Criticality", type text}, {"Location", type text}, {"ChecklistID", type text}, {"PMStdMinutes", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
