/// PM task library, one checklist per machine family.
table Dim_Checklist
	lineageTag: 8acd81ad-6d1c-4738-88af-a0abbc12de3f

	column ChecklistID
		dataType: string
		lineageTag: 036277f6-a062-417e-8eae-6fd6030f397e
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: 7684584e-50dd-46bc-a40e-9af6a3e7179e
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: ea79b8a5-8411-4f10-b55f-8d4dfc7d6c84
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: 31f62613-cf20-467b-b884-fc0dcdf2c87c
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: abebb5e4-95ad-446a-b3fe-19780bce1848
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: 371e8a9c-8751-46ab-ac26-2b003beef310
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: b03ba697-cfe7-4456-b9ab-8bf0edae9a48
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column EstMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 824b8f85-c3bb-4d8d-8848-e8bbb2fbc14e
		summarizeBy: none
		sourceColumn: EstMinutes

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 9453e9fb-18e7-4735-9ede-91608a08e860
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Checklist = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Checklist_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"EstMinutes", Int64.Type}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
