/// Marked date table. One row per day, 2024-01-01 to 2028-12-31.
table Dim_Date
	dataCategory: Time
	lineageTag: cee49fdc-efb8-4661-abed-723b7d992c86

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 22b51c57-0541-47e3-9efd-478fba30ed37
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: 11983186-3445-41f5-bf53-de7e31782299
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 6b861c59-191f-4c8d-b781-5a1c484fee47
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 4b64d959-b5b8-4583-95da-c764a03ed64a
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: string
		lineageTag: 5ad85cad-592b-44f4-bbf1-551021e58eaa
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: #,0
		lineageTag: 0dc85a7d-901c-4f6f-b220-2fa2d5f15067
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: #,0
		lineageTag: 8a15ee0a-1363-4d40-bd94-bc5eb696123b
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: 1355c7eb-f06b-4809-ac39-aaed2a60a46b
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: #,0
		lineageTag: 45033e3f-d94f-47e7-b785-4ec412c0b134
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: string
		lineageTag: 90a16f6c-f814-4922-9e7e-ac95ae389bd8
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: string
		lineageTag: 17c4d077-6263-42a9-8b5a-6be32e081a59
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 3748f6fc-ed46-4a28-a163-3a10e95382fb
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 2b316b92-a063-4eb2-b716-856ed7a220dc
		summarizeBy: none
		sourceColumn: FiscalMonthNo

		annotation SummarizationSetBy = Automatic

	column MonthSort
		dataType: string
		lineageTag: 347f6f06-cb5a-4ccd-b2f1-5a5132163a7d
		summarizeBy: none
		sourceColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column RelativeToToday
		dataType: string
		lineageTag: adf3f3eb-9fba-4d05-b86d-528f28142875
		summarizeBy: none
		sourceColumn: RelativeToToday

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source = ```
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2028, 12, 31),
				    Holidays = {
				        #date(2025,1,14), #date(2025,1,26), #date(2025,4,14), #date(2025,8,15),
				        #date(2025,10,20), #date(2025,10,21), #date(2025,12,25),
				        #date(2026,1,14), #date(2026,1,26), #date(2026,4,14), #date(2026,8,15),
				        #date(2026,11,8), #date(2026,12,25),
				        #date(2027,1,14), #date(2027,1,26), #date(2027,4,14)
				    },
				    Days = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				    Base = Table.FromList(Days, Splitter.SplitByNothing(), {"Date"}),
				    T0 = Table.TransformColumnTypes(Base, {{"Date", type date}}),
				    T1 = Table.AddColumn(T0, "Year", each Date.Year([Date]), Int64.Type),
				    T2 = Table.AddColumn(T1, "MonthNo", each Date.Month([Date]), Int64.Type),
				    T3 = Table.AddColumn(T2, "MonthShort", each Date.ToText([Date], "MMM"), type text),
				    T4 = Table.AddColumn(T3, "MonthKey", each Date.ToText([Date], "yyyy-MM"), type text),
				    T5 = Table.AddColumn(T4, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    T6 = Table.AddColumn(T5, "Day", each Date.Day([Date]), Int64.Type),
				    T7 = Table.AddColumn(T6, "DayShort", each Date.ToText([Date], "ddd"), type text),
				    T8 = Table.AddColumn(T7, "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    T9 = Table.AddColumn(T8, "IsWeekend", each if Date.DayOfWeek([Date], Day.Monday) >= 5 then "Yes" else "No", type text),
				    TA = Table.AddColumn(T9, "IsHoliday", each if List.Contains(Holidays, [Date]) then "Yes" else "No", type text),
				    TB = Table.AddColumn(TA, "FinancialYear", each
				            let y = if Date.Month([Date]) >= 4 then Date.Year([Date]) else Date.Year([Date]) - 1
				            in "FY" & Text.End(Text.From(y), 2) & "-" & Text.End(Text.From(y + 1), 2), type text),
				    TC = Table.AddColumn(TB, "FiscalMonthNo", each Number.Mod(Date.Month([Date]) - 4, 12) + 1, Int64.Type),
				    TD = Table.AddColumn(TC, "MonthSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    TE = Table.AddColumn(TD, "RelativeToToday", each
				            if [Date] < Date.From(DateTime.LocalNow()) then "Past"
				            else if [Date] = Date.From(DateTime.LocalNow()) then "Today"
				            else "Future", type text)
				in
				    TE
				```

	annotation PBI_ResultType = Table
