/// Production cells. Carries the PM threshold and calendar backstop.
table Dim_Cell
	lineageTag: 8ecfacee-1768-4d0d-9a49-9a69ea17085c

	column CellID
		dataType: string
		lineageTag: 597ea1bf-4e8c-4171-918f-40ace70c8d08
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: ff999f0b-e0dd-4209-84b8-1f9ca02eb038
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: e6f3c749-73c0-4faf-8555-a4265b6062b1
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 19a21e15-a9e0-4613-8cfc-2a8e9fdc8a45
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 23605ba9-3338-4832-97f8-b9b4444f9271
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: dca1d466-c198-4f2b-95df-de114f6a87a4
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column CalendarBackstopMonths
		dataType: int64
		formatString: #,0
		lineageTag: b68a477e-8bb7-4532-8d30-c24031b29b73
		summarizeBy: none
		sourceColumn: CalendarBackstopMonths

		annotation SummarizationSetBy = Automatic

	column BaselineMonthlyStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: a969044c-ce7b-4c8a-98b1-748097c67217
		summarizeBy: none
		sourceColumn: BaselineMonthlyStdHrs

		annotation SummarizationSetBy = Automatic

	column CostCenter
		dataType: string
		lineageTag: dad13919-9842-421d-a7e1-42420e885502
		summarizeBy: none
		sourceColumn: CostCenter

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 11558295-428c-4fd7-9606-370508edf091
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Cell = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Plant", type text}, {"Criticality", type text}, {"PMIntervalStdHrs", Int64.Type}, {"CalendarBackstopMonths", Int64.Type}, {"BaselineMonthlyStdHrs", Int64.Type}, {"CostCenter", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
