/// Production cells. Carries the PM threshold and calendar backstop.
table Dim_Cell
	lineageTag: 21313616-8d20-4633-8ba8-a8cd4a061151

	column CellID
		dataType: string
		lineageTag: c7e6a11e-64c8-40e5-be6d-f506baa66644
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: d6cf4a31-8cf8-4e39-9198-2e286c243f8c
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 82adc28c-46a8-409c-91a1-7b63930c6ce6
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 381d28ba-de0e-4852-9436-65e9346ef411
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 0fbf83de-4d1d-4991-96d3-c51821f12ec7
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: da1fde49-c603-40fd-b255-817c11e89fc8
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column CalendarBackstopMonths
		dataType: int64
		formatString: #,0
		lineageTag: a2d977b6-287b-4453-8823-0c88c84609d4
		summarizeBy: none
		sourceColumn: CalendarBackstopMonths

		annotation SummarizationSetBy = Automatic

	column BaselineMonthlyStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: fa4489bc-23ba-4ebe-a8dd-99ca3a13ec2f
		summarizeBy: none
		sourceColumn: BaselineMonthlyStdHrs

		annotation SummarizationSetBy = Automatic

	column CostCenter
		dataType: string
		lineageTag: f0e68039-7916-42a6-9e31-0c0f567838ad
		summarizeBy: none
		sourceColumn: CostCenter

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: e98589c7-7987-4985-9386-fde40f59b56f
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Cell = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Plant", type text}, {"Criticality", type text}, {"PMIntervalStdHrs", Int64.Type}, {"CalendarBackstopMonths", Int64.Type}, {"BaselineMonthlyStdHrs", Int64.Type}, {"CostCenter", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
