/// Production cells. Carries the PM threshold and calendar backstop.
table Dim_Cell
	lineageTag: 26e1479f-b909-4d85-881e-6991ac914f41

	column CellID
		dataType: string
		lineageTag: ba55e174-07a7-48d2-8113-dd9f7d725617
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 55e8ea68-def6-45bd-b9d8-6e96905b9781
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 647ab73e-650e-4d7b-87a6-5f620bd4be07
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 86c05487-979f-4926-b092-b262a39f00b5
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: f4b93f07-0ccd-4c1f-8c58-bb51bd04d9f8
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: 097ad1dd-7561-44f0-b2da-b4104b2254d7
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column CalendarBackstopMonths
		dataType: int64
		formatString: #,0
		lineageTag: d4b9fc36-4ab3-41d4-ab0b-a5ccd83df91e
		summarizeBy: none
		sourceColumn: CalendarBackstopMonths

		annotation SummarizationSetBy = Automatic

	column BaselineMonthlyStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: 11c49b5e-429c-4c85-b5a7-0f1c72cfefec
		summarizeBy: none
		sourceColumn: BaselineMonthlyStdHrs

		annotation SummarizationSetBy = Automatic

	column CostCenter
		dataType: string
		lineageTag: dc393a69-ad52-4460-a3c9-9b21cec75eab
		summarizeBy: none
		sourceColumn: CostCenter

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: e151358d-9cc3-48de-b269-8dfaaec836a4
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Cell = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Plant", type text}, {"Criticality", type text}, {"PMIntervalStdHrs", Int64.Type}, {"CalendarBackstopMonths", Int64.Type}, {"BaselineMonthlyStdHrs", Int64.Type}, {"CostCenter", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
