/// Marked date table. One row per day, 2024-01-01 to 2028-12-31.
table Dim_Date
	dataCategory: Time
	lineageTag: d80bce72-7af2-43d6-9a38-69ab7c3b9ec6

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 8230654a-9152-452b-9d6f-b997e97f562a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: a67997b6-df20-4820-bbeb-86a7b9564a04
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: fa99dde7-0ecc-4bd7-a0c0-1cd70c4e1c18
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 7b3b05e9-13b9-499f-8f55-74ff1f4d0469
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: string
		lineageTag: 7d0cfe93-872a-4155-a881-3d35c076cabe
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: #,0
		lineageTag: b175916f-6bab-4330-8972-6d1320178a35
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: #,0
		lineageTag: 0df25256-d68a-4e2d-9ae2-a86e3d5d1fb2
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: c3d44848-da6e-4fac-8572-681ca514cd65
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: #,0
		lineageTag: 2cdb38d0-3af4-44f1-858b-224992a0d544
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: string
		lineageTag: adc0a32d-3950-4596-9b2c-35db74edcacc
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: string
		lineageTag: 7d9e37c5-fb50-4911-a9b8-4eb31f31c74d
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 8c15a7aa-893b-49e2-b9df-be5dd5489179
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNo
		dataType: int64
		formatString: #,0
		lineageTag: efc15196-74e0-4249-98ba-d020a72a4f59
		summarizeBy: none
		sourceColumn: FiscalMonthNo

		annotation SummarizationSetBy = Automatic

	column MonthSort
		dataType: string
		lineageTag: 4513a896-2438-41ee-988c-f9ffa7503afb
		summarizeBy: none
		sourceColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column RelativeToToday
		dataType: string
		lineageTag: f90d724d-7240-4dc9-b8ba-07a3bb4b528f
		summarizeBy: none
		sourceColumn: RelativeToToday

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source = ```
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2028, 12, 31),
				    Holidays = {
				        #date(2025,1,14), #date(2025,1,26), #date(2025,4,14), #date(2025,8,15),
				        #date(2025,10,20), #date(2025,10,21), #date(2025,12,25),
				        #date(2026,1,14), #date(2026,1,26), #date(2026,4,14), #date(2026,8,15),
				        #date(2026,11,8), #date(2026,12,25),
				        #date(2027,1,14), #date(2027,1,26), #date(2027,4,14)
				    },
				    Days = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				    Base = Table.FromList(Days, Splitter.SplitByNothing(), {"Date"}),
				    T0 = Table.TransformColumnTypes(Base, {{"Date", type date}}),
				    T1 = Table.AddColumn(T0, "Year", each Date.Year([Date]), Int64.Type),
				    T2 = Table.AddColumn(T1, "MonthNo", each Date.Month([Date]), Int64.Type),
				    T3 = Table.AddColumn(T2, "MonthShort", each Date.ToText([Date], "MMM"), type text),
				    T4 = Table.AddColumn(T3, "MonthKey", each Date.ToText([Date], "yyyy-MM"), type text),
				    T5 = Table.AddColumn(T4, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    T6 = Table.AddColumn(T5, "Day", each Date.Day([Date]), Int64.Type),
				    T7 = Table.AddColumn(T6, "DayShort", each Date.ToText([Date], "ddd"), type text),
				    T8 = Table.AddColumn(T7, "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    T9 = Table.AddColumn(T8, "IsWeekend", each if Date.DayOfWeek([Date], Day.Monday) >= 5 then "Yes" else "No", type text),
				    TA = Table.AddColumn(T9, "IsHoliday", each if List.Contains(Holidays, [Date]) then "Yes" else "No", type text),
				    TB = Table.AddColumn(TA, "FinancialYear", each
				            let y = if Date.Month([Date]) >= 4 then Date.Year([Date]) else Date.Year([Date]) - 1
				            in "FY" & Text.End(Text.From(y), 2) & "-" & Text.End(Text.From(y + 1), 2), type text),
				    TC = Table.AddColumn(TB, "FiscalMonthNo", each Number.Mod(Date.Month([Date]) - 4, 12) + 1, Int64.Type),
				    TD = Table.AddColumn(TC, "MonthSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    TE = Table.AddColumn(TD, "RelativeToToday", each
				            if [Date] < Date.From(DateTime.LocalNow()) then "Past"
				            else if [Date] = Date.From(DateTime.LocalNow()) then "Today"
				            else "Future", type text)
				in
				    TE
				```

	annotation PBI_ResultType = Table
