/// Production cells. Carries the PM threshold and calendar backstop.
table Dim_Cell
	lineageTag: be38b73b-45b2-45e5-b7f0-a778ab7c0608

	column CellID
		dataType: string
		lineageTag: 7380c4cd-9755-4432-99b6-742fd3477bf9
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 92731a3f-2732-46fd-a14a-c1b1496f2492
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: fc8f40ed-ebe1-4680-8d6e-f9a952cff104
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: 8a11ec4e-765f-4b79-959c-85b460a46d48
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: a65df679-fb15-49dd-9498-9608a71a3faf
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: 654fc32f-d3ce-4ce5-9871-710b9f1345f2
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column CalendarBackstopMonths
		dataType: int64
		formatString: #,0
		lineageTag: 214bb714-5798-42fa-990f-253c54201f60
		summarizeBy: none
		sourceColumn: CalendarBackstopMonths

		annotation SummarizationSetBy = Automatic

	column BaselineMonthlyStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: d7973e6b-ec8e-4501-84f8-e9404a50ab50
		summarizeBy: none
		sourceColumn: BaselineMonthlyStdHrs

		annotation SummarizationSetBy = Automatic

	column CostCenter
		dataType: string
		lineageTag: a393ffd3-7089-4cfa-af50-388de3ef146c
		summarizeBy: none
		sourceColumn: CostCenter

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 8e660ed9-c1b6-4438-a532-9d8c5a8be03a
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Cell = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Plant", type text}, {"Criticality", type text}, {"PMIntervalStdHrs", Int64.Type}, {"CalendarBackstopMonths", Int64.Type}, {"BaselineMonthlyStdHrs", Int64.Type}, {"CostCenter", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
