/// Spare parts catalogue with stock and minimum levels.
table Dim_SparePart
	lineageTag: 825dff9b-0a8b-4cef-8047-4edd885b031e

	column PartNo
		dataType: string
		lineageTag: c5b9ca00-dd93-4d6d-9072-525656f1f9a0
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 1845a346-29cf-43bd-b2cb-a75d590444d7
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 1b3ee4f8-870a-4f7d-9bf2-b6293504a9c5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 58e6e42f-8e89-4b00-93f5-50a03037aff3
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 47efa37d-087f-4548-8c42-37c8616ff11e
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column MinStock
		dataType: int64
		formatString: #,0
		lineageTag: 3e3bc25d-b814-4f79-9b16-f73827fadc72
		summarizeBy: none
		sourceColumn: MinStock

		annotation SummarizationSetBy = Automatic

	column CurrentStock
		dataType: int64
		formatString: #,0
		lineageTag: 9a9e86c5-1128-4c90-b19c-87d673213184
		summarizeBy: none
		sourceColumn: CurrentStock

		annotation SummarizationSetBy = Automatic

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: 105d6dc0-d670-49a2-bfe4-72feed93c6d6
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: 979cd403-ec07-45df-8b9d-4e2e605975f8
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column AppliesToMachineType
		dataType: string
		lineageTag: 26207985-6bc1-4b92-a328-63c52a418659
		summarizeBy: none
		sourceColumn: AppliesToMachineType

		annotation SummarizationSetBy = Automatic

	partition Dim_SparePart = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"UnitCostINR", type number}, {"MinStock", Int64.Type}, {"CurrentStock", Int64.Type}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"AppliesToMachineType", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
