/// Production cells. Carries the PM threshold and calendar backstop.
table Dim_Cell
	lineageTag: bb8d9a51-0611-4d31-beef-8cdd09be272b

	column CellID
		dataType: string
		lineageTag: 7587aa85-cace-45a0-88a8-a0e2e0cf9045
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: edd45fec-0553-460d-bea1-bff8ab57b62f
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: f2144f8a-33b9-4688-a85d-f966e01e1501
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Plant
		dataType: string
		lineageTag: def54273-8736-490d-b569-e0a370800ec4
		summarizeBy: none
		sourceColumn: Plant

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: db2d8daa-289c-4e56-a1a2-c2e8cca7586f
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: e1c6507f-3a7e-44eb-8697-bc524d92e47f
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column CalendarBackstopMonths
		dataType: int64
		formatString: #,0
		lineageTag: 2e970464-3348-49cc-a48a-aaf040a4b03d
		summarizeBy: none
		sourceColumn: CalendarBackstopMonths

		annotation SummarizationSetBy = Automatic

	column BaselineMonthlyStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: 5730f4d1-1e60-4117-aa1c-d92f193eb586
		summarizeBy: none
		sourceColumn: BaselineMonthlyStdHrs

		annotation SummarizationSetBy = Automatic

	column CostCenter
		dataType: string
		lineageTag: 416e7cc8-03c9-49a4-9e10-1a17bf553459
		summarizeBy: none
		sourceColumn: CostCenter

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 5fa2e301-fbca-4533-ae9e-2ac28e88d818
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Cell = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Plant", type text}, {"Criticality", type text}, {"PMIntervalStdHrs", Int64.Type}, {"CalendarBackstopMonths", Int64.Type}, {"BaselineMonthlyStdHrs", Int64.Type}, {"CostCenter", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
