/// Spare parts catalogue with stock and minimum levels.
table Dim_SparePart
	lineageTag: 9ba957f7-b0ca-45d6-af3f-aa9c1210dc84

	column PartNo
		dataType: string
		lineageTag: 0c32bdf0-b6d5-4c58-9921-efe0a4242ced
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 2617580d-31bc-42c9-9d87-3f090a5a7119
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 14becf45-634b-48c8-b1cf-6a4ea5d43412
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 7b44199c-e879-4015-8470-1ea448906374
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 0b3d1716-a4b0-4e9e-b70a-28a75ead0dad
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column MinStock
		dataType: int64
		formatString: #,0
		lineageTag: 306de852-a715-43b5-aa34-65fe5a4676b5
		summarizeBy: none
		sourceColumn: MinStock

		annotation SummarizationSetBy = Automatic

	column CurrentStock
		dataType: int64
		formatString: #,0
		lineageTag: 6960d303-9531-4319-9051-1464e52d7a86
		summarizeBy: none
		sourceColumn: CurrentStock

		annotation SummarizationSetBy = Automatic

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: 28909efd-e59f-44be-b199-2ef49a7a289f
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: 0efbcd3e-1701-4102-9beb-dce06119bccf
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column AppliesToMachineType
		dataType: string
		lineageTag: 2498d37e-ee4c-4d3c-aa3a-e0a68e62e1c9
		summarizeBy: none
		sourceColumn: AppliesToMachineType

		annotation SummarizationSetBy = Automatic

	partition Dim_SparePart = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"UnitCostINR", type number}, {"MinStock", Int64.Type}, {"CurrentStock", Int64.Type}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"AppliesToMachineType", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
