/// Spare parts catalogue with stock and minimum levels.
table Dim_SparePart
	lineageTag: 49a69a67-6e65-4f40-b1d0-b494ac567e41

	column PartNo
		dataType: string
		lineageTag: 50ceff22-bf63-4ddf-9e71-ef5785a2492d
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 474ab824-2085-4fc6-b83e-05a2e35e3931
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7e284edc-f16b-4c4c-b068-04a089131769
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: c71eebb3-4e85-4895-bc0f-88b2ca68f481
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 8249d638-9cbe-4df7-b182-53b7644163b0
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column MinStock
		dataType: int64
		formatString: #,0
		lineageTag: fe33f5dc-0e58-42af-930f-e9fec17520ba
		summarizeBy: none
		sourceColumn: MinStock

		annotation SummarizationSetBy = Automatic

	column CurrentStock
		dataType: int64
		formatString: #,0
		lineageTag: d67dbe6d-a7c7-4ae8-817a-1a941f22e7f2
		summarizeBy: none
		sourceColumn: CurrentStock

		annotation SummarizationSetBy = Automatic

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: ecb61592-c7e4-487d-b9f2-e7340d6d592f
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: 121da8fe-4271-4368-b9e5-f15a8836d28e
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column AppliesToMachineType
		dataType: string
		lineageTag: 4505c380-3b13-4c75-a7ff-ac18587f678d
		summarizeBy: none
		sourceColumn: AppliesToMachineType

		annotation SummarizationSetBy = Automatic

	partition Dim_SparePart = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"UnitCostINR", type number}, {"MinStock", Int64.Type}, {"CurrentStock", Int64.Type}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"AppliesToMachineType", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
