/// Marked date table. One row per day, 2024-01-01 to 2028-12-31.
table Dim_Date
	dataCategory: Time
	lineageTag: 77553776-4e47-4307-b5d9-97ebd4214475

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 32d7d5ef-63fa-4b52-869c-d243b0116d39
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: f3ce0796-c773-4502-8324-5c6baebf69eb
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 62e7cc82-1f39-462d-8720-2d1801122a55
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: dd31d654-816c-4494-af2c-520eaea8c67f
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: string
		lineageTag: 66c59de5-284a-41a7-984b-45595fa5c55d
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: #,0
		lineageTag: b6929861-8109-41b7-8a9d-08dedbce0acc
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: #,0
		lineageTag: f37401af-6a07-47d8-8112-7d6968f39968
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: 8c37db9a-7e81-4e8c-a08d-501985b495de
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: #,0
		lineageTag: ed6367f9-442a-4bce-b26d-f845467dd375
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: string
		lineageTag: 41822588-4dee-4135-a121-221455c0e7c3
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: string
		lineageTag: 99d840b6-c7e2-46c7-b36e-0fea6b01ed81
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: ac5b8d86-3e73-47bd-af11-c95ff85c6635
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 0948e610-f6ff-4f64-80c0-afe577a89e92
		summarizeBy: none
		sourceColumn: FiscalMonthNo

		annotation SummarizationSetBy = Automatic

	column MonthSort
		dataType: string
		lineageTag: 4b2c71bf-98bd-4ac0-9523-475d8afdbc3b
		summarizeBy: none
		sourceColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column RelativeToToday
		dataType: string
		lineageTag: 5076fd24-3e27-42d5-a399-aca8859e9753
		summarizeBy: none
		sourceColumn: RelativeToToday

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source = ```
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2028, 12, 31),
				    Holidays = {
				        #date(2025,1,14), #date(2025,1,26), #date(2025,4,14), #date(2025,8,15),
				        #date(2025,10,20), #date(2025,10,21), #date(2025,12,25),
				        #date(2026,1,14), #date(2026,1,26), #date(2026,4,14), #date(2026,8,15),
				        #date(2026,11,8), #date(2026,12,25),
				        #date(2027,1,14), #date(2027,1,26), #date(2027,4,14)
				    },
				    Days = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				    Base = Table.FromList(Days, Splitter.SplitByNothing(), {"Date"}),
				    T0 = Table.TransformColumnTypes(Base, {{"Date", type date}}),
				    T1 = Table.AddColumn(T0, "Year", each Date.Year([Date]), Int64.Type),
				    T2 = Table.AddColumn(T1, "MonthNo", each Date.Month([Date]), Int64.Type),
				    T3 = Table.AddColumn(T2, "MonthShort", each Date.ToText([Date], "MMM"), type text),
				    T4 = Table.AddColumn(T3, "MonthKey", each Date.ToText([Date], "yyyy-MM"), type text),
				    T5 = Table.AddColumn(T4, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    T6 = Table.AddColumn(T5, "Day", each Date.Day([Date]), Int64.Type),
				    T7 = Table.AddColumn(T6, "DayShort", each Date.ToText([Date], "ddd"), type text),
				    T8 = Table.AddColumn(T7, "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    T9 = Table.AddColumn(T8, "IsWeekend", each if Date.DayOfWeek([Date], Day.Monday) >= 5 then "Yes" else "No", type text),
				    TA = Table.AddColumn(T9, "IsHoliday", each if List.Contains(Holidays, [Date]) then "Yes" else "No", type text),
				    TB = Table.AddColumn(TA, "FinancialYear", each
				            let y = if Date.Month([Date]) >= 4 then Date.Year([Date]) else Date.Year([Date]) - 1
				            in "FY" & Text.End(Text.From(y), 2) & "-" & Text.End(Text.From(y + 1), 2), type text),
				    TC = Table.AddColumn(TB, "FiscalMonthNo", each Number.Mod(Date.Month([Date]) - 4, 12) + 1, Int64.Type),
				    TD = Table.AddColumn(TC, "MonthSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    TE = Table.AddColumn(TD, "RelativeToToday", each
				            if [Date] < Date.From(DateTime.LocalNow()) then "Past"
				            else if [Date] = Date.From(DateTime.LocalNow()) then "Today"
				            else "Future", type text)
				in
				    TE
				```

	annotation PBI_ResultType = Table
