/// PM task library, one checklist per machine family.
table Dim_Checklist
	lineageTag: 64e88126-b731-4fa3-a40b-d129a5a3fc59

	column ChecklistID
		dataType: string
		lineageTag: c8fef190-3f13-4c12-8a76-114184ebe018
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: 8fe596da-2833-4787-ae9e-dcd96893cc60
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 3aba6bcc-67c7-4106-99a7-0ee323c6bc87
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: e1cc51a9-7238-48ff-a586-f31a39c1a3ba
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: 8083437f-2916-4fcf-91e5-f54038cd24a8
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: e5056f84-e10e-4da0-a6bc-58e86acec0fa
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: 92b9bdf1-a8a3-43f2-b3b4-366406de64d3
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column EstMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 8aa18e5d-9df1-4c89-95ea-6f19484b755d
		summarizeBy: none
		sourceColumn: EstMinutes

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 09730fc1-2fa6-4059-8eee-298c40a0c6d1
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Checklist = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Checklist_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"EstMinutes", Int64.Type}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
