/// Machines. Every QR code resolves to a row here.
table Dim_Machine
	lineageTag: 566fe1bc-0f92-4e60-a65d-a55ffcea6a8b

	column MachineID
		dataType: string
		lineageTag: 64fac6aa-c174-4683-90a2-79aca4df5aaa
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 24fe2d9d-eced-414a-8c09-dc85206341e2
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 8295728b-8a18-4b50-ad8c-4a018aab5878
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 8be277da-1de7-484c-b97b-2c2cb3cda366
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Make
		dataType: string
		lineageTag: 522de1af-988b-4488-8978-1f4b642c0445
		summarizeBy: none
		sourceColumn: Make

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: 3134267d-72f7-4e77-bf71-39862c6649e4
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column SerialNo
		dataType: string
		lineageTag: ce0a2588-0415-4664-97a7-6be8456c79f8
		summarizeBy: none
		sourceColumn: SerialNo

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a39f076e-c14f-4f1a-8acb-a88e8e8b354e
		summarizeBy: none
		sourceColumn: InstallDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Criticality
		dataType: string
		lineageTag: 4aca6a8c-57a0-46e7-b327-98de9cde80ea
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 13285936-7217-4b38-a518-e9aa9194c799
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: bdc2a983-e187-43e7-bd92-e275b333f0cc
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column PMStdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 10654551-2ab6-4255-9c15-4fa48bd97135
		summarizeBy: none
		sourceColumn: PMStdMinutes

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: 820df873-8e25-4ff6-92a9-80ec95085524
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 30649d8e-4f11-46d8-bf32-db5601a7e100
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Machine = m
		mode: import
		source = ```
				let
				    Source = fnSource("Machine_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"Make", type text}, {"Model", type text}, {"SerialNo", type text}, {"InstallDate", type date}, {"Criticality", type text}, {"Location", type text}, {"ChecklistID", type text}, {"PMStdMinutes", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
