/// Maintenance technicians. Each has a personal QR code.
table Dim_Technician
	lineageTag: 4047ad25-afa5-4d56-a1c3-629a8fb4b413

	column TechID
		dataType: string
		lineageTag: 556e68e7-c657-48d8-9fa0-1b9f319a93a5
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: 6fd11cc3-3105-42b3-8e79-86986e2db95b
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: 50eb5cc3-e4c7-479f-b6d1-299ca4adf611
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: 5347f8f5-04b7-4e31-9497-6072526fe5c8
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column SkillGroup
		dataType: string
		lineageTag: 12c1f83c-2d78-4e66-b1a5-8c2b0b8f0d83
		summarizeBy: none
		sourceColumn: SkillGroup

		annotation SummarizationSetBy = Automatic

	column PrimaryArea
		dataType: string
		lineageTag: 7ed4f43f-3eaf-41fd-986e-f7df179d8e5e
		summarizeBy: none
		sourceColumn: PrimaryArea

		annotation SummarizationSetBy = Automatic

	column DailyCapacityMin
		dataType: int64
		formatString: #,0
		lineageTag: 932ea034-6fe4-4675-bae1-0e6e1052b744
		summarizeBy: none
		sourceColumn: DailyCapacityMin

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: 048f636a-b645-4c62-8bb0-ef94e675d1e4
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 182513f7-e9c9-436d-ba4d-56779900b569
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Technician = m
		mode: import
		source = ```
				let
				    Source = fnSource("Technician_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"TechID", type text}, {"TechName", type text}, {"Email", type text}, {"Shift", type text}, {"SkillGroup", type text}, {"PrimaryArea", type text}, {"DailyCapacityMin", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
