/// Marked date table. One row per day, 2024-01-01 to 2028-12-31.
table Dim_Date
	dataCategory: Time
	lineageTag: 091a9921-3a71-4512-b057-0218f2870c41

	column Date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 429c6b05-ca15-4fda-bd8b-50b465b0bdcd
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: 1b2a29b6-5ea9-41ee-8e49-08e3e86097a7
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: a5d9ffb1-fe5c-42e0-b99f-18b1def732e1
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthShort
		dataType: string
		lineageTag: 4813e90c-8b97-462f-a270-d7074a1a0b01
		summarizeBy: none
		sourceColumn: MonthShort
		sortByColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column MonthKey
		dataType: string
		lineageTag: fc49ea68-7436-4d34-a742-1708cfe1d903
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: #,0
		lineageTag: e9c729f0-775c-4b7c-a5b3-75cd64ba5770
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: #,0
		lineageTag: 463f9415-ad59-4ad0-a4ba-10ef5463489c
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayShort
		dataType: string
		lineageTag: 86501b93-db2f-4fed-90c6-1585b4e10191
		summarizeBy: none
		sourceColumn: DayShort

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: #,0
		lineageTag: 67177ac0-61f7-48e4-bbea-7176416c3e10
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: string
		lineageTag: 7bc6cb07-cc72-4f4e-8310-c17026efd321
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		dataType: string
		lineageTag: d5b52665-1420-4291-b563-93cf28cb38bc
		summarizeBy: none
		sourceColumn: IsHoliday

		annotation SummarizationSetBy = Automatic

	column FinancialYear
		dataType: string
		lineageTag: 60a7bceb-2ca0-4460-bc30-e6e79bd0cded
		summarizeBy: none
		sourceColumn: FinancialYear

		annotation SummarizationSetBy = Automatic

	column FiscalMonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 6565cecf-a7ca-43b5-b707-dd5f56642ee5
		summarizeBy: none
		sourceColumn: FiscalMonthNo

		annotation SummarizationSetBy = Automatic

	column MonthSort
		dataType: string
		lineageTag: 0a4309e1-4455-40b1-95fb-2f9d0307a552
		summarizeBy: none
		sourceColumn: MonthSort

		annotation SummarizationSetBy = Automatic

	column RelativeToToday
		dataType: string
		lineageTag: 7efacae1-d22a-4b82-b4e1-88f64337a393
		summarizeBy: none
		sourceColumn: RelativeToToday

		annotation SummarizationSetBy = Automatic

	partition Dim_Date = m
		mode: import
		source = ```
				let
				    StartDate = #date(2024, 1, 1),
				    EndDate = #date(2028, 12, 31),
				    Holidays = {
				        #date(2025,1,14), #date(2025,1,26), #date(2025,4,14), #date(2025,8,15),
				        #date(2025,10,20), #date(2025,10,21), #date(2025,12,25),
				        #date(2026,1,14), #date(2026,1,26), #date(2026,4,14), #date(2026,8,15),
				        #date(2026,11,8), #date(2026,12,25),
				        #date(2027,1,14), #date(2027,1,26), #date(2027,4,14)
				    },
				    Days = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				    Base = Table.FromList(Days, Splitter.SplitByNothing(), {"Date"}),
				    T0 = Table.TransformColumnTypes(Base, {{"Date", type date}}),
				    T1 = Table.AddColumn(T0, "Year", each Date.Year([Date]), Int64.Type),
				    T2 = Table.AddColumn(T1, "MonthNo", each Date.Month([Date]), Int64.Type),
				    T3 = Table.AddColumn(T2, "MonthShort", each Date.ToText([Date], "MMM"), type text),
				    T4 = Table.AddColumn(T3, "MonthKey", each Date.ToText([Date], "yyyy-MM"), type text),
				    T5 = Table.AddColumn(T4, "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
				    T6 = Table.AddColumn(T5, "Day", each Date.Day([Date]), Int64.Type),
				    T7 = Table.AddColumn(T6, "DayShort", each Date.ToText([Date], "ddd"), type text),
				    T8 = Table.AddColumn(T7, "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    T9 = Table.AddColumn(T8, "IsWeekend", each if Date.DayOfWeek([Date], Day.Monday) >= 5 then "Yes" else "No", type text),
				    TA = Table.AddColumn(T9, "IsHoliday", each if List.Contains(Holidays, [Date]) then "Yes" else "No", type text),
				    TB = Table.AddColumn(TA, "FinancialYear", each
				            let y = if Date.Month([Date]) >= 4 then Date.Year([Date]) else Date.Year([Date]) - 1
				            in "FY" & Text.End(Text.From(y), 2) & "-" & Text.End(Text.From(y + 1), 2), type text),
				    TC = Table.AddColumn(TB, "FiscalMonthNo", each Number.Mod(Date.Month([Date]) - 4, 12) + 1, Int64.Type),
				    TD = Table.AddColumn(TC, "MonthSort", each Date.Year([Date]) * 100 + Date.Month([Date]), Int64.Type),
				    TE = Table.AddColumn(TD, "RelativeToToday", each
				            if [Date] < Date.From(DateTime.LocalNow()) then "Past"
				            else if [Date] = Date.From(DateTime.LocalNow()) then "Today"
				            else "Future", type text)
				in
				    TE
				```

	annotation PBI_ResultType = Table
