/// Spare parts catalogue with stock and minimum levels.
table Dim_SparePart
	lineageTag: c498ecf9-6bf4-4d73-bf82-68be08176b89

	column PartNo
		dataType: string
		lineageTag: 6cc114fb-93b3-4d94-ad3c-7bbc0fae3a93
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: aa1c9045-081c-47d6-bc1a-6b7aab860a35
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: fd623ace-74d3-4290-a3cb-43e9bd5b2c65
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: ea487622-df2b-4ebb-82de-79225a6a3b07
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: d6b63ff9-742a-4fc0-98b7-775e0e5083ef
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column MinStock
		dataType: int64
		formatString: #,0
		lineageTag: 35db4e09-fe51-495e-8826-9e9c1e88aabf
		summarizeBy: none
		sourceColumn: MinStock

		annotation SummarizationSetBy = Automatic

	column CurrentStock
		dataType: int64
		formatString: #,0
		lineageTag: 3f14bad9-fbc5-48f5-a122-031903855140
		summarizeBy: none
		sourceColumn: CurrentStock

		annotation SummarizationSetBy = Automatic

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: f10847e2-9f2b-43c9-b8ec-b18a309b69a1
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: f6219be7-594f-4ef9-9640-fc3b2d708b80
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column AppliesToMachineType
		dataType: string
		lineageTag: 2d0ca487-e50f-4260-bb78-93e15a9178e1
		summarizeBy: none
		sourceColumn: AppliesToMachineType

		annotation SummarizationSetBy = Automatic

	partition Dim_SparePart = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"UnitCostINR", type number}, {"MinStock", Int64.Type}, {"CurrentStock", Int64.Type}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"AppliesToMachineType", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
