/// PM task library, one checklist per machine family.
table Dim_Checklist
	lineageTag: c09f3d64-b34c-42f9-bd92-b2c496647a14

	column ChecklistID
		dataType: string
		lineageTag: 8ffc6e68-0be5-4d3c-9696-1168ce7a9e69
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: 59a4ebd4-a933-4f8a-8acd-0d1f42121bf0
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 660b80f5-7144-4b54-bc53-6dbd43952472
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: b8eb4313-a085-4c7e-bb92-65f4bc22391b
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: c20b3e19-59b6-4f12-b4a6-cf1aa7f3f244
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: c127c9eb-80dc-4d72-bdbf-6271905928ab
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: eddb946f-ef7a-4f08-8478-6391f46f6ee4
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column EstMinutes
		dataType: int64
		formatString: #,0
		lineageTag: b4337542-dcc6-4993-8bc7-00599baf90d8
		summarizeBy: none
		sourceColumn: EstMinutes

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 2afc6648-d308-46f0-8908-7f57b6633e3f
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Checklist = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Checklist_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"EstMinutes", Int64.Type}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
