/// PM task library, one checklist per machine family.
table Dim_Checklist
	lineageTag: cb5ac64a-502f-4cce-bfdc-b5408e52aa37

	column ChecklistID
		dataType: string
		lineageTag: b790a827-a4fc-494a-b5d1-a74797cd658d
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: ec7b0ecb-7aee-49c8-a241-5c97b2b64109
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 4f177904-22b3-4311-bc8a-8d8942e5dafd
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: dd991521-f617-4715-bee6-d4cbddd83155
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: d12fd66d-e38d-4eea-9577-61c693452d90
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: 5706ff02-6140-4691-9a4c-1b91563279d7
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: cf23312a-63e9-461c-a7ab-b131da1dd46b
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column EstMinutes
		dataType: int64
		formatString: #,0
		lineageTag: fac6027e-1b65-4658-adeb-da80c9061b9f
		summarizeBy: none
		sourceColumn: EstMinutes

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 219a79e5-989f-48a8-a93b-dd95ea707645
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Checklist = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Checklist_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"EstMinutes", Int64.Type}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
