/// Spare parts catalogue with stock and minimum levels.
table Dim_SparePart
	lineageTag: 36aeeeff-2cc0-422c-bdae-f3339340862b

	column PartNo
		dataType: string
		lineageTag: e5a978f1-7b96-44d1-960e-8c88a765b326
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: d6ce4317-a555-4f23-bbba-d607028fdad2
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9a8330d8-07c2-42f9-a41a-3179019e610d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 386a357f-55c0-4ff3-8e12-37dd98c80069
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 21cd8371-a141-44b4-aee2-5e432aeee33a
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column MinStock
		dataType: int64
		formatString: #,0
		lineageTag: fe54edbb-8bbd-4da0-88e6-e903bb874087
		summarizeBy: none
		sourceColumn: MinStock

		annotation SummarizationSetBy = Automatic

	column CurrentStock
		dataType: int64
		formatString: #,0
		lineageTag: 668d887d-7525-4779-a690-0449402ed9bd
		summarizeBy: none
		sourceColumn: CurrentStock

		annotation SummarizationSetBy = Automatic

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: 6c75f5ef-ab4d-4a67-861a-8f9582f57aec
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: 5e349c8d-a19e-418f-8ee3-c093ae0c0d09
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column AppliesToMachineType
		dataType: string
		lineageTag: 90ea293b-6f61-436c-a830-bdb0769d5472
		summarizeBy: none
		sourceColumn: AppliesToMachineType

		annotation SummarizationSetBy = Automatic

	partition Dim_SparePart = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"UnitCostINR", type number}, {"MinStock", Int64.Type}, {"CurrentStock", Int64.Type}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"AppliesToMachineType", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
