/// Machines. Every QR code resolves to a row here.
table Dim_Machine
	lineageTag: a2ab3dc4-db82-4f2a-9fe3-2473189ea0cd

	column MachineID
		dataType: string
		lineageTag: 1437f139-6fcc-4a5b-a0fd-c734428f2309
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: f617f4ad-48eb-49d7-9c74-8ce47414889d
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 58008a45-a894-4d5e-a9ee-ef13854797c4
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: b4b169ca-6a39-4027-a7fb-47bafdd4a456
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Make
		dataType: string
		lineageTag: 0cda6963-e0a9-4438-917e-73b3a7b95988
		summarizeBy: none
		sourceColumn: Make

		annotation SummarizationSetBy = Automatic

	column Model
		dataType: string
		lineageTag: f8a781f6-f0d0-4add-b3d8-96cf85a6a775
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column SerialNo
		dataType: string
		lineageTag: 7cb06e95-a9d3-4e7a-b6dc-c23444511b44
		summarizeBy: none
		sourceColumn: SerialNo

		annotation SummarizationSetBy = Automatic

	column InstallDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 6f84d0e7-79e2-4741-87a9-ce23b498c82c
		summarizeBy: none
		sourceColumn: InstallDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Criticality
		dataType: string
		lineageTag: a03fb638-d392-45c4-9c04-c24131b39969
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: bf72b508-27e8-4e08-9f82-abb66a9c39e7
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: 6ec9f865-dce9-48ef-91d1-3b82a4e12d06
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column PMStdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 72c1cce3-1bc0-446c-912a-fcf4efd59780
		summarizeBy: none
		sourceColumn: PMStdMinutes

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: fa0903d9-9cdc-417c-9218-b7687eb95ca4
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: d3562667-a4ea-4303-8a55-632499914e26
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Machine = m
		mode: import
		source = ```
				let
				    Source = fnSource("Machine_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"Make", type text}, {"Model", type text}, {"SerialNo", type text}, {"InstallDate", type date}, {"Criticality", type text}, {"Location", type text}, {"ChecklistID", type text}, {"PMStdMinutes", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
