/// Maintenance technicians. Each has a personal QR code.
table Dim_Technician
	lineageTag: 5c737d45-d93a-428f-a3d9-9fa7646b149c

	column TechID
		dataType: string
		lineageTag: 053cb26f-c72f-4021-8971-b9941a66512e
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: c4601dbc-c19a-4168-bc11-94a45e000a86
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: f686d071-de15-4cd7-b0a7-b2e2d609ef1c
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: 3f1bfdb2-87ea-4d1e-af09-49c6609e0739
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column SkillGroup
		dataType: string
		lineageTag: 62c0ce77-1b91-4363-8946-8d368a19cf84
		summarizeBy: none
		sourceColumn: SkillGroup

		annotation SummarizationSetBy = Automatic

	column PrimaryArea
		dataType: string
		lineageTag: 0d3cf7fc-b5ac-47ca-a3f0-d7685fccbed2
		summarizeBy: none
		sourceColumn: PrimaryArea

		annotation SummarizationSetBy = Automatic

	column DailyCapacityMin
		dataType: int64
		formatString: #,0
		lineageTag: 1515731e-a3a4-4242-992f-1fcb901ca18d
		summarizeBy: none
		sourceColumn: DailyCapacityMin

		annotation SummarizationSetBy = Automatic

	column QRPayload
		dataType: string
		lineageTag: 1a4f5231-0381-4559-9de1-66f58690c88f
		summarizeBy: none
		sourceColumn: QRPayload

		annotation SummarizationSetBy = Automatic

	column Active
		dataType: string
		lineageTag: 31eacdf5-294a-498e-9085-693b76291514
		summarizeBy: none
		sourceColumn: Active

		annotation SummarizationSetBy = Automatic

	partition Dim_Technician = m
		mode: import
		source = ```
				let
				    Source = fnSource("Technician_Master"),
				    Typed = Table.TransformColumnTypes(Source, {{"TechID", type text}, {"TechName", type text}, {"Email", type text}, {"Shift", type text}, {"SkillGroup", type text}, {"PrimaryArea", type text}, {"DailyCapacityMin", Int64.Type}, {"QRPayload", type text}, {"Active", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
