/// Unplanned stoppages. Feeds MTBF, MTTR and availability.
table Fact_Breakdowns
	lineageTag: cfe0dbe1-ee38-434b-9403-625c159932eb

	column BreakdownID
		dataType: string
		lineageTag: f56b3930-a8c3-4c39-b382-f2152b119a07
		summarizeBy: none
		sourceColumn: BreakdownID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 633ee75c-823e-4412-808e-1d8e9500b3bb
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: ddf6efe2-1c9b-42dd-ac21-1eee9017b1bb
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 7af99be4-3688-4bb2-889e-82beb37eedce
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: d5e66518-5ad1-480f-afed-a4a7710bef34
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 7c266230-e36a-471b-adf0-5e20fb1edc17
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 138942ae-8bfd-4b63-b36d-623129401a4c
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 6c238a76-15c7-4e86-bf1a-2135d8c8c0d1
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column ReportedDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 2300939a-6b83-4c43-b9d3-714fa277a629
		summarizeBy: none
		sourceColumn: ReportedDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RestoredDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: b9242ef3-5c31-4415-8992-49e9da888bfb
		summarizeBy: none
		sourceColumn: RestoredDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeMinutes
		dataType: int64
		formatString: #,0
		lineageTag: e22f0b50-40ed-420c-a190-83e2b93f8597
		summarizeBy: none
		sourceColumn: DowntimeMinutes

		annotation SummarizationSetBy = Automatic

	column ResponseMinutes
		dataType: int64
		formatString: #,0
		lineageTag: ecbb20a5-ead4-4b05-a88c-215ecfc938c5
		summarizeBy: none
		sourceColumn: ResponseMinutes

		annotation SummarizationSetBy = Automatic

	column FailureMode
		dataType: string
		lineageTag: f6997484-49ab-4329-ba21-5b709f92563e
		summarizeBy: none
		sourceColumn: FailureMode

		annotation SummarizationSetBy = Automatic

	column FailureCategory
		dataType: string
		lineageTag: a984a8ca-ac90-4488-8c3e-60965477d466
		summarizeBy: none
		sourceColumn: FailureCategory

		annotation SummarizationSetBy = Automatic

	column RootCause
		dataType: string
		lineageTag: 5fa30d7e-6892-48a1-9ae7-8b9e26b15758
		summarizeBy: none
		sourceColumn: RootCause

		annotation SummarizationSetBy = Automatic

	column ActionTaken
		dataType: string
		lineageTag: 50e20fc0-dc4d-4c57-9422-19cb8f0ff4ab
		summarizeBy: none
		sourceColumn: ActionTaken

		annotation SummarizationSetBy = Automatic

	column ReportedBy
		dataType: string
		lineageTag: acd4e1c0-1b22-4b20-aeca-65becf73df0e
		summarizeBy: none
		sourceColumn: ReportedBy

		annotation SummarizationSetBy = Automatic

	column AttendedTechID
		dataType: string
		lineageTag: 60fbca74-f544-4af6-8bd8-64a9c0019a5e
		summarizeBy: none
		sourceColumn: AttendedTechID

		annotation SummarizationSetBy = Automatic

	column AttendedTechName
		dataType: string
		lineageTag: 9c6cc204-3793-488c-9f60-205ac6b004f4
		summarizeBy: none
		sourceColumn: AttendedTechName

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 864d8d09-af69-4849-920a-3bb4e4390335
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SpareUsed
		dataType: string
		lineageTag: b4b4a504-9192-4ff1-8c75-274292bef5d2
		summarizeBy: none
		sourceColumn: SpareUsed

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: b9849f68-9a6c-45d8-9d0f-852b53e04862
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ab61f175-295f-42ec-bc91-25b976e6e65e
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeHours
		dataType: double
		formatString: #,0.0
		lineageTag: b57bfc1b-4c76-4b4d-88dd-4b7ae858b9c2
		summarizeBy: none
		sourceColumn: DowntimeHours

		annotation SummarizationSetBy = Automatic

	partition Fact_Breakdowns = m
		mode: import
		source = ```
				let
				    Source = fnSource("Breakdown_Reports"),
				    Typed = Table.TransformColumnTypes(Source, {{"BreakdownID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineType", type text}, {"Criticality", type text}, {"ReportedDateTime", type datetime}, {"RestoredDateTime", type datetime}, {"DowntimeMinutes", Int64.Type}, {"ResponseMinutes", Int64.Type}, {"FailureMode", type text}, {"FailureCategory", type text}, {"RootCause", type text}, {"ActionTaken", type text}, {"ReportedBy", type text}, {"AttendedTechID", type text}, {"AttendedTechName", type text}, {"Status", type text}, {"SpareUsed", type text}, {"Severity", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ReportedDate", each Date.From([ReportedDateTime]), type date),
				    AddHrs = Table.AddColumn(AddDate, "DowntimeHours", each if [DowntimeMinutes] = null then null else [DowntimeMinutes] / 60, type number)
				in
				    AddHrs
				```

	annotation PBI_ResultType = Table
