/// Spare part requests raised from the machine QR.
table Fact_SpareRequests
	lineageTag: 002ee976-e6dc-4bc1-a93a-a941527fa246

	column RequestID
		dataType: string
		lineageTag: 7a9ba0e1-64ed-404d-8111-a1705776f76a
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: 41074aed-c160-428b-af2b-0b57b69d7330
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: b651e7ed-cd58-467c-9e05-d7d7188a579c
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 762651bb-7474-4af9-a686-4e06bcedeed6
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 5927321e-2ade-4cec-8c7c-d85056b8ea8b
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 1683d2fb-545f-49cc-891d-61ad57942d77
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: 9d90bc4d-6144-4a44-a1b5-fa31b9b7f64f
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 4ea1c1c7-45bb-4b89-abb5-e81d0913bac3
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: eb92bc7f-96db-45eb-a2b7-7c2aa1232ef7
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: f4f208a9-4f15-4e59-877a-efa68a777d97
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyRequested
		dataType: int64
		formatString: #,0
		lineageTag: 5faa3ea0-1a72-4670-ba27-a107cacafe7e
		summarizeBy: none
		sourceColumn: QtyRequested

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: ae12f892-1a77-4737-a0b6-8b81d97c4e8f
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 25d76b8f-ffc1-4ffd-90be-98ff107059ad
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column RequestedByTechID
		dataType: string
		lineageTag: 8db3ea4b-4a75-4b8d-a7c0-a24b74b2802c
		summarizeBy: none
		sourceColumn: RequestedByTechID

		annotation SummarizationSetBy = Automatic

	column RequestedByName
		dataType: string
		lineageTag: 6bd96ab7-bceb-4edf-9ba2-2ccf453288c9
		summarizeBy: none
		sourceColumn: RequestedByName

		annotation SummarizationSetBy = Automatic

	column RequestDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5e0482e8-7bd2-4eb4-b14b-0e138537792c
		summarizeBy: none
		sourceColumn: RequestDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Urgency
		dataType: string
		lineageTag: cd2c57b2-81a8-46ca-a23b-e35c35ec119a
		summarizeBy: none
		sourceColumn: Urgency

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 367a0472-d183-43b2-8579-3d01a33ca6fd
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ApprovedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 6c55d44b-3117-4af2-83c0-6d0eb9f4b99f
		summarizeBy: none
		sourceColumn: ApprovedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ApprovedBy
		dataType: string
		lineageTag: ec074461-e2a5-431a-8073-9450f8eeafae
		summarizeBy: none
		sourceColumn: ApprovedBy

		annotation SummarizationSetBy = Automatic

	column IssuedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 2cc3f9ec-141e-43ab-b166-b2474ea3b0a1
		summarizeBy: none
		sourceColumn: IssuedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: 6a29ea13-024a-46b1-8301-7a652a8671ea
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: afe0f378-dff6-4785-a3d4-7d9f501749cd
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column RejectionReason
		dataType: string
		lineageTag: f75657d2-95de-4ea8-937d-3ac25db2846e
		summarizeBy: none
		sourceColumn: RejectionReason

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareRequests = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Requests"),
				    Typed = Table.TransformColumnTypes(Source, {{"RequestID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyRequested", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"RequestedByTechID", type text}, {"RequestedByName", type text}, {"RequestDate", type date}, {"Urgency", type text}, {"Status", type text}, {"ApprovedDate", type date}, {"ApprovedBy", type text}, {"IssuedDate", type date}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"RejectionReason", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
