/// Monthly production standard hours per cell - the input that drives scheduling.
table Fact_StdHours
	lineageTag: 6bba6058-c788-406c-8023-e56ee64c0c5d

	column MonthKey
		dataType: string
		lineageTag: f8444c65-8e9a-402d-bcaf-72cf16826eaf
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: 549c496d-a6a4-4b6d-83cb-d5626405a8b4
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 1a66d691-61e1-49c6-8035-e1b14e743103
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: b8e648bc-6342-4f79-8f99-da9a8338ec27
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: c1bfb1c3-c85b-4d3b-bdd2-2e81cf735870
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 52773e37-a02b-4826-8e06-0231d8916096
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column StdHours
		dataType: double
		formatString: #,0.0
		lineageTag: 5015264e-999b-4b58-96ae-28567236cdc1
		summarizeBy: none
		sourceColumn: StdHours

		annotation SummarizationSetBy = Automatic

	column UploadedBy
		dataType: string
		lineageTag: 1649fab2-e80d-42ff-8de9-5e1e33c28949
		summarizeBy: none
		sourceColumn: UploadedBy

		annotation SummarizationSetBy = Automatic

	column UploadDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e67db61c-566b-4eb3-9f5f-51e9d3248897
		summarizeBy: none
		sourceColumn: UploadDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SourceFile
		dataType: string
		lineageTag: e8792504-4335-4672-ad0a-c63bf98fe548
		summarizeBy: none
		sourceColumn: SourceFile

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a2b8c3d4-1da8-4506-873a-aab5dec0ea2c
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_StdHours = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Standard_Hours"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"Year", Int64.Type}, {"MonthNo", Int64.Type}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"StdHours", type number}, {"UploadedBy", type text}, {"UploadDate", type date}, {"SourceFile", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date)
				in
				    AddMonthStart
				```

	annotation PBI_ResultType = Table
