/// One row per machine per PM cycle. The core transactional table.
table Fact_WorkOrders
	lineageTag: d27f72f0-d2c1-4eba-b132-cda66770c6b4

	column WOID
		dataType: string
		lineageTag: e87c8bc8-fb37-4f8f-8c49-1c516ee65008
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column CycleID
		dataType: string
		lineageTag: 58246550-a17b-48ff-a04f-6014255be437
		summarizeBy: none
		sourceColumn: CycleID

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: f3707ff3-cfbe-489b-809f-808044623318
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 2b33ea2f-6d72-4a62-acaf-ada0e84cd6fa
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 348ef63d-06fe-4ab9-8915-ae40d96f8ae3
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: b82149d0-535d-4606-b2bc-37077a8c6116
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: ac2be772-1756-49b6-82c9-9dd29740ac95
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 3d598826-da65-4763-931a-5a60036df1e0
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 8bb2ad9a-cad6-4ac9-8f95-b7e6cad339ab
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMType
		dataType: string
		lineageTag: f1d19c3f-9dbb-4063-a678-9300456864b9
		summarizeBy: none
		sourceColumn: PMType

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: 638498ec-2eb4-444d-b6ad-95a26bb3a1d7
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column TriggerStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: b81a4d0e-f024-4e3f-8e6b-253e5885a35d
		summarizeBy: none
		sourceColumn: TriggerStdHrs

		annotation SummarizationSetBy = Automatic

	column PlanMonth
		dataType: string
		lineageTag: 2d8e779b-9819-4a2f-8747-0f09d9e45671
		summarizeBy: none
		sourceColumn: PlanMonth

		annotation SummarizationSetBy = Automatic

	column PlannedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: bf23bec3-ab24-47cd-81f6-10dea107e80b
		summarizeBy: none
		sourceColumn: PlannedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 58a1a493-8776-4c84-aae5-a36963b906f5
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AssignedTechID
		dataType: string
		lineageTag: 78bc3200-0c3f-417a-a75b-2c0922c0626e
		summarizeBy: none
		sourceColumn: AssignedTechID

		annotation SummarizationSetBy = Automatic

	column AssignedTechName
		dataType: string
		lineageTag: 9e765246-bcb3-43a1-936b-19da5429a475
		summarizeBy: none
		sourceColumn: AssignedTechName

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: 0f2516eb-55b4-4b81-aa3c-1e176129575f
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 5b207631-6a25-4f83-b341-ecd5d2dd1a6d
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ActualStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: af85b8fc-9252-4439-a5f4-0efcbf441669
		summarizeBy: none
		sourceColumn: ActualStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ActualEndDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 0123ee3f-acd4-496a-aa39-3b684a2cf284
		summarizeBy: none
		sourceColumn: ActualEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DurationMin
		dataType: int64
		formatString: #,0
		lineageTag: 04b96734-091f-4557-b9e7-09b8d9ab94a2
		summarizeBy: none
		sourceColumn: DurationMin

		annotation SummarizationSetBy = Automatic

	column ChecklistTotalTasks
		dataType: int64
		formatString: #,0
		lineageTag: c6967f10-7fc1-4b66-bfe3-61bfbf150924
		summarizeBy: none
		sourceColumn: ChecklistTotalTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistDoneTasks
		dataType: int64
		formatString: #,0
		lineageTag: ea275334-45e6-41e8-a099-c5fd29bf3eb8
		summarizeBy: none
		sourceColumn: ChecklistDoneTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistFailTasks
		dataType: int64
		formatString: #,0
		lineageTag: 672546a4-5581-4a4e-b9c4-30d0a06e2190
		summarizeBy: none
		sourceColumn: ChecklistFailTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistCompletionPct
		dataType: double
		formatString: #,0.0
		lineageTag: c014ef2a-a37c-4405-b01f-d53a280e504d
		summarizeBy: none
		sourceColumn: ChecklistCompletionPct

		annotation SummarizationSetBy = Automatic

	column MachineQRScanned
		dataType: string
		lineageTag: 4eaa5e3f-453f-49af-9768-3f0b2f83eb9c
		summarizeBy: none
		sourceColumn: MachineQRScanned

		annotation SummarizationSetBy = Automatic

	column PMResult
		dataType: string
		lineageTag: 2bf9e488-08be-494b-9b69-80a72d4ae69a
		summarizeBy: none
		sourceColumn: PMResult

		annotation SummarizationSetBy = Automatic

	column OnTimeFlag
		dataType: string
		lineageTag: ed859d9c-37ea-4500-894e-f658a6548b19
		summarizeBy: none
		sourceColumn: OnTimeFlag

		annotation SummarizationSetBy = Automatic

	column StdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: e6ce61ac-0bae-4a22-b65a-42d3ae30008c
		summarizeBy: none
		sourceColumn: StdMinutes

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 25e9b3f9-4df4-4844-adab-cdef2b8976b4
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_WorkOrders = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_WorkOrders"),
				    Typed = Table.TransformColumnTypes(Source, {{"WOID", type text}, {"CycleID", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineID", type text}, {"MachineName", type text}, {"MachineType", type text}, {"Criticality", type text}, {"PMType", type text}, {"TriggerType", type text}, {"TriggerStdHrs", type number}, {"PlanMonth", type text}, {"PlannedDate", type date}, {"DueDate", type date}, {"AssignedTechID", type text}, {"AssignedTechName", type text}, {"Shift", type text}, {"Status", type text}, {"ActualStartDate", type date}, {"ActualEndDate", type date}, {"DurationMin", Int64.Type}, {"ChecklistTotalTasks", Int64.Type}, {"ChecklistDoneTasks", Int64.Type}, {"ChecklistFailTasks", Int64.Type}, {"ChecklistCompletionPct", type number}, {"MachineQRScanned", type text}, {"PMResult", type text}, {"OnTimeFlag", type text}, {"StdMinutes", Int64.Type}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
