/// Cell hour counter month by month: opening, added, closing, trigger, carry-over.
table Fact_HourLedger
	lineageTag: ae47a9df-0fd8-4e9a-a9a8-5c14afddc4b7

	column MonthKey
		dataType: string
		lineageTag: 1af09cf5-527c-48da-b0d1-bcecd527ec7b
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 95f9053a-a25a-4e49-92e3-f23b89f7668c
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 88e1130e-ace5-4d1d-81f7-98d3508ffb4c
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column OpeningStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: abbdfbe4-1992-4ad6-8c79-56698042b2c7
		summarizeBy: none
		sourceColumn: OpeningStdHrs

		annotation SummarizationSetBy = Automatic

	column StdHoursAdded
		dataType: double
		formatString: #,0.0
		lineageTag: 1f5baa4a-cbe1-4368-9c04-f29fb43a2b0a
		summarizeBy: none
		sourceColumn: StdHoursAdded

		annotation SummarizationSetBy = Automatic

	column ClosingStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 5c09f7a0-7b06-4c4a-a5be-9503ae55820b
		summarizeBy: none
		sourceColumn: ClosingStdHrs

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: 8a5523dd-035c-47a9-bc4d-63259f75b1b4
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column PMTriggered
		dataType: string
		lineageTag: 039614c0-6aa3-491a-82c9-128b79828c9e
		summarizeBy: none
		sourceColumn: PMTriggered

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: 563e297f-1695-4e05-9382-439d1639729c
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column CarryOverAfterPM
		dataType: double
		formatString: #,0.0
		lineageTag: a19f3072-4ead-4b1f-802e-93bc6b509904
		summarizeBy: none
		sourceColumn: CarryOverAfterPM

		annotation SummarizationSetBy = Automatic

	column MonthsSinceLastPM
		dataType: int64
		formatString: #,0
		lineageTag: 229b206a-f0c0-4325-a8b6-364fa1fd77c3
		summarizeBy: none
		sourceColumn: MonthsSinceLastPM

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: 0ca500be-85c2-48ba-8be0-24f8440a6064
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: cfd286d9-c8b5-4c7a-b3fb-8741fde7ddd9
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PctOfThreshold
		dataType: double
		formatString: #,0.0
		lineageTag: 47f1b03d-092e-416e-8967-048ed9d23541
		summarizeBy: none
		sourceColumn: PctOfThreshold

		annotation SummarizationSetBy = Automatic

	partition Fact_HourLedger = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Hour_Ledger"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"CellID", type text}, {"CellName", type text}, {"OpeningStdHrs", type number}, {"StdHoursAdded", type number}, {"ClosingStdHrs", type number}, {"PMIntervalStdHrs", Int64.Type}, {"PMTriggered", type text}, {"TriggerType", type text}, {"CarryOverAfterPM", type number}, {"MonthsSinceLastPM", Int64.Type}, {"Scenario", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date),
				    AddPct = Table.AddColumn(AddMonthStart, "PctOfThreshold", each if [PMIntervalStdHrs] = null or [PMIntervalStdHrs] = 0 then null else [ClosingStdHrs] / [PMIntervalStdHrs], type number)
				in
				    AddPct
				```

	annotation PBI_ResultType = Table
