/// One row per machine per PM cycle. The core transactional table.
table Fact_WorkOrders
	lineageTag: 98810544-9ac7-4210-a797-c4ee34f7f30b

	column WOID
		dataType: string
		lineageTag: 37bb534d-45e6-45be-942d-f0b85fd8841b
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column CycleID
		dataType: string
		lineageTag: f5c07f53-68f4-4763-8054-0b12faa39f1e
		summarizeBy: none
		sourceColumn: CycleID

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: a0c6cdf5-3f6d-40dc-871e-9ddce601f749
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: e4d8b840-737c-44de-b768-453058d1f34b
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 334e6988-4820-482f-b9d6-015802ccd741
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 0bb33efe-f38f-46e9-94e0-72930b673490
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 077fd651-1301-4427-b3df-4be76b042cc3
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: f693538d-550d-4494-86f4-b4654849fcc8
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: deebe8fe-4af1-4e32-8293-f58a35e08c61
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMType
		dataType: string
		lineageTag: 7936750f-c353-42cd-b529-837741d8fd42
		summarizeBy: none
		sourceColumn: PMType

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: f2f47f4f-5929-4f55-bd9f-e07a8a35322c
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column TriggerStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 5de5cd14-74fe-49bb-a250-fee1915c9102
		summarizeBy: none
		sourceColumn: TriggerStdHrs

		annotation SummarizationSetBy = Automatic

	column PlanMonth
		dataType: string
		lineageTag: 3b69bf61-4779-4b7f-b900-ee48b202aef9
		summarizeBy: none
		sourceColumn: PlanMonth

		annotation SummarizationSetBy = Automatic

	column PlannedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d5fe6d8c-418c-4de9-9add-0fb69e8ae1f1
		summarizeBy: none
		sourceColumn: PlannedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d62af789-64bb-429f-911e-c0da70702643
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AssignedTechID
		dataType: string
		lineageTag: da6b2d2a-1b24-4a71-98c6-5618ee9b789f
		summarizeBy: none
		sourceColumn: AssignedTechID

		annotation SummarizationSetBy = Automatic

	column AssignedTechName
		dataType: string
		lineageTag: 6c8d4675-8fed-42bf-bc4f-1e6462d62d87
		summarizeBy: none
		sourceColumn: AssignedTechName

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: b67479f0-ea69-4e43-8703-4ba33d6f273c
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 1d3429bf-0092-4941-90f4-4a00219c762e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ActualStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 087b64e8-1934-4f26-9cf5-b5e28df9ad57
		summarizeBy: none
		sourceColumn: ActualStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ActualEndDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e118319d-690b-4461-8f71-17784606d56f
		summarizeBy: none
		sourceColumn: ActualEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DurationMin
		dataType: int64
		formatString: #,0
		lineageTag: fd77e945-082a-456b-9acd-8885f61343cd
		summarizeBy: none
		sourceColumn: DurationMin

		annotation SummarizationSetBy = Automatic

	column ChecklistTotalTasks
		dataType: int64
		formatString: #,0
		lineageTag: 683b99ca-ba69-45e4-b343-8f099681b1dd
		summarizeBy: none
		sourceColumn: ChecklistTotalTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistDoneTasks
		dataType: int64
		formatString: #,0
		lineageTag: e6cbf307-00cd-41a5-9b1d-5ec45c60d751
		summarizeBy: none
		sourceColumn: ChecklistDoneTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistFailTasks
		dataType: int64
		formatString: #,0
		lineageTag: ce843d88-7fdd-4ae3-afa9-2acaecc02c6b
		summarizeBy: none
		sourceColumn: ChecklistFailTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistCompletionPct
		dataType: double
		formatString: #,0.0
		lineageTag: d90efbc1-278c-4663-9f2a-a3c0a457be70
		summarizeBy: none
		sourceColumn: ChecklistCompletionPct

		annotation SummarizationSetBy = Automatic

	column MachineQRScanned
		dataType: string
		lineageTag: d72ab6b9-11ba-4432-87f1-a3275b116e66
		summarizeBy: none
		sourceColumn: MachineQRScanned

		annotation SummarizationSetBy = Automatic

	column PMResult
		dataType: string
		lineageTag: 32ec0e70-25cc-411c-b8d3-57b49261d371
		summarizeBy: none
		sourceColumn: PMResult

		annotation SummarizationSetBy = Automatic

	column OnTimeFlag
		dataType: string
		lineageTag: 8b5a3c5d-098c-4dce-9155-f7a7807af768
		summarizeBy: none
		sourceColumn: OnTimeFlag

		annotation SummarizationSetBy = Automatic

	column StdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 7a19957f-0bf7-4814-b222-edff312ace3f
		summarizeBy: none
		sourceColumn: StdMinutes

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 5bae5219-bf4e-4ce5-a091-2d61acbbe2a9
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_WorkOrders = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_WorkOrders"),
				    Typed = Table.TransformColumnTypes(Source, {{"WOID", type text}, {"CycleID", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineID", type text}, {"MachineName", type text}, {"MachineType", type text}, {"Criticality", type text}, {"PMType", type text}, {"TriggerType", type text}, {"TriggerStdHrs", type number}, {"PlanMonth", type text}, {"PlannedDate", type date}, {"DueDate", type date}, {"AssignedTechID", type text}, {"AssignedTechName", type text}, {"Shift", type text}, {"Status", type text}, {"ActualStartDate", type date}, {"ActualEndDate", type date}, {"DurationMin", Int64.Type}, {"ChecklistTotalTasks", Int64.Type}, {"ChecklistDoneTasks", Int64.Type}, {"ChecklistFailTasks", Int64.Type}, {"ChecklistCompletionPct", type number}, {"MachineQRScanned", type text}, {"PMResult", type text}, {"OnTimeFlag", type text}, {"StdMinutes", Int64.Type}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
