/// Monthly production standard hours per cell - the input that drives scheduling.
table Fact_StdHours
	lineageTag: 6e71305b-e4ef-4108-92ab-7023c092ae21

	column MonthKey
		dataType: string
		lineageTag: f1a1a010-d3e9-48b1-a0d0-6b75fd49d0cb
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: ea5b776d-5c00-4c1a-8dd4-7da5c976d030
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: ed35b396-0f2b-4894-80e3-e5c03d9daef7
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: af131d47-2445-4ab7-8c29-c6edcd5399d2
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: a0ba4a2f-f202-47c6-9d18-cba6d2b3796a
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 11574cca-6f80-4146-a020-58f4c00b16b2
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column StdHours
		dataType: double
		formatString: #,0.0
		lineageTag: 9b4a81fb-eea8-4538-9020-843020261fa7
		summarizeBy: none
		sourceColumn: StdHours

		annotation SummarizationSetBy = Automatic

	column UploadedBy
		dataType: string
		lineageTag: c316abbf-95db-4b34-b461-f7cba165c91f
		summarizeBy: none
		sourceColumn: UploadedBy

		annotation SummarizationSetBy = Automatic

	column UploadDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 756a88d8-d37a-43a2-b7bb-44b5cc0da885
		summarizeBy: none
		sourceColumn: UploadDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SourceFile
		dataType: string
		lineageTag: 3afd4d64-c52b-45fb-bf22-eda46f9cf331
		summarizeBy: none
		sourceColumn: SourceFile

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 1fb06e40-6d3f-4e00-b91d-e6dc035b03c5
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_StdHours = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Standard_Hours"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"Year", Int64.Type}, {"MonthNo", Int64.Type}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"StdHours", type number}, {"UploadedBy", type text}, {"UploadDate", type date}, {"SourceFile", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date)
				in
				    AddMonthStart
				```

	annotation PBI_ResultType = Table
