/// Every QR scan. Proves attendance at the machine.
table Fact_ScanLog
	lineageTag: 8b5d054c-dce5-4a31-a276-be06782afa4d

	column ScanID
		dataType: string
		lineageTag: 82d28eef-43fb-4c7f-b309-e1e47336a619
		summarizeBy: none
		sourceColumn: ScanID

		annotation SummarizationSetBy = Automatic

	column QRType
		dataType: string
		lineageTag: 267e8d8d-36b6-4eb5-b017-104d97447044
		summarizeBy: none
		sourceColumn: QRType

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 0d1eeb97-53f7-45ce-8061-8c3f314126a6
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: b575424f-bf74-49e8-a121-aa8cc5abfae6
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 5c10a01d-bdd0-49f4-92de-82157527ad10
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: 7396bca7-2f66-4a88-a251-c9f1ccaec044
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column ScanDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 2addac91-d45f-4794-869f-081fe51cd999
		summarizeBy: none
		sourceColumn: ScanDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LinkedWOID
		dataType: string
		lineageTag: cba5718d-8d06-4436-ba7a-64c7b44fc95c
		summarizeBy: none
		sourceColumn: LinkedWOID

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: 9459bd5e-2592-4661-8d93-d5db0382a88b
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: e2bbf91a-beff-4343-9160-efd2f9a771a2
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column ScanDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 151fd2a4-a91a-4f30-be62-78e1337a56d4
		summarizeBy: none
		sourceColumn: ScanDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_ScanLog = m
		mode: import
		source = ```
				let
				    Source = fnSource("QR_Scan_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"ScanID", type text}, {"QRType", type text}, {"MachineID", type text}, {"MachineName", type text}, {"TechID", type text}, {"TechName", type text}, {"ScanDateTime", type datetime}, {"LinkedWOID", type text}, {"Action", type text}, {"CellID", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ScanDate", each Date.From([ScanDateTime]), type date)
				in
				    AddDate
				```

	annotation PBI_ResultType = Table
