/// One row per machine per PM cycle. The core transactional table.
table Fact_WorkOrders
	lineageTag: dc63909b-4bad-4322-9e3b-65537bca9995

	column WOID
		dataType: string
		lineageTag: e935bfd6-8f55-4330-bced-9984467db434
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column CycleID
		dataType: string
		lineageTag: 139379f8-1271-4bef-aef4-dde020d162b7
		summarizeBy: none
		sourceColumn: CycleID

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 6d6861d9-d7e7-4d22-93f8-c06446e4d181
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 384838b6-ba29-448c-84e9-09d5c15a4d24
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 694d3f92-0eb5-435c-89be-5c7f74d4b58f
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: c8229392-cb3b-46d5-bde7-c4655dbc60a1
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: e32b5a02-d157-4d48-9802-5f02f2d2cfd8
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: fbc63425-1d9f-41ed-8275-7f3c51f7e1a3
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 16d708c4-6538-4b03-ac44-54b4a37f056a
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMType
		dataType: string
		lineageTag: d0a16e3e-7c8c-41c0-ae1c-447a07f71b9f
		summarizeBy: none
		sourceColumn: PMType

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: 85027f3c-25f2-44df-b2f5-8a421f908987
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column TriggerStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 756b521c-86d0-4d06-8547-9fffefcdaf79
		summarizeBy: none
		sourceColumn: TriggerStdHrs

		annotation SummarizationSetBy = Automatic

	column PlanMonth
		dataType: string
		lineageTag: 7c17dec4-4e25-4022-881b-bdbf96ff3bb9
		summarizeBy: none
		sourceColumn: PlanMonth

		annotation SummarizationSetBy = Automatic

	column PlannedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5cb9326b-0cff-49bd-bac1-16a99ab9abe1
		summarizeBy: none
		sourceColumn: PlannedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 92ca8023-5178-44f0-a98f-48b4286b6a5b
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AssignedTechID
		dataType: string
		lineageTag: 4e69896d-9858-4d1f-b9db-02b497fbd71e
		summarizeBy: none
		sourceColumn: AssignedTechID

		annotation SummarizationSetBy = Automatic

	column AssignedTechName
		dataType: string
		lineageTag: c55b13e4-9311-44f1-9fb1-e26b4c0bee5d
		summarizeBy: none
		sourceColumn: AssignedTechName

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: 2e342f00-0c1e-42af-b835-3d0b40b1607e
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: bd5429de-fee8-4d41-a808-5e4e6488938a
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ActualStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 58a7fa29-da4a-4bcf-8346-6838ef0a92f6
		summarizeBy: none
		sourceColumn: ActualStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ActualEndDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 27b02a23-6e5c-4bc2-b9cf-a2bb04c9cb2d
		summarizeBy: none
		sourceColumn: ActualEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DurationMin
		dataType: int64
		formatString: #,0
		lineageTag: 0e7f0aa6-c758-4aff-881f-2cdb1cd9858a
		summarizeBy: none
		sourceColumn: DurationMin

		annotation SummarizationSetBy = Automatic

	column ChecklistTotalTasks
		dataType: int64
		formatString: #,0
		lineageTag: 79e2e06a-dcc2-4ce7-ac8f-892855358da7
		summarizeBy: none
		sourceColumn: ChecklistTotalTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistDoneTasks
		dataType: int64
		formatString: #,0
		lineageTag: 81297f72-2251-4712-bbb5-e9e3432407ab
		summarizeBy: none
		sourceColumn: ChecklistDoneTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistFailTasks
		dataType: int64
		formatString: #,0
		lineageTag: 552ace59-7301-46cf-83ce-33877d69bbaa
		summarizeBy: none
		sourceColumn: ChecklistFailTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistCompletionPct
		dataType: double
		formatString: #,0.0
		lineageTag: 88c2a6bb-a767-4bbb-ba78-2eb4bdbd298f
		summarizeBy: none
		sourceColumn: ChecklistCompletionPct

		annotation SummarizationSetBy = Automatic

	column MachineQRScanned
		dataType: string
		lineageTag: ae2ad4b2-89aa-42f5-b3b0-caf1d7ecefda
		summarizeBy: none
		sourceColumn: MachineQRScanned

		annotation SummarizationSetBy = Automatic

	column PMResult
		dataType: string
		lineageTag: 68df6f96-bc5c-4f82-aaee-9d33baf9c126
		summarizeBy: none
		sourceColumn: PMResult

		annotation SummarizationSetBy = Automatic

	column OnTimeFlag
		dataType: string
		lineageTag: ddbfe4f0-26aa-40d0-8cdb-c82715fef663
		summarizeBy: none
		sourceColumn: OnTimeFlag

		annotation SummarizationSetBy = Automatic

	column StdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: b502582e-30a0-4bb1-ab88-e5e9c15b53de
		summarizeBy: none
		sourceColumn: StdMinutes

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 13d54661-9b17-4208-b406-2ec8f87dd601
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_WorkOrders = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_WorkOrders"),
				    Typed = Table.TransformColumnTypes(Source, {{"WOID", type text}, {"CycleID", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineID", type text}, {"MachineName", type text}, {"MachineType", type text}, {"Criticality", type text}, {"PMType", type text}, {"TriggerType", type text}, {"TriggerStdHrs", type number}, {"PlanMonth", type text}, {"PlannedDate", type date}, {"DueDate", type date}, {"AssignedTechID", type text}, {"AssignedTechName", type text}, {"Shift", type text}, {"Status", type text}, {"ActualStartDate", type date}, {"ActualEndDate", type date}, {"DurationMin", Int64.Type}, {"ChecklistTotalTasks", Int64.Type}, {"ChecklistDoneTasks", Int64.Type}, {"ChecklistFailTasks", Int64.Type}, {"ChecklistCompletionPct", type number}, {"MachineQRScanned", type text}, {"PMResult", type text}, {"OnTimeFlag", type text}, {"StdMinutes", Int64.Type}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
