/// What was actually fitted to the machine.
table Fact_SpareReplacements
	lineageTag: 800e8334-bdc3-4c7d-89b9-a0604718b660

	column ReplacementID
		dataType: string
		lineageTag: 12a6ad7f-f92d-4963-95e4-2b821d7b5493
		summarizeBy: none
		sourceColumn: ReplacementID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: f73fae59-c3ad-45f4-a366-7b704ceff56e
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: 5e6bf0f4-454f-466b-88a1-2028ac629c55
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column RequestID
		dataType: string
		lineageTag: 5149547b-e3e4-459d-b92c-3868089590b8
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 916018ef-404b-4c5b-b217-d14fd150a496
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: e781518e-eab2-4fc8-92b0-97c2fcdf704a
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: fed2c8a7-07b0-4a23-a927-2f813f2aa3be
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: f2af1343-6397-408f-b900-ef71ba4c6140
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: 8ea323f7-41eb-4a0a-b888-ea4458609eab
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 58218ef9-05f0-4cda-a5c4-40aadd93a51d
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 8f65ac73-51a1-43bd-8710-bdf612ac34ad
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 0797d9ce-4a9e-4a62-a5f4-46488ea98faf
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyReplaced
		dataType: int64
		formatString: #,0
		lineageTag: eefe8f22-4143-4746-b4af-0ef68a2bc60d
		summarizeBy: none
		sourceColumn: QtyReplaced

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 0eb13c41-04dd-4ab7-be4c-5ca24e216eae
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 935816fd-ce58-4528-9150-40de6df545b2
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column ReplacedByTechID
		dataType: string
		lineageTag: 82ed01d1-2018-44c1-93c4-2449ec45f1fb
		summarizeBy: none
		sourceColumn: ReplacedByTechID

		annotation SummarizationSetBy = Automatic

	column ReplacedByName
		dataType: string
		lineageTag: e0bc55c7-2bc7-4874-a093-922ddd45d3db
		summarizeBy: none
		sourceColumn: ReplacedByName

		annotation SummarizationSetBy = Automatic

	column ReplacedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 6689acc6-5626-44e7-b582-42a25539daf1
		summarizeBy: none
		sourceColumn: ReplacedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OldPartCondition
		dataType: string
		lineageTag: 6b2a64f4-2913-47ba-86df-cd2897cd602c
		summarizeBy: none
		sourceColumn: OldPartCondition

		annotation SummarizationSetBy = Automatic

	column WarrantyClaim
		dataType: string
		lineageTag: 26527669-a8f3-424a-a5d7-39293cdfb159
		summarizeBy: none
		sourceColumn: WarrantyClaim

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 9512f6ed-0a80-4d7e-8273-c09a99151660
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareReplacements = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Replacements"),
				    Typed = Table.TransformColumnTypes(Source, {{"ReplacementID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"RequestID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyReplaced", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"ReplacedByTechID", type text}, {"ReplacedByName", type text}, {"ReplacedDate", type date}, {"OldPartCondition", type text}, {"WarrantyClaim", type text}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
