/// Every QR scan. Proves attendance at the machine.
table Fact_ScanLog
	lineageTag: cab656d6-5ca3-49a2-8031-b5cba0f95c4b

	column ScanID
		dataType: string
		lineageTag: 8ce4e0f3-fba7-4353-8d3f-39d6f59d2970
		summarizeBy: none
		sourceColumn: ScanID

		annotation SummarizationSetBy = Automatic

	column QRType
		dataType: string
		lineageTag: fe8b200e-b777-4985-8aac-e33b4af47046
		summarizeBy: none
		sourceColumn: QRType

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: b14e3852-ed9a-4c88-85f8-d489d704c7a0
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 0fa1ce13-4170-478a-8b12-f279074b2a2d
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 9bfb78c4-7e56-4652-9f7e-8fb0e4aa73b5
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: f70b4d8f-c9cd-49c5-a2c7-85ddd26a6d24
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column ScanDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: d36385cf-dd2f-4b8b-8f86-f99c454203e3
		summarizeBy: none
		sourceColumn: ScanDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LinkedWOID
		dataType: string
		lineageTag: 78232691-1964-4bdb-bd86-ca88c3842b75
		summarizeBy: none
		sourceColumn: LinkedWOID

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: 7b183839-5dda-4865-9987-0ecab7283ac0
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 7b9eb796-9174-4b8c-978c-b6113d93e1c3
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column ScanDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 76e8b13d-eb70-4bdd-af28-67d7ac978670
		summarizeBy: none
		sourceColumn: ScanDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_ScanLog = m
		mode: import
		source = ```
				let
				    Source = fnSource("QR_Scan_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"ScanID", type text}, {"QRType", type text}, {"MachineID", type text}, {"MachineName", type text}, {"TechID", type text}, {"TechName", type text}, {"ScanDateTime", type datetime}, {"LinkedWOID", type text}, {"Action", type text}, {"CellID", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ScanDate", each Date.From([ScanDateTime]), type date)
				in
				    AddDate
				```

	annotation PBI_ResultType = Table
