/// Unplanned stoppages. Feeds MTBF, MTTR and availability.
table Fact_Breakdowns
	lineageTag: df0d1a43-e192-46d5-8a91-54e68d26a6ed

	column BreakdownID
		dataType: string
		lineageTag: 13807a33-173a-4448-8028-810486d0d9cb
		summarizeBy: none
		sourceColumn: BreakdownID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 71e9bd73-ee96-4049-af33-63f86e901ad6
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: b7a2dd74-d2c0-440b-9314-f52c20937160
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 8def40a4-b4b9-47b5-87bf-ffb21fb3e7a0
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 7a86a308-34eb-40b4-9743-3b474fd7e06a
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 81c03e25-fc64-400b-a6fe-b27cce3486ae
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: ae122d86-bdeb-48ba-a970-b6eaf069a1ad
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 72e320b4-8f1d-41e1-b0df-6a2113ebbd78
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column ReportedDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 0011f1ff-807d-4fb2-96c6-2db428d843ca
		summarizeBy: none
		sourceColumn: ReportedDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RestoredDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 8de5fbaa-9600-4ea6-97d4-50be403520d6
		summarizeBy: none
		sourceColumn: RestoredDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeMinutes
		dataType: int64
		formatString: #,0
		lineageTag: c43f4e67-b770-46ec-9ba5-c17ebc97f736
		summarizeBy: none
		sourceColumn: DowntimeMinutes

		annotation SummarizationSetBy = Automatic

	column ResponseMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 7e0e7179-60f2-412e-8c41-e0c06c735f24
		summarizeBy: none
		sourceColumn: ResponseMinutes

		annotation SummarizationSetBy = Automatic

	column FailureMode
		dataType: string
		lineageTag: c984e894-d85e-4835-9756-283afc385a2e
		summarizeBy: none
		sourceColumn: FailureMode

		annotation SummarizationSetBy = Automatic

	column FailureCategory
		dataType: string
		lineageTag: b7b3278d-f2ac-49ef-b59b-a216c04f7ca0
		summarizeBy: none
		sourceColumn: FailureCategory

		annotation SummarizationSetBy = Automatic

	column RootCause
		dataType: string
		lineageTag: 53075aef-8f17-455f-8eb3-067ca0e5d70e
		summarizeBy: none
		sourceColumn: RootCause

		annotation SummarizationSetBy = Automatic

	column ActionTaken
		dataType: string
		lineageTag: d22b9730-2ab1-47a7-a829-6766f2324466
		summarizeBy: none
		sourceColumn: ActionTaken

		annotation SummarizationSetBy = Automatic

	column ReportedBy
		dataType: string
		lineageTag: 5edb0b69-ed54-4002-929b-c7cfa241b9ec
		summarizeBy: none
		sourceColumn: ReportedBy

		annotation SummarizationSetBy = Automatic

	column AttendedTechID
		dataType: string
		lineageTag: 673dedbb-bdc3-4d52-90ce-1d5238754b18
		summarizeBy: none
		sourceColumn: AttendedTechID

		annotation SummarizationSetBy = Automatic

	column AttendedTechName
		dataType: string
		lineageTag: d28ed101-c577-4b7d-b4d0-ee22b43a1b7b
		summarizeBy: none
		sourceColumn: AttendedTechName

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: ef528997-4e0d-4025-b05a-d9effe4ce587
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SpareUsed
		dataType: string
		lineageTag: d1261596-d1bb-443b-ac8b-5d90217f6bd4
		summarizeBy: none
		sourceColumn: SpareUsed

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: 1ce5d628-fc44-48a6-9243-f30cfdf614cd
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 45982afe-ab66-4c47-a88f-73b30f9d480d
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeHours
		dataType: double
		formatString: #,0.0
		lineageTag: dcdbdab8-c09f-475f-b15a-b3465867a878
		summarizeBy: none
		sourceColumn: DowntimeHours

		annotation SummarizationSetBy = Automatic

	partition Fact_Breakdowns = m
		mode: import
		source = ```
				let
				    Source = fnSource("Breakdown_Reports"),
				    Typed = Table.TransformColumnTypes(Source, {{"BreakdownID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineType", type text}, {"Criticality", type text}, {"ReportedDateTime", type datetime}, {"RestoredDateTime", type datetime}, {"DowntimeMinutes", Int64.Type}, {"ResponseMinutes", Int64.Type}, {"FailureMode", type text}, {"FailureCategory", type text}, {"RootCause", type text}, {"ActionTaken", type text}, {"ReportedBy", type text}, {"AttendedTechID", type text}, {"AttendedTechName", type text}, {"Status", type text}, {"SpareUsed", type text}, {"Severity", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ReportedDate", each Date.From([ReportedDateTime]), type date),
				    AddHrs = Table.AddColumn(AddDate, "DowntimeHours", each if [DowntimeMinutes] = null then null else [DowntimeMinutes] / 60, type number)
				in
				    AddHrs
				```

	annotation PBI_ResultType = Table
