/// Spare part requests raised from the machine QR.
table Fact_SpareRequests
	lineageTag: 57a5e8d8-d5e1-4343-bad3-cb3f1ceafe8d

	column RequestID
		dataType: string
		lineageTag: 4634ffc7-c682-4153-9c9f-0878f4e671f8
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: e74bb0b9-30c8-4fe4-b9b4-d17432ef7cb9
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: 565a1813-eeef-4073-874c-405a2961c470
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 588688b0-8a72-452d-9054-ee6403f4e72a
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 4e4dc46e-4ad2-443f-967f-6ee276d9bbb0
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 36b5c3f7-b3de-4f30-8015-46c22aa01026
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: fb333ae0-e26e-4418-a462-d0c572709e19
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: bb2a4a0c-9867-4ab7-bf15-15942f7e343d
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 7cdf8faa-827a-463e-8177-93b6a1c316db
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 328d2d71-5a9c-42db-8729-6ee2ff83585b
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyRequested
		dataType: int64
		formatString: #,0
		lineageTag: d8695b68-03b4-405c-ab89-e408d1d95789
		summarizeBy: none
		sourceColumn: QtyRequested

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 7f0012c5-f118-441a-ba78-b3871b598b05
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 5cb4d0e9-1372-4e25-b544-e25e81983af0
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column RequestedByTechID
		dataType: string
		lineageTag: a3ea6dcc-c8d7-4c9a-9e82-43ad2d140bc1
		summarizeBy: none
		sourceColumn: RequestedByTechID

		annotation SummarizationSetBy = Automatic

	column RequestedByName
		dataType: string
		lineageTag: 9ee69457-24f8-4656-88b1-3298dc82b9e8
		summarizeBy: none
		sourceColumn: RequestedByName

		annotation SummarizationSetBy = Automatic

	column RequestDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 94a43caf-ad75-4709-be94-1c0e80f027f5
		summarizeBy: none
		sourceColumn: RequestDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Urgency
		dataType: string
		lineageTag: 654516f4-7c31-410b-a9ea-2ba647539127
		summarizeBy: none
		sourceColumn: Urgency

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f5cb48ab-9619-438c-81f7-38a2e50a1df5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ApprovedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 46afafb0-485c-40a1-b748-692bcd0729da
		summarizeBy: none
		sourceColumn: ApprovedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ApprovedBy
		dataType: string
		lineageTag: 35381ac6-907b-42e2-aaa7-dbd6ea0b3594
		summarizeBy: none
		sourceColumn: ApprovedBy

		annotation SummarizationSetBy = Automatic

	column IssuedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: bc71e0b5-89fe-4a85-b7da-07dd1315ff06
		summarizeBy: none
		sourceColumn: IssuedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: d0b26d00-8235-4a39-882c-0fc66df4659a
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: ab7d4f42-b57e-419a-85bc-4b6f7a4db6f4
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column RejectionReason
		dataType: string
		lineageTag: 76088f49-9e22-4fa3-a930-96af39e0ae78
		summarizeBy: none
		sourceColumn: RejectionReason

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareRequests = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Requests"),
				    Typed = Table.TransformColumnTypes(Source, {{"RequestID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyRequested", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"RequestedByTechID", type text}, {"RequestedByName", type text}, {"RequestDate", type date}, {"Urgency", type text}, {"Status", type text}, {"ApprovedDate", type date}, {"ApprovedBy", type text}, {"IssuedDate", type date}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"RejectionReason", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
