/// Every QR scan. Proves attendance at the machine.
table Fact_ScanLog
	lineageTag: 0d3ac094-4c29-439d-a532-301ba37d0d30

	column ScanID
		dataType: string
		lineageTag: ad607244-fa7c-43e5-ac85-df7c7e85cabc
		summarizeBy: none
		sourceColumn: ScanID

		annotation SummarizationSetBy = Automatic

	column QRType
		dataType: string
		lineageTag: ad6500d1-1f73-450c-85b1-4a5d4c47428f
		summarizeBy: none
		sourceColumn: QRType

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 05798ecd-67c0-4a08-ae52-53bc96a96b62
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 6f3eb04e-a493-4418-8d4f-4fdab5d1b068
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 97634331-2989-4fbb-b89c-2bac9731a5f2
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: 077f7e46-6a84-4778-8c5c-8fd2f2ca9ef4
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column ScanDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 2204dc68-2eb7-4d3e-a65c-40c6425943a1
		summarizeBy: none
		sourceColumn: ScanDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LinkedWOID
		dataType: string
		lineageTag: 02519334-0b63-4ffd-a04f-3f120b535921
		summarizeBy: none
		sourceColumn: LinkedWOID

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: 59fcceb9-4b48-4f75-be03-d66f257442db
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 007cc9f6-c1da-4f31-9864-3c405d2f2a50
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column ScanDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: dddf1dad-e19a-41c5-942f-b15ad5b53087
		summarizeBy: none
		sourceColumn: ScanDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_ScanLog = m
		mode: import
		source = ```
				let
				    Source = fnSource("QR_Scan_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"ScanID", type text}, {"QRType", type text}, {"MachineID", type text}, {"MachineName", type text}, {"TechID", type text}, {"TechName", type text}, {"ScanDateTime", type datetime}, {"LinkedWOID", type text}, {"Action", type text}, {"CellID", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ScanDate", each Date.From([ScanDateTime]), type date)
				in
				    AddDate
				```

	annotation PBI_ResultType = Table
