/// Cell hour counter month by month: opening, added, closing, trigger, carry-over.
table Fact_HourLedger
	lineageTag: e78f053e-ed60-48e9-a1af-841bce704081

	column MonthKey
		dataType: string
		lineageTag: 5da07c15-7759-403f-843d-7b344fc2c112
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: bdfe50c8-fc12-4130-a4b0-b04fbe1fcc10
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 21b07f23-d863-4f6b-b574-9d06d827b0a2
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column OpeningStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: acae74bd-774a-41e9-9641-63fdbc2bebc2
		summarizeBy: none
		sourceColumn: OpeningStdHrs

		annotation SummarizationSetBy = Automatic

	column StdHoursAdded
		dataType: double
		formatString: #,0.0
		lineageTag: 864cda64-5b1c-497c-850b-9e803ade834a
		summarizeBy: none
		sourceColumn: StdHoursAdded

		annotation SummarizationSetBy = Automatic

	column ClosingStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 23b7cbda-ec39-49c6-b35b-00b4ef2906f3
		summarizeBy: none
		sourceColumn: ClosingStdHrs

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: f5f4353c-0a62-409f-a857-1cd811501696
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column PMTriggered
		dataType: string
		lineageTag: 48a71bc3-5b1f-49ae-ba0e-2adaa0ed4500
		summarizeBy: none
		sourceColumn: PMTriggered

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: e693a326-13d7-4b55-b6bd-d7ce5241bf12
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column CarryOverAfterPM
		dataType: double
		formatString: #,0.0
		lineageTag: f77580f3-813f-4ddf-b83d-5893faee9b32
		summarizeBy: none
		sourceColumn: CarryOverAfterPM

		annotation SummarizationSetBy = Automatic

	column MonthsSinceLastPM
		dataType: int64
		formatString: #,0
		lineageTag: f753f0c9-2c75-4396-8726-9464b78d5980
		summarizeBy: none
		sourceColumn: MonthsSinceLastPM

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: 68ccc77f-989a-46a8-b37f-40bcca5e03f9
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 8a144fb5-fc49-42d1-a88a-7754136c6373
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PctOfThreshold
		dataType: double
		formatString: #,0.0
		lineageTag: ebb76999-4c95-42a7-be2e-63992495e765
		summarizeBy: none
		sourceColumn: PctOfThreshold

		annotation SummarizationSetBy = Automatic

	partition Fact_HourLedger = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Hour_Ledger"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"CellID", type text}, {"CellName", type text}, {"OpeningStdHrs", type number}, {"StdHoursAdded", type number}, {"ClosingStdHrs", type number}, {"PMIntervalStdHrs", Int64.Type}, {"PMTriggered", type text}, {"TriggerType", type text}, {"CarryOverAfterPM", type number}, {"MonthsSinceLastPM", Int64.Type}, {"Scenario", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date),
				    AddPct = Table.AddColumn(AddMonthStart, "PctOfThreshold", each if [PMIntervalStdHrs] = null or [PMIntervalStdHrs] = 0 then null else [ClosingStdHrs] / [PMIntervalStdHrs], type number)
				in
				    AddPct
				```

	annotation PBI_ResultType = Table
