/// One row per checklist task per work order - the audit evidence.
table Fact_ChecklistResults
	lineageTag: 0fd904a9-4e8a-44e6-b3fd-6ae3bd8dce1e

	column ResultID
		dataType: string
		lineageTag: aeb5835c-6c7f-44bc-9fb2-04edb3f19186
		summarizeBy: none
		sourceColumn: ResultID

		annotation SummarizationSetBy = Automatic

	column WOID
		dataType: string
		lineageTag: 8377f026-5fbc-4deb-8864-fb4663812094
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 973cdd40-2002-41b5-8295-c8a80b5afb95
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 897f697d-d9dc-4af9-815c-1c49fa557db5
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: c349ae5a-0252-4cf8-8256-e1e9552f9de3
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: 58defe34-45f0-4380-957c-bbc439f53a12
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: db177eb1-6bc4-473d-b2d4-b231b20f7290
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: e2375d08-b705-4503-9f78-5490fb53a3bf
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: 8636328b-b3a7-4ee4-9210-404e42cbb0ba
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: b3874979-c6cd-4614-b523-e01559643117
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: 21e12c8e-4807-4c7a-a048-074ab62561d2
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: b2d8210f-f02b-490b-8b48-065c34d855b0
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column MeasuredValue
		dataType: double
		formatString: #,0.0
		lineageTag: aa0bf679-d220-4fe1-8aab-c8ae7c0d422c
		summarizeBy: none
		sourceColumn: MeasuredValue

		annotation SummarizationSetBy = Automatic

	column Observation
		dataType: string
		lineageTag: 12756499-f44a-406e-86c2-a823816b635b
		summarizeBy: none
		sourceColumn: Observation

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 799d0c61-c4dd-495e-9771-52f904098dc1
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column RecordedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c35a1f33-1781-496e-9d62-b525217200b3
		summarizeBy: none
		sourceColumn: RecordedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AbnormalityRaised
		dataType: string
		lineageTag: 76f20e52-57d5-4963-8f17-d8af0ea2e74e
		summarizeBy: none
		sourceColumn: AbnormalityRaised

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: c1da1204-09ea-44ef-acd1-65d255e0b2e5
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Fact_ChecklistResults = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_ChecklistResults"),
				    Typed = Table.TransformColumnTypes(Source, {{"ResultID", type text}, {"WOID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"Result", type text}, {"MeasuredValue", type number}, {"Observation", type text}, {"TechID", type text}, {"RecordedDate", type date}, {"AbnormalityRaised", type text}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
