/// Every QR scan. Proves attendance at the machine.
table Fact_ScanLog
	lineageTag: 8b441e9a-8f2c-4a27-a6ae-b0f1e870d76d

	column ScanID
		dataType: string
		lineageTag: af2c505b-9d9f-4687-9b2d-a2918fa0eb8c
		summarizeBy: none
		sourceColumn: ScanID

		annotation SummarizationSetBy = Automatic

	column QRType
		dataType: string
		lineageTag: e8301357-3178-4952-bd75-9287c7436e52
		summarizeBy: none
		sourceColumn: QRType

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: cda40cec-8a97-4b3b-a76c-6922a14f08fe
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 10187979-fa19-4ed7-aceb-6fe689edcaca
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: ef11d3a8-239a-40d3-9a8f-a6850917b39d
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: 42655a09-305b-4e03-bbce-4f6b6a699d1f
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column ScanDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 51ed57ae-11cd-4d14-95af-22343d2767ac
		summarizeBy: none
		sourceColumn: ScanDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LinkedWOID
		dataType: string
		lineageTag: f877a5e7-e688-4e86-83c6-355fc60568ae
		summarizeBy: none
		sourceColumn: LinkedWOID

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: 89b1541f-7b10-4c32-bc74-0089a52e9ad9
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 052c3479-3ede-4688-a676-f9f7d21b7b7b
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column ScanDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 49831908-fc9b-4d79-9cd7-7fe115c595f5
		summarizeBy: none
		sourceColumn: ScanDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_ScanLog = m
		mode: import
		source = ```
				let
				    Source = fnSource("QR_Scan_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"ScanID", type text}, {"QRType", type text}, {"MachineID", type text}, {"MachineName", type text}, {"TechID", type text}, {"TechName", type text}, {"ScanDateTime", type datetime}, {"LinkedWOID", type text}, {"Action", type text}, {"CellID", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ScanDate", each Date.From([ScanDateTime]), type date)
				in
				    AddDate
				```

	annotation PBI_ResultType = Table
