/// One row per machine per PM cycle. The core transactional table.
table Fact_WorkOrders
	lineageTag: 6b2abedd-95a9-4955-96d0-90d24f34d723

	column WOID
		dataType: string
		lineageTag: 01e4878e-490c-4c18-a2bd-ff1247bdd737
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column CycleID
		dataType: string
		lineageTag: 5645cf73-6303-4f32-8c80-a02ac8e61d94
		summarizeBy: none
		sourceColumn: CycleID

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 855a06e2-2acc-4e8c-ac33-4e7aeb3f6d7e
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 710c1e03-2903-43fd-99bc-3d4e979fefb7
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 8435040e-718a-4ce3-89ed-e2890c0da517
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: df1bd1c0-5d31-409e-a242-4c7945eaff3a
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 9d009076-6607-4d42-9796-0b3505bb73f1
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 08d5ba5b-707a-4215-a600-e1ecdc1f4d3d
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 51b2ca74-c0ae-48e2-83bc-a6895051e4d4
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMType
		dataType: string
		lineageTag: f7ee5337-1543-4cca-9ad5-e955357360f3
		summarizeBy: none
		sourceColumn: PMType

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: 9a415ca9-cdeb-497d-9f04-35509c8587b6
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column TriggerStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 018d33b2-1430-47d2-81e5-6fb0049b17a5
		summarizeBy: none
		sourceColumn: TriggerStdHrs

		annotation SummarizationSetBy = Automatic

	column PlanMonth
		dataType: string
		lineageTag: 59e38733-66c9-4f7d-ab45-3fdbcd8027d4
		summarizeBy: none
		sourceColumn: PlanMonth

		annotation SummarizationSetBy = Automatic

	column PlannedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 605a68e2-92e5-416b-a1e9-2c73db643ec9
		summarizeBy: none
		sourceColumn: PlannedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 598e312c-6fba-4cec-9a2c-cafb7055f87f
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AssignedTechID
		dataType: string
		lineageTag: 514e1ffb-b3c2-4f14-bbd8-da1b88315415
		summarizeBy: none
		sourceColumn: AssignedTechID

		annotation SummarizationSetBy = Automatic

	column AssignedTechName
		dataType: string
		lineageTag: bfa68979-16c9-4d95-a608-94d3592c6adc
		summarizeBy: none
		sourceColumn: AssignedTechName

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: c4863c5f-2b5b-4fd3-9312-9c4cc03f4ee1
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0868c9f4-1341-4b9f-9104-acf44a4d98b7
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ActualStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 933cf989-8e92-4e23-be93-e7c15bcf6376
		summarizeBy: none
		sourceColumn: ActualStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ActualEndDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 979d97ae-1cda-4420-9106-7f8d2720dbd2
		summarizeBy: none
		sourceColumn: ActualEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DurationMin
		dataType: int64
		formatString: #,0
		lineageTag: 5f5b8ec3-a8b7-400a-bb1d-db9d288fb599
		summarizeBy: none
		sourceColumn: DurationMin

		annotation SummarizationSetBy = Automatic

	column ChecklistTotalTasks
		dataType: int64
		formatString: #,0
		lineageTag: 9adf1695-d654-493a-ab29-59f0013e4aef
		summarizeBy: none
		sourceColumn: ChecklistTotalTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistDoneTasks
		dataType: int64
		formatString: #,0
		lineageTag: 038c5469-6a95-4f68-9aa4-a701c76a766e
		summarizeBy: none
		sourceColumn: ChecklistDoneTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistFailTasks
		dataType: int64
		formatString: #,0
		lineageTag: 8db60ace-e8d7-4a75-ba75-2dd67a0203ab
		summarizeBy: none
		sourceColumn: ChecklistFailTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistCompletionPct
		dataType: double
		formatString: #,0.0
		lineageTag: 1d552997-1d9f-45da-befc-d09d601d8ca1
		summarizeBy: none
		sourceColumn: ChecklistCompletionPct

		annotation SummarizationSetBy = Automatic

	column MachineQRScanned
		dataType: string
		lineageTag: b998ae34-8c63-40a9-b738-fd9997373033
		summarizeBy: none
		sourceColumn: MachineQRScanned

		annotation SummarizationSetBy = Automatic

	column PMResult
		dataType: string
		lineageTag: 6b2d8fad-fe49-43f9-bf61-b230cff7435e
		summarizeBy: none
		sourceColumn: PMResult

		annotation SummarizationSetBy = Automatic

	column OnTimeFlag
		dataType: string
		lineageTag: 8a969f58-99a9-4c9c-b775-69df57664d04
		summarizeBy: none
		sourceColumn: OnTimeFlag

		annotation SummarizationSetBy = Automatic

	column StdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: f9e5d314-9c61-45ae-a4d8-43709c3794f1
		summarizeBy: none
		sourceColumn: StdMinutes

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: ea953372-098b-4822-b12b-4ac0bd53033f
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_WorkOrders = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_WorkOrders"),
				    Typed = Table.TransformColumnTypes(Source, {{"WOID", type text}, {"CycleID", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineID", type text}, {"MachineName", type text}, {"MachineType", type text}, {"Criticality", type text}, {"PMType", type text}, {"TriggerType", type text}, {"TriggerStdHrs", type number}, {"PlanMonth", type text}, {"PlannedDate", type date}, {"DueDate", type date}, {"AssignedTechID", type text}, {"AssignedTechName", type text}, {"Shift", type text}, {"Status", type text}, {"ActualStartDate", type date}, {"ActualEndDate", type date}, {"DurationMin", Int64.Type}, {"ChecklistTotalTasks", Int64.Type}, {"ChecklistDoneTasks", Int64.Type}, {"ChecklistFailTasks", Int64.Type}, {"ChecklistCompletionPct", type number}, {"MachineQRScanned", type text}, {"PMResult", type text}, {"OnTimeFlag", type text}, {"StdMinutes", Int64.Type}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
