/// One row per checklist task per work order - the audit evidence.
table Fact_ChecklistResults
	lineageTag: 7a052100-cb4f-4b8f-a608-4a9015c3726a

	column ResultID
		dataType: string
		lineageTag: bdb865ef-650f-4dd6-9a74-82bfd3b15b5d
		summarizeBy: none
		sourceColumn: ResultID

		annotation SummarizationSetBy = Automatic

	column WOID
		dataType: string
		lineageTag: a5aec7a6-5fdf-44eb-898b-cceef619fd76
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 9525ea33-bef0-4a69-866a-9c34b680ca5d
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 9bacf757-6834-4b08-b8de-4da25b4b5933
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: 33a7fc55-9070-47d8-b0d0-b72d955f0d15
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: 68bc0ea4-c8d0-4779-8b09-c893971c6a8c
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 785397b5-4fc6-49e0-ad86-ea5df8eea064
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: 319ea5a5-da9d-418c-9923-8ac5f07e3061
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: d56e553d-8436-4ef2-a073-13deb76ffbab
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: 00f51b79-7904-4c49-8df5-559edec3d6d2
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: dd9f96ec-bd61-4bbf-83df-5098789e544f
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: 869fb4de-2171-4fea-9e46-86b9af715418
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column MeasuredValue
		dataType: double
		formatString: #,0.0
		lineageTag: d9b43679-c22a-42c3-bb79-c6d78c8daa16
		summarizeBy: none
		sourceColumn: MeasuredValue

		annotation SummarizationSetBy = Automatic

	column Observation
		dataType: string
		lineageTag: cfc02cba-ea8f-4d00-bf13-3a8f5d0fd469
		summarizeBy: none
		sourceColumn: Observation

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 7b7c2add-b940-4dbc-a5ea-abaff3ac64c2
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column RecordedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: df0beda1-ebfc-4663-a6b8-35cdb4fafe4a
		summarizeBy: none
		sourceColumn: RecordedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AbnormalityRaised
		dataType: string
		lineageTag: b715c311-7ab5-45a3-87d4-e6bd938ef2e1
		summarizeBy: none
		sourceColumn: AbnormalityRaised

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 5fbe9094-f807-4f02-8be0-422b493b39fb
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Fact_ChecklistResults = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_ChecklistResults"),
				    Typed = Table.TransformColumnTypes(Source, {{"ResultID", type text}, {"WOID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"Result", type text}, {"MeasuredValue", type number}, {"Observation", type text}, {"TechID", type text}, {"RecordedDate", type date}, {"AbnormalityRaised", type text}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
