/// One row per checklist task per work order - the audit evidence.
table Fact_ChecklistResults
	lineageTag: 9aaa4507-5dc0-4446-94d2-5da8035545cc

	column ResultID
		dataType: string
		lineageTag: bc0a9f9d-652e-43f9-bcf3-2b086a09858d
		summarizeBy: none
		sourceColumn: ResultID

		annotation SummarizationSetBy = Automatic

	column WOID
		dataType: string
		lineageTag: f1ac8d4e-b0e4-45e8-bf63-d0007331e133
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 395e8233-dfa0-4b93-b705-2ce3fa13684a
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: a1454c03-7e39-4565-a839-1e50c14b9e59
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: 2e032959-8748-4eb3-84f2-3f441c9f12de
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: f44aa8da-b5a9-4152-91d1-fcfb42f90c18
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 4810ae42-4476-49bd-b97d-f0cf53676ecf
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: be286753-c824-4614-b57c-91b774edcd29
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: 2fa4c8ed-3853-4008-acfb-979251f31e61
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: 02c9018a-536e-4cfe-805d-ded6ba295b98
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: 5ddd7d61-1b04-4ad5-8403-b08e16acd5a5
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: 3f5ab438-f7f0-4689-b465-8f63e62fb0b1
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column MeasuredValue
		dataType: double
		formatString: #,0.0
		lineageTag: e072ea97-4434-4d60-8a3d-2104f6b74ea8
		summarizeBy: none
		sourceColumn: MeasuredValue

		annotation SummarizationSetBy = Automatic

	column Observation
		dataType: string
		lineageTag: e4a876f1-4f4a-452e-91fc-8a193dc4df05
		summarizeBy: none
		sourceColumn: Observation

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 31e48cdb-ae7b-42bd-833f-fd1dcfcc2daf
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column RecordedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e294770a-d93f-4458-b55e-233d44dba7ae
		summarizeBy: none
		sourceColumn: RecordedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AbnormalityRaised
		dataType: string
		lineageTag: 2982c569-b803-42ee-b1b9-f753c8b29167
		summarizeBy: none
		sourceColumn: AbnormalityRaised

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 1f067dc9-95b3-4d45-a0fa-6b84bd1b89bd
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Fact_ChecklistResults = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_ChecklistResults"),
				    Typed = Table.TransformColumnTypes(Source, {{"ResultID", type text}, {"WOID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"Result", type text}, {"MeasuredValue", type number}, {"Observation", type text}, {"TechID", type text}, {"RecordedDate", type date}, {"AbnormalityRaised", type text}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
