/// What was actually fitted to the machine.
table Fact_SpareReplacements
	lineageTag: 895df85b-29c7-4630-968d-45b5254096be

	column ReplacementID
		dataType: string
		lineageTag: 87fc5a19-eaff-456a-9dbd-b4cc055ebbfd
		summarizeBy: none
		sourceColumn: ReplacementID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: 6d4d6ab0-82c1-4c4d-9d1a-90f7eef72371
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: 84518f92-357d-45cf-b786-af3c2ee9e83f
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column RequestID
		dataType: string
		lineageTag: ac9af196-6951-4437-bc2f-25fa59652819
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: ead12c98-d6b5-4fa3-81a5-62fdb5fa7606
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 3868dd5a-c094-4d0e-8282-82b27c74c2bc
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 871d3a69-944b-4dd9-8dc3-0dc6acee2fb1
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 9763cf35-fcf8-4c4b-8e65-ec6a5456ff24
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: f2f4f4c6-dfc4-4be6-a2fd-665b9ba071f0
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 9de26b06-a900-48df-b8f6-26a0e9303300
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 49d0b201-28af-4700-8a4a-c6a2503ad0f1
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 7dcb6fbd-b277-4de3-81f1-9f79ccf76dff
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyReplaced
		dataType: int64
		formatString: #,0
		lineageTag: 37d4c6e5-6e0a-4536-bc5d-8137899d631a
		summarizeBy: none
		sourceColumn: QtyReplaced

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: d64994a3-c98a-40e1-b594-d6916bcd3f1a
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 3476c147-b617-4973-bf94-18f1df246b16
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column ReplacedByTechID
		dataType: string
		lineageTag: b7d285cb-f670-4ed6-9455-1f594db79d34
		summarizeBy: none
		sourceColumn: ReplacedByTechID

		annotation SummarizationSetBy = Automatic

	column ReplacedByName
		dataType: string
		lineageTag: 383780c1-4194-440f-93c6-e681be005227
		summarizeBy: none
		sourceColumn: ReplacedByName

		annotation SummarizationSetBy = Automatic

	column ReplacedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d895fd55-45e9-44b5-b69c-7bbdd676f10b
		summarizeBy: none
		sourceColumn: ReplacedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OldPartCondition
		dataType: string
		lineageTag: 961e19e4-c3b1-4b0d-97bf-ec1ea0d44f43
		summarizeBy: none
		sourceColumn: OldPartCondition

		annotation SummarizationSetBy = Automatic

	column WarrantyClaim
		dataType: string
		lineageTag: 81ad90fa-a70f-4f31-9c25-6652418daabf
		summarizeBy: none
		sourceColumn: WarrantyClaim

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: b17cc0ea-a736-4db2-8f76-11889f7c9b6c
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareReplacements = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Replacements"),
				    Typed = Table.TransformColumnTypes(Source, {{"ReplacementID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"RequestID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyReplaced", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"ReplacedByTechID", type text}, {"ReplacedByName", type text}, {"ReplacedDate", type date}, {"OldPartCondition", type text}, {"WarrantyClaim", type text}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
