/// Abnormalities - the early warning layer before a breakdown.
table Fact_Abnormalities
	lineageTag: e47331fe-735e-4816-bfcb-99d21a91ba41

	column AbnormalityID
		dataType: string
		lineageTag: b93d06a7-a886-47ca-823b-cedfd7b7ecd4
		summarizeBy: none
		sourceColumn: AbnormalityID

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 5cc10e9a-dc7c-4b79-80e0-187a6ab6ae33
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column SourceRefID
		dataType: string
		lineageTag: e0308140-a720-4f7d-b6f4-3743c9d286f5
		summarizeBy: none
		sourceColumn: SourceRefID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: d286be8a-0ab5-4c17-af28-d51db05ad95c
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 8ec918a9-432c-4ac3-b16a-18488c4d2065
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: d9f6aea5-0c8d-4ea6-98fd-33b8c6a5cad3
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 61165554-2c35-4921-a664-02272907591f
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: cb8d96d1-c240-486b-aac8-8394c39cd82c
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 52f631f2-79cd-4ecc-9ce2-5c911bf596cb
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: 372d3f5b-e999-4b79-9cb4-521d879119c9
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 8df8ee98-de95-4e1f-a96a-331f48342e11
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column ReportedByTechID
		dataType: string
		lineageTag: 8b060053-74ce-43f1-8956-7f0c6eb14651
		summarizeBy: none
		sourceColumn: ReportedByTechID

		annotation SummarizationSetBy = Automatic

	column ReportedByName
		dataType: string
		lineageTag: be30c3a9-5eed-4d7c-b311-6d576c2ebfd2
		summarizeBy: none
		sourceColumn: ReportedByName

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 647c0040-847d-439b-b7f0-ce979395af33
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: b0fadd24-7db3-458f-a003-8280cbcfddda
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ClosedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 347fe48e-2ac8-4876-b940-18aa71d1cfef
		summarizeBy: none
		sourceColumn: ClosedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CorrectiveAction
		dataType: string
		lineageTag: b6bd3779-cbb3-4e07-aba3-2bf9a41a8892
		summarizeBy: none
		sourceColumn: CorrectiveAction

		annotation SummarizationSetBy = Automatic

	column OwnerFunction
		dataType: string
		lineageTag: 15f9014b-0de2-4240-8f1c-dd86976b6e60
		summarizeBy: none
		sourceColumn: OwnerFunction

		annotation SummarizationSetBy = Automatic

	column EscalationRequired
		dataType: string
		lineageTag: f829678f-4575-41bc-8345-006b24f2795d
		summarizeBy: none
		sourceColumn: EscalationRequired

		annotation SummarizationSetBy = Automatic

	column PhotoURL
		dataType: string
		lineageTag: ee78401f-10c1-403c-bb06-bb31214bd33f
		summarizeBy: none
		sourceColumn: PhotoURL

		annotation SummarizationSetBy = Automatic

	partition Fact_Abnormalities = m
		mode: import
		source = ```
				let
				    Source = fnSource("Abnormality_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"AbnormalityID", type text}, {"Source", type text}, {"SourceRefID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Category", type text}, {"Severity", type text}, {"Description", type text}, {"ReportedByTechID", type text}, {"ReportedByName", type text}, {"ReportedDate", type date}, {"Status", type text}, {"ClosedDate", type date}, {"CorrectiveAction", type text}, {"OwnerFunction", type text}, {"EscalationRequired", type text}, {"PhotoURL", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
