/// Spare part requests raised from the machine QR.
table Fact_SpareRequests
	lineageTag: cfade7ed-cebe-4466-a811-dc848fa17b1e

	column RequestID
		dataType: string
		lineageTag: 38a971b3-347f-45bc-b9c9-9688d296b065
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: e9d8ce0a-560c-45d4-b4a6-2301514cf4ba
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: a09ab853-7bed-4b77-ba7c-1d43ec555006
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 9de07fa5-3c76-434f-a107-f9389d9dab02
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 10e6cff9-672e-470d-8af4-1b41ad5a2a21
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 16bb8029-f89b-406e-9995-dc5b949b3cf8
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: 3ad45825-ad1d-4259-bb50-868540fbdffa
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: f8364c09-6c1e-4f96-b322-19a6000f66f5
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 71b84e94-e317-41a6-90c1-b494fac83306
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 349d7a6a-b124-4d77-9cef-6f2a0e8503ee
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyRequested
		dataType: int64
		formatString: #,0
		lineageTag: d7838cf5-9768-4480-b801-15574ae6597d
		summarizeBy: none
		sourceColumn: QtyRequested

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: a789f330-c2c0-42e1-8cce-33c527fa69c1
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 60813fd9-7150-4103-85eb-c5f157909b2f
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column RequestedByTechID
		dataType: string
		lineageTag: d67d3215-4f5f-4e7c-9bec-8e311b5194c2
		summarizeBy: none
		sourceColumn: RequestedByTechID

		annotation SummarizationSetBy = Automatic

	column RequestedByName
		dataType: string
		lineageTag: 200ad408-0bfd-409b-b814-5fc2327c9bcc
		summarizeBy: none
		sourceColumn: RequestedByName

		annotation SummarizationSetBy = Automatic

	column RequestDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: ee16290b-18d5-472e-a735-6753127b8ab7
		summarizeBy: none
		sourceColumn: RequestDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Urgency
		dataType: string
		lineageTag: 2efbe907-6e54-43f9-95a4-bb7ba712dc75
		summarizeBy: none
		sourceColumn: Urgency

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0aff9d0a-5845-403d-8fe9-0d45baed6ff7
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ApprovedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: bf075927-5ae9-4b7b-a9b2-bc6b44a84d42
		summarizeBy: none
		sourceColumn: ApprovedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ApprovedBy
		dataType: string
		lineageTag: b8ff81ed-2548-40a7-b899-f666a2817ad8
		summarizeBy: none
		sourceColumn: ApprovedBy

		annotation SummarizationSetBy = Automatic

	column IssuedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d4581fa7-f49c-4539-94f0-ab5209288458
		summarizeBy: none
		sourceColumn: IssuedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: 34574cfe-fe05-479c-8aeb-a899dc53fd2e
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: ef0bc67c-4d52-4852-81f4-85301c0a352c
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column RejectionReason
		dataType: string
		lineageTag: c179226d-6ec0-43d7-8e94-0d953ee1d5f8
		summarizeBy: none
		sourceColumn: RejectionReason

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareRequests = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Requests"),
				    Typed = Table.TransformColumnTypes(Source, {{"RequestID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyRequested", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"RequestedByTechID", type text}, {"RequestedByName", type text}, {"RequestDate", type date}, {"Urgency", type text}, {"Status", type text}, {"ApprovedDate", type date}, {"ApprovedBy", type text}, {"IssuedDate", type date}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"RejectionReason", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
