/// Unplanned stoppages. Feeds MTBF, MTTR and availability.
table Fact_Breakdowns
	lineageTag: 430642aa-9f11-4042-a63c-de803a26cd33

	column BreakdownID
		dataType: string
		lineageTag: 77aa28ed-f5f0-4106-9c8c-4752bfec087b
		summarizeBy: none
		sourceColumn: BreakdownID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 147b306d-d5e3-413c-a7d2-8b2a1d6a290b
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: b1d06fe7-7784-40fb-9990-b3fe4528ad4c
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: dc086bd9-83ed-4a47-835e-3d4da871e5f7
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 261c7680-e558-4d6f-91ea-939b0cd06f5c
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 6174fc8a-81c9-461f-9cc8-eee8f18d2c08
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 0d053fd9-4f8d-4913-84d2-f3e1fe19760b
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: aa4dec24-070a-4296-a738-299aac8b54fe
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column ReportedDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: c310f050-1933-4b7d-bb49-6a0cfd2ab442
		summarizeBy: none
		sourceColumn: ReportedDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RestoredDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: afe58e38-1360-4604-b4d0-9640e827beec
		summarizeBy: none
		sourceColumn: RestoredDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 4f21b7f2-026c-46c9-9034-4d1d43f7b410
		summarizeBy: none
		sourceColumn: DowntimeMinutes

		annotation SummarizationSetBy = Automatic

	column ResponseMinutes
		dataType: int64
		formatString: #,0
		lineageTag: b17c3e98-5d5b-49ec-8ecf-52039c255f2a
		summarizeBy: none
		sourceColumn: ResponseMinutes

		annotation SummarizationSetBy = Automatic

	column FailureMode
		dataType: string
		lineageTag: d9d97fcb-52d9-4afc-97ae-22ab47d40a5c
		summarizeBy: none
		sourceColumn: FailureMode

		annotation SummarizationSetBy = Automatic

	column FailureCategory
		dataType: string
		lineageTag: eb28db1e-cde4-43d1-942e-6783c423aa7b
		summarizeBy: none
		sourceColumn: FailureCategory

		annotation SummarizationSetBy = Automatic

	column RootCause
		dataType: string
		lineageTag: 0eeb9cea-4b66-4677-83f2-872904d360d3
		summarizeBy: none
		sourceColumn: RootCause

		annotation SummarizationSetBy = Automatic

	column ActionTaken
		dataType: string
		lineageTag: 6bebc426-4110-42c1-8cca-ef8fdd491070
		summarizeBy: none
		sourceColumn: ActionTaken

		annotation SummarizationSetBy = Automatic

	column ReportedBy
		dataType: string
		lineageTag: edbdd690-58a4-438d-a7c1-9ce26e19d12c
		summarizeBy: none
		sourceColumn: ReportedBy

		annotation SummarizationSetBy = Automatic

	column AttendedTechID
		dataType: string
		lineageTag: 749a698d-40d5-4a9a-bbb6-358a20cba022
		summarizeBy: none
		sourceColumn: AttendedTechID

		annotation SummarizationSetBy = Automatic

	column AttendedTechName
		dataType: string
		lineageTag: 5040550d-08ab-423b-ad99-51cb0c909fcc
		summarizeBy: none
		sourceColumn: AttendedTechName

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 9d2931b2-9e41-4fbe-81dc-3c9e7bfa9f01
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SpareUsed
		dataType: string
		lineageTag: 0d82b551-817e-48cc-9109-a62690568d02
		summarizeBy: none
		sourceColumn: SpareUsed

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: 9bf01a97-a072-4efd-a3eb-48d05a051675
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 397ad8dd-34a3-4e17-9cf4-1f4ccfb60a7b
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeHours
		dataType: double
		formatString: #,0.0
		lineageTag: ae7e94db-c041-4f78-b601-2d0e873e9756
		summarizeBy: none
		sourceColumn: DowntimeHours

		annotation SummarizationSetBy = Automatic

	partition Fact_Breakdowns = m
		mode: import
		source = ```
				let
				    Source = fnSource("Breakdown_Reports"),
				    Typed = Table.TransformColumnTypes(Source, {{"BreakdownID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineType", type text}, {"Criticality", type text}, {"ReportedDateTime", type datetime}, {"RestoredDateTime", type datetime}, {"DowntimeMinutes", Int64.Type}, {"ResponseMinutes", Int64.Type}, {"FailureMode", type text}, {"FailureCategory", type text}, {"RootCause", type text}, {"ActionTaken", type text}, {"ReportedBy", type text}, {"AttendedTechID", type text}, {"AttendedTechName", type text}, {"Status", type text}, {"SpareUsed", type text}, {"Severity", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ReportedDate", each Date.From([ReportedDateTime]), type date),
				    AddHrs = Table.AddColumn(AddDate, "DowntimeHours", each if [DowntimeMinutes] = null then null else [DowntimeMinutes] / 60, type number)
				in
				    AddHrs
				```

	annotation PBI_ResultType = Table
