/// Every QR scan. Proves attendance at the machine.
table Fact_ScanLog
	lineageTag: 625d191a-6fbd-4021-b0fd-d41a6eabfb82

	column ScanID
		dataType: string
		lineageTag: 0ab80163-75fe-4f0a-8397-d90d26cdfaa9
		summarizeBy: none
		sourceColumn: ScanID

		annotation SummarizationSetBy = Automatic

	column QRType
		dataType: string
		lineageTag: 7cbf1163-957f-409e-86d2-01bdf2038535
		summarizeBy: none
		sourceColumn: QRType

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 446e56bf-aa60-4229-8cd8-9f694b636bdb
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 0de645b6-e80d-4dcb-b7c3-15a56f5d3c7f
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 0ff0fa48-186c-4bcf-9dce-5c1aa95c47f3
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column TechName
		dataType: string
		lineageTag: a3e84017-daa8-4d5f-9e4f-3f0a9e4770d3
		summarizeBy: none
		sourceColumn: TechName

		annotation SummarizationSetBy = Automatic

	column ScanDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 201c3a8d-8d9f-45a8-843f-0d5191e77b4b
		summarizeBy: none
		sourceColumn: ScanDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LinkedWOID
		dataType: string
		lineageTag: 0e80e9e3-6ff7-4ed1-a887-141a1182d5af
		summarizeBy: none
		sourceColumn: LinkedWOID

		annotation SummarizationSetBy = Automatic

	column Action
		dataType: string
		lineageTag: 37e70bfc-9c91-47f9-9271-e3c2587acd7b
		summarizeBy: none
		sourceColumn: Action

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: f09f62db-9ba3-4abe-8947-8aed2a5b8bcc
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column ScanDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 8a0f9c7e-7d33-4f0c-9ba4-5f15d198208d
		summarizeBy: none
		sourceColumn: ScanDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_ScanLog = m
		mode: import
		source = ```
				let
				    Source = fnSource("QR_Scan_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"ScanID", type text}, {"QRType", type text}, {"MachineID", type text}, {"MachineName", type text}, {"TechID", type text}, {"TechName", type text}, {"ScanDateTime", type datetime}, {"LinkedWOID", type text}, {"Action", type text}, {"CellID", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ScanDate", each Date.From([ScanDateTime]), type date)
				in
				    AddDate
				```

	annotation PBI_ResultType = Table
