/// Abnormalities - the early warning layer before a breakdown.
table Fact_Abnormalities
	lineageTag: 78ef02fa-7cb3-43ed-ae6b-ec132e21d68d

	column AbnormalityID
		dataType: string
		lineageTag: bba275e7-4ea6-4b0b-ba25-9f91a4d07788
		summarizeBy: none
		sourceColumn: AbnormalityID

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: fdea1bcd-f4f3-44c8-adb1-c2c3c61af492
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column SourceRefID
		dataType: string
		lineageTag: 25095356-642b-491a-92a1-85195bf871a8
		summarizeBy: none
		sourceColumn: SourceRefID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 34d771bf-43af-4c7a-ac68-7a0021e10055
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 0c942574-3851-4ef6-819f-d41c164d2651
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 34f916d0-fa0b-4e0e-8230-61b92fa531ac
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: ecc4d92d-8427-4ca3-9ce9-8d5b52793e42
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: bbe045b4-2cec-43f6-80e7-25220d3bfb93
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 20fddb86-4d53-49f7-9326-d7adcbd39940
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: 53b59b3f-7fbe-485e-b6a1-9038d1b25c88
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 1c051a70-ec31-4eda-b04c-af5c00eefce4
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column ReportedByTechID
		dataType: string
		lineageTag: 8667363f-5520-4754-9eea-cb1742098558
		summarizeBy: none
		sourceColumn: ReportedByTechID

		annotation SummarizationSetBy = Automatic

	column ReportedByName
		dataType: string
		lineageTag: 6a62e60b-afc7-4243-8724-237ceb6aa904
		summarizeBy: none
		sourceColumn: ReportedByName

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e9803950-a9a9-4537-bf18-d66823a278be
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: ed31237b-1419-41bc-b18d-375858e817bf
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ClosedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: fa5efbaa-65ef-4dc5-9481-4fafd099e6e6
		summarizeBy: none
		sourceColumn: ClosedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CorrectiveAction
		dataType: string
		lineageTag: 39590aae-91be-47ab-8bed-69236ffdde62
		summarizeBy: none
		sourceColumn: CorrectiveAction

		annotation SummarizationSetBy = Automatic

	column OwnerFunction
		dataType: string
		lineageTag: dc5e96ff-a81b-4847-849e-687f9b8889f9
		summarizeBy: none
		sourceColumn: OwnerFunction

		annotation SummarizationSetBy = Automatic

	column EscalationRequired
		dataType: string
		lineageTag: 46643394-284a-4633-8321-3a6bee261971
		summarizeBy: none
		sourceColumn: EscalationRequired

		annotation SummarizationSetBy = Automatic

	column PhotoURL
		dataType: string
		lineageTag: e0eadd58-71e5-4c68-a71a-adfb88283234
		summarizeBy: none
		sourceColumn: PhotoURL

		annotation SummarizationSetBy = Automatic

	partition Fact_Abnormalities = m
		mode: import
		source = ```
				let
				    Source = fnSource("Abnormality_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"AbnormalityID", type text}, {"Source", type text}, {"SourceRefID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Category", type text}, {"Severity", type text}, {"Description", type text}, {"ReportedByTechID", type text}, {"ReportedByName", type text}, {"ReportedDate", type date}, {"Status", type text}, {"ClosedDate", type date}, {"CorrectiveAction", type text}, {"OwnerFunction", type text}, {"EscalationRequired", type text}, {"PhotoURL", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
