/// Spare part requests raised from the machine QR.
table Fact_SpareRequests
	lineageTag: 007d23e3-920c-4683-9d63-992df8d80c4a

	column RequestID
		dataType: string
		lineageTag: d7ad8d09-55d7-4ed0-b3ac-c680c924db6f
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: 1c65bed5-03de-4f02-b586-f1946d9465bf
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: 81c65814-4114-40d7-b6d5-dbfe249c73e4
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 15740b26-a546-41d0-9c6f-b348e5e3b400
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 73adcfab-133a-472d-be30-dfb566ba7470
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 9900173f-6886-4e58-aee2-d46bae2e3ef3
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: e857f5cf-8d32-4080-a3b0-8e759b2b3885
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 7d3836de-f227-4e3d-873e-50c357544413
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: b5de193e-0432-4b4b-a9ac-04c7186b12cc
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 32d95b4a-2cad-4c58-944d-ebdcc249846b
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyRequested
		dataType: int64
		formatString: #,0
		lineageTag: f76c9ae4-e746-4076-8e54-556a88822848
		summarizeBy: none
		sourceColumn: QtyRequested

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 9fac5dbf-9ee2-4a89-8e99-152e9815e43d
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: c820b568-22fd-4e07-b648-2dd78750c3b6
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column RequestedByTechID
		dataType: string
		lineageTag: 3551c50c-4777-4e12-9734-b48a02f16504
		summarizeBy: none
		sourceColumn: RequestedByTechID

		annotation SummarizationSetBy = Automatic

	column RequestedByName
		dataType: string
		lineageTag: 11dbbb4d-443b-45c7-a6fb-aa87fb2a925b
		summarizeBy: none
		sourceColumn: RequestedByName

		annotation SummarizationSetBy = Automatic

	column RequestDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 4354a020-f3ae-42f1-90c3-8e0d6d6f88af
		summarizeBy: none
		sourceColumn: RequestDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Urgency
		dataType: string
		lineageTag: 49d49bd5-c23a-4dbe-a7df-6ef2c667b58a
		summarizeBy: none
		sourceColumn: Urgency

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 55f58496-53f9-46d3-8381-d1dc83f12ecb
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ApprovedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 2eb24531-7fc4-4201-98f2-c8ba288ec8b7
		summarizeBy: none
		sourceColumn: ApprovedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ApprovedBy
		dataType: string
		lineageTag: a7806118-4a16-4f88-88c4-7096f9149c54
		summarizeBy: none
		sourceColumn: ApprovedBy

		annotation SummarizationSetBy = Automatic

	column IssuedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c2dfdd38-44aa-45f9-8e2d-b42564287a6f
		summarizeBy: none
		sourceColumn: IssuedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: 727e9f34-eee0-48aa-8217-89a8dc3e8787
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: 7bc5a7a3-0197-4598-a8a0-3845497b7297
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column RejectionReason
		dataType: string
		lineageTag: e27acd1f-910a-4ee1-88ed-b22a2845a767
		summarizeBy: none
		sourceColumn: RejectionReason

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareRequests = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Requests"),
				    Typed = Table.TransformColumnTypes(Source, {{"RequestID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyRequested", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"RequestedByTechID", type text}, {"RequestedByName", type text}, {"RequestDate", type date}, {"Urgency", type text}, {"Status", type text}, {"ApprovedDate", type date}, {"ApprovedBy", type text}, {"IssuedDate", type date}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"RejectionReason", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
