/// Abnormalities - the early warning layer before a breakdown.
table Fact_Abnormalities
	lineageTag: 33af1dab-3e70-4ed6-aba7-f070f007e220

	column AbnormalityID
		dataType: string
		lineageTag: 00adb8a2-a0e5-4315-9010-9232fbb70bdb
		summarizeBy: none
		sourceColumn: AbnormalityID

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 7a8a98ea-c56d-466d-8ccd-8b0f25f0d590
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column SourceRefID
		dataType: string
		lineageTag: 50832e6f-8384-44cd-b4ba-6543d712b0e8
		summarizeBy: none
		sourceColumn: SourceRefID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: a284eb1b-ad5a-41b5-8991-4e0fbefe4fd0
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 260f2478-c417-4f9a-bce9-e02ac4df4009
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 968f29d9-9728-4c1f-9194-ebb254114dc7
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: be3922f8-4bf2-49ed-a250-3236f5a57d1c
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 36f29385-b093-4e35-b9ea-ea0b7dd2b4b9
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 2ca3e2f0-bee4-49a6-88af-ea092018ed43
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: 25563974-91b1-4c06-888e-02ff8f4019e6
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 74ff46e9-09cb-41a6-9ad2-d5337e262d54
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column ReportedByTechID
		dataType: string
		lineageTag: 75d7e362-4ce6-42fe-adda-57d42278c038
		summarizeBy: none
		sourceColumn: ReportedByTechID

		annotation SummarizationSetBy = Automatic

	column ReportedByName
		dataType: string
		lineageTag: 02715ac3-c811-4317-b59d-b55c50885003
		summarizeBy: none
		sourceColumn: ReportedByName

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7de21ec9-1669-4532-9480-5347179e6ac5
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 03536586-718b-4907-bd40-a269dbc65152
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ClosedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 8c9910e3-54ec-4aed-b6ea-cdd6eecf4e39
		summarizeBy: none
		sourceColumn: ClosedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CorrectiveAction
		dataType: string
		lineageTag: 2b04ca84-5c7c-4f94-ad45-7246bf8e8ada
		summarizeBy: none
		sourceColumn: CorrectiveAction

		annotation SummarizationSetBy = Automatic

	column OwnerFunction
		dataType: string
		lineageTag: b6d35c8f-a491-46b0-b4c9-cf6ea56cb913
		summarizeBy: none
		sourceColumn: OwnerFunction

		annotation SummarizationSetBy = Automatic

	column EscalationRequired
		dataType: string
		lineageTag: 6bced96d-1ef8-4a87-a49c-e9c2db3953f7
		summarizeBy: none
		sourceColumn: EscalationRequired

		annotation SummarizationSetBy = Automatic

	column PhotoURL
		dataType: string
		lineageTag: ef93ddc5-202a-47ce-8ba2-66a389a4b4e0
		summarizeBy: none
		sourceColumn: PhotoURL

		annotation SummarizationSetBy = Automatic

	partition Fact_Abnormalities = m
		mode: import
		source = ```
				let
				    Source = fnSource("Abnormality_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"AbnormalityID", type text}, {"Source", type text}, {"SourceRefID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Category", type text}, {"Severity", type text}, {"Description", type text}, {"ReportedByTechID", type text}, {"ReportedByName", type text}, {"ReportedDate", type date}, {"Status", type text}, {"ClosedDate", type date}, {"CorrectiveAction", type text}, {"OwnerFunction", type text}, {"EscalationRequired", type text}, {"PhotoURL", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
