/// What was actually fitted to the machine.
table Fact_SpareReplacements
	lineageTag: b1557d3e-3de8-4f74-8095-16c41c6376b4

	column ReplacementID
		dataType: string
		lineageTag: e9959347-1bb3-4835-b4f6-8351b4fb7df9
		summarizeBy: none
		sourceColumn: ReplacementID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: 9b55314d-4b16-4a93-91d9-e2362a715192
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: 04b43eb5-4f26-4207-8be5-9e050ffe9613
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column RequestID
		dataType: string
		lineageTag: 2ebf4fd3-04c5-4dbe-8cf8-5f2525b2ea13
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: eb75b3fb-8754-49c1-ae5a-420371dc6138
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: e9dcbbf3-3c20-43cb-912e-f0c9c500c877
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 71927a04-831d-4372-8b75-e35e2869eefe
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: f9bbf3dd-1ebd-4563-9f57-2c06f1dd62c3
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: 096c0887-663c-4d93-8542-e1bbc380124f
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 18eae89d-3171-4ed9-9e40-9491bb1f5d0c
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 406cbdd2-840c-4739-b03c-58c2773e8e9d
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 60e08f8a-ee97-404b-a44b-a97f9f0dcca1
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyReplaced
		dataType: int64
		formatString: #,0
		lineageTag: 0732f65f-8bb6-4d58-ba8b-8db83b80c051
		summarizeBy: none
		sourceColumn: QtyReplaced

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: d5ca87b0-7b6b-4fb0-94a1-ce8516325611
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: b6f36f04-bf0a-4c70-9bce-0fe8e4be298b
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column ReplacedByTechID
		dataType: string
		lineageTag: 572b8ff5-1e02-47ad-92d3-e4655a0280b9
		summarizeBy: none
		sourceColumn: ReplacedByTechID

		annotation SummarizationSetBy = Automatic

	column ReplacedByName
		dataType: string
		lineageTag: c966241d-2011-4104-b4b2-e7c832db5d76
		summarizeBy: none
		sourceColumn: ReplacedByName

		annotation SummarizationSetBy = Automatic

	column ReplacedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 1caa9d39-8714-4b05-8d7d-906670a5228f
		summarizeBy: none
		sourceColumn: ReplacedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OldPartCondition
		dataType: string
		lineageTag: 19b8577c-8be2-45ee-8fd7-ff148da2d3fe
		summarizeBy: none
		sourceColumn: OldPartCondition

		annotation SummarizationSetBy = Automatic

	column WarrantyClaim
		dataType: string
		lineageTag: 2f94dca7-0d96-4e40-b919-afe2b7294d25
		summarizeBy: none
		sourceColumn: WarrantyClaim

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: a1872aac-45ba-430a-8a86-874f318a6d37
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareReplacements = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Replacements"),
				    Typed = Table.TransformColumnTypes(Source, {{"ReplacementID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"RequestID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyReplaced", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"ReplacedByTechID", type text}, {"ReplacedByName", type text}, {"ReplacedDate", type date}, {"OldPartCondition", type text}, {"WarrantyClaim", type text}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
