/// One row per checklist task per work order - the audit evidence.
table Fact_ChecklistResults
	lineageTag: e8c063cb-fa75-4995-8e7c-db91d3a934af

	column ResultID
		dataType: string
		lineageTag: a7c4e79b-5497-43c5-9b25-54792472d333
		summarizeBy: none
		sourceColumn: ResultID

		annotation SummarizationSetBy = Automatic

	column WOID
		dataType: string
		lineageTag: 35e2454c-7bd6-4019-b295-e39acf17dc50
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: dd2d2910-49ad-47b8-b35e-52287e006e54
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: c1994e0b-5b2d-4d07-b837-c95ae135d371
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: 817102ad-13c1-4600-b8c1-d2e66ea5ccf0
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: 94deb29b-6f34-470a-bea6-bf92ba544a69
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 39307c3d-eb61-419e-b3b9-f9e6c918017b
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: fea364a8-5026-4ae3-86d3-55acde908e53
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: ee48d6eb-0eac-4621-a4a6-f21af00863e8
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: 1f4ba011-edcf-4811-95b0-11bf405c1460
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: 6eabb26d-069b-4327-83b1-97560ce6fe24
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: 427f86c9-e88f-4543-b9f5-f076557e8799
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column MeasuredValue
		dataType: double
		formatString: #,0.0
		lineageTag: 117a701c-3b40-4a7d-87e0-ccab5616a844
		summarizeBy: none
		sourceColumn: MeasuredValue

		annotation SummarizationSetBy = Automatic

	column Observation
		dataType: string
		lineageTag: 8743692a-f16c-4802-978a-c07f8c0b7c6d
		summarizeBy: none
		sourceColumn: Observation

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 9624af02-622a-4ad6-8099-ca39c28b5add
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column RecordedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e4e27f0b-c296-487e-adf6-f94267807293
		summarizeBy: none
		sourceColumn: RecordedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AbnormalityRaised
		dataType: string
		lineageTag: 521cc18d-d533-4515-abb2-148e685f478a
		summarizeBy: none
		sourceColumn: AbnormalityRaised

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 0df3866a-40e8-4c51-a43f-4cb99a769dbd
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Fact_ChecklistResults = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_ChecklistResults"),
				    Typed = Table.TransformColumnTypes(Source, {{"ResultID", type text}, {"WOID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"Result", type text}, {"MeasuredValue", type number}, {"Observation", type text}, {"TechID", type text}, {"RecordedDate", type date}, {"AbnormalityRaised", type text}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
