/// One row per checklist task per work order - the audit evidence.
table Fact_ChecklistResults
	lineageTag: 5f899922-7d47-4dba-864a-9e50255a47c4

	column ResultID
		dataType: string
		lineageTag: c5f6c2f8-f370-4e44-b988-45b839e7be23
		summarizeBy: none
		sourceColumn: ResultID

		annotation SummarizationSetBy = Automatic

	column WOID
		dataType: string
		lineageTag: a894ec0e-bfbf-4755-92fe-5382a9d55a49
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: b5572e7e-717c-4455-b836-4686ca4d2432
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 1b498ede-da83-483e-a9a9-125de191c398
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column ChecklistID
		dataType: string
		lineageTag: ccbfb593-124d-421a-931a-3194509ba263
		summarizeBy: none
		sourceColumn: ChecklistID

		annotation SummarizationSetBy = Automatic

	column TaskNo
		dataType: int64
		formatString: #,0
		lineageTag: 5a8eaf0b-706f-468a-a555-3029a0ad9fb5
		summarizeBy: none
		sourceColumn: TaskNo

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 66860d33-a8b0-4e5d-bcb5-43ccaa9052a6
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column TaskType
		dataType: string
		lineageTag: 154a677c-4821-4f3b-a063-5e967078977c
		summarizeBy: none
		sourceColumn: TaskType

		annotation SummarizationSetBy = Automatic

	column AcceptanceStandard
		dataType: string
		lineageTag: 3dfdb568-7f51-4403-970f-f6dd340636b9
		summarizeBy: none
		sourceColumn: AcceptanceStandard

		annotation SummarizationSetBy = Automatic

	column Mandatory
		dataType: string
		lineageTag: 4a2f6d8f-065b-46ad-8018-cd0e2893ca71
		summarizeBy: none
		sourceColumn: Mandatory

		annotation SummarizationSetBy = Automatic

	column SafetyCritical
		dataType: string
		lineageTag: fa277797-763b-4017-84e8-e2e4d5113a03
		summarizeBy: none
		sourceColumn: SafetyCritical

		annotation SummarizationSetBy = Automatic

	column Result
		dataType: string
		lineageTag: 096ed715-6c44-4e66-8d39-58a6e8aff9f8
		summarizeBy: none
		sourceColumn: Result

		annotation SummarizationSetBy = Automatic

	column MeasuredValue
		dataType: double
		formatString: #,0.0
		lineageTag: 82ab5624-7508-4bf7-a1ad-585940976559
		summarizeBy: none
		sourceColumn: MeasuredValue

		annotation SummarizationSetBy = Automatic

	column Observation
		dataType: string
		lineageTag: 4e1ea5a8-1fab-4855-aafe-96d173966b54
		summarizeBy: none
		sourceColumn: Observation

		annotation SummarizationSetBy = Automatic

	column TechID
		dataType: string
		lineageTag: 88e82415-20ce-4e9b-8025-1898f10c432d
		summarizeBy: none
		sourceColumn: TechID

		annotation SummarizationSetBy = Automatic

	column RecordedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d5c47f17-336c-4850-84c7-79321248d303
		summarizeBy: none
		sourceColumn: RecordedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AbnormalityRaised
		dataType: string
		lineageTag: 9402942f-4c7a-42bc-ac81-cac5a822f03b
		summarizeBy: none
		sourceColumn: AbnormalityRaised

		annotation SummarizationSetBy = Automatic

	column TaskKey
		dataType: string
		lineageTag: 81430640-cdf7-48aa-b9da-e807d8c77f39
		summarizeBy: none
		sourceColumn: TaskKey

		annotation SummarizationSetBy = Automatic

	partition Fact_ChecklistResults = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_ChecklistResults"),
				    Typed = Table.TransformColumnTypes(Source, {{"ResultID", type text}, {"WOID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"ChecklistID", type text}, {"TaskNo", Int64.Type}, {"TaskDescription", type text}, {"TaskType", type text}, {"AcceptanceStandard", type text}, {"Mandatory", type text}, {"SafetyCritical", type text}, {"Result", type text}, {"MeasuredValue", type number}, {"Observation", type text}, {"TechID", type text}, {"RecordedDate", type date}, {"AbnormalityRaised", type text}}, "en-US"),
				    AddKey = Table.AddColumn(Typed, "TaskKey", each [ChecklistID] & "|" & Text.From([TaskNo]), type text)
				in
				    AddKey
				```

	annotation PBI_ResultType = Table
