/// Monthly production standard hours per cell - the input that drives scheduling.
table Fact_StdHours
	lineageTag: 02cac537-a772-4e35-b872-4a0b5798553f

	column MonthKey
		dataType: string
		lineageTag: a846bcd0-a8d7-4f11-9f61-51ba1150d84b
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: d706c399-5f6b-495f-afbb-7d7bc131d87b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: 8321a40d-c22a-4de5-9a98-93558ef9c421
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 028ec47c-cbca-486e-b5db-377208628615
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: e5c0acea-857a-41a6-9cc9-84852a0f57bb
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 75ab0618-2478-44c7-8904-cf34b1a896c1
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column StdHours
		dataType: double
		formatString: #,0.0
		lineageTag: 87186228-6bd7-4751-b2ae-f63a486dd58a
		summarizeBy: none
		sourceColumn: StdHours

		annotation SummarizationSetBy = Automatic

	column UploadedBy
		dataType: string
		lineageTag: 91d65ebe-f0ab-4997-8ce5-43ec17d138f5
		summarizeBy: none
		sourceColumn: UploadedBy

		annotation SummarizationSetBy = Automatic

	column UploadDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 4ba85ba9-e68c-4120-8183-351ea04f7f7e
		summarizeBy: none
		sourceColumn: UploadDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SourceFile
		dataType: string
		lineageTag: 82a3fa72-169b-4c36-97b2-bf269620552b
		summarizeBy: none
		sourceColumn: SourceFile

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5d6aa2e5-5b85-494d-bae4-b430ae020af4
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_StdHours = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Standard_Hours"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"Year", Int64.Type}, {"MonthNo", Int64.Type}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"StdHours", type number}, {"UploadedBy", type text}, {"UploadDate", type date}, {"SourceFile", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date)
				in
				    AddMonthStart
				```

	annotation PBI_ResultType = Table
