/// Monthly production standard hours per cell - the input that drives scheduling.
table Fact_StdHours
	lineageTag: 2a767ea9-922d-4cf4-aa28-47f4dab82d52

	column MonthKey
		dataType: string
		lineageTag: 2376b14b-9d4f-465b-b186-485c0709285e
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: #,0
		lineageTag: 7e2e40bd-0c24-4e57-9ebb-d3afb0ad13ab
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNo
		dataType: int64
		formatString: #,0
		lineageTag: b4e0fd3f-13d5-4322-aca2-13ed78e5250a
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 60af49e3-7162-4ea5-bc4e-1e50abd3b8fe
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 8733d811-c0b2-41d5-8b0c-966531201b5c
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: bd905596-6d08-4432-8f08-6b9dfdac14d5
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column StdHours
		dataType: double
		formatString: #,0.0
		lineageTag: 3dc61991-a935-4b4c-afb7-a0f85d5d3133
		summarizeBy: none
		sourceColumn: StdHours

		annotation SummarizationSetBy = Automatic

	column UploadedBy
		dataType: string
		lineageTag: 0f0491de-33a8-4623-b0c0-2e54498a1024
		summarizeBy: none
		sourceColumn: UploadedBy

		annotation SummarizationSetBy = Automatic

	column UploadDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 8fd844c0-efb7-436f-9234-f8339652dc71
		summarizeBy: none
		sourceColumn: UploadDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SourceFile
		dataType: string
		lineageTag: 8bdc1096-10f4-4640-a513-8a61475050fd
		summarizeBy: none
		sourceColumn: SourceFile

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 147e6071-abce-4071-9bb7-11f96c3229f5
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Fact_StdHours = m
		mode: import
		source = ```
				let
				    Source = fnSource("Cell_Standard_Hours"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"Year", Int64.Type}, {"MonthNo", Int64.Type}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"StdHours", type number}, {"UploadedBy", type text}, {"UploadDate", type date}, {"SourceFile", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date)
				in
				    AddMonthStart
				```

	annotation PBI_ResultType = Table
