/// Cell hour counter month by month: opening, added, closing, trigger, carry-over.
table Fact_HourLedger
	lineageTag: 05906068-22c6-4314-8c48-e963c7d75af4

	column MonthKey
		dataType: string
		lineageTag: d1ad9a1d-82fc-4d56-b878-7288ad23ee02
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 412eff71-b4bf-4eef-b01c-416b46d8fade
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: edaa2282-617a-47f1-8ae6-44573465072e
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column OpeningStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 39331d3e-9acd-45e1-af94-1af0ace0dd8d
		summarizeBy: none
		sourceColumn: OpeningStdHrs

		annotation SummarizationSetBy = Automatic

	column StdHoursAdded
		dataType: double
		formatString: #,0.0
		lineageTag: 428924f7-c084-47f3-a9d3-5f6791525a5d
		summarizeBy: none
		sourceColumn: StdHoursAdded

		annotation SummarizationSetBy = Automatic

	column ClosingStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 3019ef95-8c21-4ab5-9c61-1ddde77c88a1
		summarizeBy: none
		sourceColumn: ClosingStdHrs

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: 396e12c6-61b0-4fab-a4c9-69bba82a87a5
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column PMTriggered
		dataType: string
		lineageTag: 447357f4-7b92-4daa-b29b-3738a9cbeaec
		summarizeBy: none
		sourceColumn: PMTriggered

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: be4e4d01-3b83-4c9e-967a-301136d2cb63
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column CarryOverAfterPM
		dataType: double
		formatString: #,0.0
		lineageTag: 352ce5f2-adae-4836-b817-57b078aebc28
		summarizeBy: none
		sourceColumn: CarryOverAfterPM

		annotation SummarizationSetBy = Automatic

	column MonthsSinceLastPM
		dataType: int64
		formatString: #,0
		lineageTag: d8b12b92-e674-4cf3-a7c9-6570ff95114b
		summarizeBy: none
		sourceColumn: MonthsSinceLastPM

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: 1604b68a-64a2-4bc7-9b38-a1737382287b
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7ba7143d-79c5-4bc1-9064-ec9327ff8bce
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PctOfThreshold
		dataType: double
		formatString: #,0.0
		lineageTag: f3256b0e-7bbb-4ed8-ade6-58acd6429f0a
		summarizeBy: none
		sourceColumn: PctOfThreshold

		annotation SummarizationSetBy = Automatic

	partition Fact_HourLedger = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Hour_Ledger"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"CellID", type text}, {"CellName", type text}, {"OpeningStdHrs", type number}, {"StdHoursAdded", type number}, {"ClosingStdHrs", type number}, {"PMIntervalStdHrs", Int64.Type}, {"PMTriggered", type text}, {"TriggerType", type text}, {"CarryOverAfterPM", type number}, {"MonthsSinceLastPM", Int64.Type}, {"Scenario", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date),
				    AddPct = Table.AddColumn(AddMonthStart, "PctOfThreshold", each if [PMIntervalStdHrs] = null or [PMIntervalStdHrs] = 0 then null else [ClosingStdHrs] / [PMIntervalStdHrs], type number)
				in
				    AddPct
				```

	annotation PBI_ResultType = Table
