/// Unplanned stoppages. Feeds MTBF, MTTR and availability.
table Fact_Breakdowns
	lineageTag: 0865899a-0b36-4e38-b9f9-e056a545f0b3

	column BreakdownID
		dataType: string
		lineageTag: 37ab3784-108d-4123-8dd5-d6d433af4cfa
		summarizeBy: none
		sourceColumn: BreakdownID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 5fc61788-b0d2-46e2-a13c-a0cee9c0bd21
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: baeee5ef-19c1-4fd7-b893-5d2faa082e10
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 5763f7a9-eecf-4d4b-ae34-bf09c80d693c
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: fe92d484-b650-45b5-a57c-1d5057569a4e
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: c26f2dd1-007f-44d4-8e7f-a1a90a461595
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 3b22ac56-26ca-4f16-aae5-6a542c4625cf
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 01e77581-3d2f-4691-b230-3efba1cc9bac
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column ReportedDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: a370b520-080e-4f29-8f03-a9aa6acae380
		summarizeBy: none
		sourceColumn: ReportedDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RestoredDateTime
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn
		lineageTag: 003d4503-4fb8-41fd-8cea-74a2f4211306
		summarizeBy: none
		sourceColumn: RestoredDateTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 248bbb9b-1c73-43b2-86ef-6eed6d46c6cd
		summarizeBy: none
		sourceColumn: DowntimeMinutes

		annotation SummarizationSetBy = Automatic

	column ResponseMinutes
		dataType: int64
		formatString: #,0
		lineageTag: 8941f8e5-5836-4cc5-9ad8-9f97d95791ac
		summarizeBy: none
		sourceColumn: ResponseMinutes

		annotation SummarizationSetBy = Automatic

	column FailureMode
		dataType: string
		lineageTag: 3ccb9e77-0263-41f2-8e9d-b30af9c07461
		summarizeBy: none
		sourceColumn: FailureMode

		annotation SummarizationSetBy = Automatic

	column FailureCategory
		dataType: string
		lineageTag: 182b32fe-4250-4da3-b3b6-46cdb71205f3
		summarizeBy: none
		sourceColumn: FailureCategory

		annotation SummarizationSetBy = Automatic

	column RootCause
		dataType: string
		lineageTag: de32da0e-42ee-4b80-a2ce-03137bda6c69
		summarizeBy: none
		sourceColumn: RootCause

		annotation SummarizationSetBy = Automatic

	column ActionTaken
		dataType: string
		lineageTag: b10567e1-6f54-4070-a58b-0faf2ee81241
		summarizeBy: none
		sourceColumn: ActionTaken

		annotation SummarizationSetBy = Automatic

	column ReportedBy
		dataType: string
		lineageTag: 2042c4af-a7c1-4979-94d2-69f40fc5e450
		summarizeBy: none
		sourceColumn: ReportedBy

		annotation SummarizationSetBy = Automatic

	column AttendedTechID
		dataType: string
		lineageTag: 89fbadf9-1e80-40c2-9af3-890ab036388d
		summarizeBy: none
		sourceColumn: AttendedTechID

		annotation SummarizationSetBy = Automatic

	column AttendedTechName
		dataType: string
		lineageTag: 280ec81a-db85-4338-9b93-c201aa9ca549
		summarizeBy: none
		sourceColumn: AttendedTechName

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 0f5a5c59-6910-4d7b-8e40-4d80869b2db0
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column SpareUsed
		dataType: string
		lineageTag: 8683e00d-5d18-47eb-98a6-fc974a0133bf
		summarizeBy: none
		sourceColumn: SpareUsed

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: d6049840-1e5f-43f0-bc1d-6703bf75695a
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: b79e5d89-0c1e-449f-824f-9cfd00edf689
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DowntimeHours
		dataType: double
		formatString: #,0.0
		lineageTag: 210de564-9e05-44ac-a973-ffd35df49846
		summarizeBy: none
		sourceColumn: DowntimeHours

		annotation SummarizationSetBy = Automatic

	partition Fact_Breakdowns = m
		mode: import
		source = ```
				let
				    Source = fnSource("Breakdown_Reports"),
				    Typed = Table.TransformColumnTypes(Source, {{"BreakdownID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineType", type text}, {"Criticality", type text}, {"ReportedDateTime", type datetime}, {"RestoredDateTime", type datetime}, {"DowntimeMinutes", Int64.Type}, {"ResponseMinutes", Int64.Type}, {"FailureMode", type text}, {"FailureCategory", type text}, {"RootCause", type text}, {"ActionTaken", type text}, {"ReportedBy", type text}, {"AttendedTechID", type text}, {"AttendedTechName", type text}, {"Status", type text}, {"SpareUsed", type text}, {"Severity", type text}}, "en-US"),
				    AddDate = Table.AddColumn(Typed, "ReportedDate", each Date.From([ReportedDateTime]), type date),
				    AddHrs = Table.AddColumn(AddDate, "DowntimeHours", each if [DowntimeMinutes] = null then null else [DowntimeMinutes] / 60, type number)
				in
				    AddHrs
				```

	annotation PBI_ResultType = Table
