/// Spare part requests raised from the machine QR.
table Fact_SpareRequests
	lineageTag: 4de4b94e-80ac-4070-bbea-7c6ebf959e92

	column RequestID
		dataType: string
		lineageTag: 3bf584f5-1499-4297-8edf-7565f62f5233
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: 2348c571-13b8-4072-aa14-a77542e029bb
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: 9270a2a8-3b0f-454e-b284-8b5b9c02ff1b
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 1f444c89-db11-4a7f-ae7b-2c342cd8d9da
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 22057d88-7855-4506-b5e4-d668d3a0d65f
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 7190ebac-f0b8-45b5-97ab-341272953af6
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: d70fa940-eb5b-4067-b257-79d8e8934cec
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 9d436d0b-e851-4423-9f0e-7eaa6cd99e46
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 84960a7c-1ff5-4086-a8d6-a69c717c0820
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: 53bc5e30-ae35-47f0-84fd-30e9f8bdd2b2
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyRequested
		dataType: int64
		formatString: #,0
		lineageTag: 00653885-6546-468b-adaf-64be0e87bdee
		summarizeBy: none
		sourceColumn: QtyRequested

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: a14e5e18-5a3b-4ebb-b8fb-29d8c82bb267
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: f14451c3-e802-430c-9cb9-3a4c0ab3bf09
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column RequestedByTechID
		dataType: string
		lineageTag: a8c47d8f-62ab-407c-8016-5859309d3c85
		summarizeBy: none
		sourceColumn: RequestedByTechID

		annotation SummarizationSetBy = Automatic

	column RequestedByName
		dataType: string
		lineageTag: 85688685-2633-486f-b880-d74e9ea20bbd
		summarizeBy: none
		sourceColumn: RequestedByName

		annotation SummarizationSetBy = Automatic

	column RequestDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5c7d1b2d-e838-4de8-80a9-506610f24887
		summarizeBy: none
		sourceColumn: RequestDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Urgency
		dataType: string
		lineageTag: ee54dac6-b89f-4a23-ac26-b30c5d63ed0a
		summarizeBy: none
		sourceColumn: Urgency

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 88fc8dde-5226-4046-a5ce-b5077bfe8f4e
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ApprovedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: a7ca176e-8965-4620-b806-baf1c8ba40a4
		summarizeBy: none
		sourceColumn: ApprovedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ApprovedBy
		dataType: string
		lineageTag: 3224f8f0-f15a-4816-b35e-2476df3bc4e0
		summarizeBy: none
		sourceColumn: ApprovedBy

		annotation SummarizationSetBy = Automatic

	column IssuedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: c1185678-6633-47b0-97cb-f830e6f21adc
		summarizeBy: none
		sourceColumn: IssuedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column LeadTimeDays
		dataType: int64
		formatString: #,0
		lineageTag: 88d27705-970b-4eb8-aba7-0cddafb85d22
		summarizeBy: none
		sourceColumn: LeadTimeDays

		annotation SummarizationSetBy = Automatic

	column StoreBin
		dataType: string
		lineageTag: 77d05b4d-9b2a-4330-8e80-10382a293d43
		summarizeBy: none
		sourceColumn: StoreBin

		annotation SummarizationSetBy = Automatic

	column RejectionReason
		dataType: string
		lineageTag: 2c3ff3dd-3242-4226-8ad4-429e074ee3a1
		summarizeBy: none
		sourceColumn: RejectionReason

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareRequests = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Requests"),
				    Typed = Table.TransformColumnTypes(Source, {{"RequestID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyRequested", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"RequestedByTechID", type text}, {"RequestedByName", type text}, {"RequestDate", type date}, {"Urgency", type text}, {"Status", type text}, {"ApprovedDate", type date}, {"ApprovedBy", type text}, {"IssuedDate", type date}, {"LeadTimeDays", Int64.Type}, {"StoreBin", type text}, {"RejectionReason", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
