/// Abnormalities - the early warning layer before a breakdown.
table Fact_Abnormalities
	lineageTag: 4ae29757-b783-4063-9a14-a10ee896f7f9

	column AbnormalityID
		dataType: string
		lineageTag: 992e1251-8578-4c51-bafc-09ea689598cf
		summarizeBy: none
		sourceColumn: AbnormalityID

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: a4d25c41-b69c-4da4-bbb3-f45e8d44d842
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	column SourceRefID
		dataType: string
		lineageTag: aefa82ca-15d4-4e71-bce2-9069990f9b8c
		summarizeBy: none
		sourceColumn: SourceRefID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 6137cab8-8052-44dd-9ef8-aed1d490f0c5
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: 17441871-e3dc-4c87-abe3-c9151d73c1d0
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 042f9843-c485-4e86-a7f6-4f8208ccaf70
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 9215526e-9a30-49b1-a0d4-11f7facb5eda
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: 8be0d144-ec6f-4fea-8534-814e2dc94a82
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 277c0773-a299-4daf-82a2-16ccff832446
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Severity
		dataType: string
		lineageTag: 88a5b903-4de7-4513-864d-14a42a64dc54
		summarizeBy: none
		sourceColumn: Severity

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 46488238-76e5-4b24-958c-a720cc046963
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column ReportedByTechID
		dataType: string
		lineageTag: f59c2f17-507b-45a6-a35f-2df4f462a051
		summarizeBy: none
		sourceColumn: ReportedByTechID

		annotation SummarizationSetBy = Automatic

	column ReportedByName
		dataType: string
		lineageTag: 2ac25695-bc17-4d45-8696-984fe01f30f3
		summarizeBy: none
		sourceColumn: ReportedByName

		annotation SummarizationSetBy = Automatic

	column ReportedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: abbb3c7b-56bb-4a2e-807c-f1b2fcd0dc94
		summarizeBy: none
		sourceColumn: ReportedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: e9775a7c-b8f5-47c2-844a-8ef4477547c1
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ClosedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 98e4452f-43e0-41ad-9470-d69f3edd85e0
		summarizeBy: none
		sourceColumn: ClosedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CorrectiveAction
		dataType: string
		lineageTag: a52996dc-9977-4ef7-98a7-2b67957c0225
		summarizeBy: none
		sourceColumn: CorrectiveAction

		annotation SummarizationSetBy = Automatic

	column OwnerFunction
		dataType: string
		lineageTag: e4111824-0684-4ac6-a9cc-811eeb68e591
		summarizeBy: none
		sourceColumn: OwnerFunction

		annotation SummarizationSetBy = Automatic

	column EscalationRequired
		dataType: string
		lineageTag: 3642f2e1-cc8f-4ecd-887a-61b406c0f178
		summarizeBy: none
		sourceColumn: EscalationRequired

		annotation SummarizationSetBy = Automatic

	column PhotoURL
		dataType: string
		lineageTag: 478536db-d8b8-4f0c-8def-947445958a92
		summarizeBy: none
		sourceColumn: PhotoURL

		annotation SummarizationSetBy = Automatic

	partition Fact_Abnormalities = m
		mode: import
		source = ```
				let
				    Source = fnSource("Abnormality_Log"),
				    Typed = Table.TransformColumnTypes(Source, {{"AbnormalityID", type text}, {"Source", type text}, {"SourceRefID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"Category", type text}, {"Severity", type text}, {"Description", type text}, {"ReportedByTechID", type text}, {"ReportedByName", type text}, {"ReportedDate", type date}, {"Status", type text}, {"ClosedDate", type date}, {"CorrectiveAction", type text}, {"OwnerFunction", type text}, {"EscalationRequired", type text}, {"PhotoURL", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
