/// What was actually fitted to the machine.
table Fact_SpareReplacements
	lineageTag: fc7d65de-1970-4b68-8b55-583670f32279

	column ReplacementID
		dataType: string
		lineageTag: 3eb19735-21dc-4d90-84b8-2e1122c58e31
		summarizeBy: none
		sourceColumn: ReplacementID

		annotation SummarizationSetBy = Automatic

	column SourceType
		dataType: string
		lineageTag: 562e1553-905e-4b5e-ab18-40f1e85c81c9
		summarizeBy: none
		sourceColumn: SourceType

		annotation SummarizationSetBy = Automatic

	column SourceID
		dataType: string
		lineageTag: 30629567-e3aa-4746-9351-d6d75d4c4112
		summarizeBy: none
		sourceColumn: SourceID

		annotation SummarizationSetBy = Automatic

	column RequestID
		dataType: string
		lineageTag: fb732647-b2c7-414d-9751-55de57c482d0
		summarizeBy: none
		sourceColumn: RequestID

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: 13543469-d1b7-42c9-b747-98390bd54a34
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: d65911e4-51b8-402f-824c-f0c7a07c7e27
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 9306cf37-5585-4d04-8d9e-7913b6f9de00
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: ee41e063-7c07-43fc-a191-678f841af0eb
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column PartNo
		dataType: string
		lineageTag: 1ee8db48-e967-4abc-94fa-87738565870f
		summarizeBy: none
		sourceColumn: PartNo

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: b1137ffb-fd99-4bcd-933f-36a923bba328
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 004c1e91-a3f7-4475-b057-bea36f1c4fa9
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column UOM
		dataType: string
		lineageTag: e69b3f86-b43e-49f3-b1ba-fc32bb1bb42c
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = Automatic

	column QtyReplaced
		dataType: int64
		formatString: #,0
		lineageTag: 26d375c4-84a5-4524-8340-d7d1d723cf44
		summarizeBy: none
		sourceColumn: QtyReplaced

		annotation SummarizationSetBy = Automatic

	column UnitCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 22f2cedb-0ac8-4931-a42c-293c9242604f
		summarizeBy: none
		sourceColumn: UnitCostINR

		annotation SummarizationSetBy = Automatic

	column TotalCostINR
		dataType: double
		formatString: "₹"#,0.00;("₹"#,0.00);"₹"#,0.00
		lineageTag: 1f6743af-e66f-46ce-9247-3925a0cfd159
		summarizeBy: none
		sourceColumn: TotalCostINR

		annotation SummarizationSetBy = Automatic

	column ReplacedByTechID
		dataType: string
		lineageTag: 19e84832-70ff-43ef-ab05-0ff502e1d964
		summarizeBy: none
		sourceColumn: ReplacedByTechID

		annotation SummarizationSetBy = Automatic

	column ReplacedByName
		dataType: string
		lineageTag: 1dfa96be-b703-4860-98f2-7abc5c621047
		summarizeBy: none
		sourceColumn: ReplacedByName

		annotation SummarizationSetBy = Automatic

	column ReplacedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 4be39661-f625-4ee6-a005-4b33c16db352
		summarizeBy: none
		sourceColumn: ReplacedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OldPartCondition
		dataType: string
		lineageTag: 4c5fa626-c48b-4a6d-b469-2768f6554b42
		summarizeBy: none
		sourceColumn: OldPartCondition

		annotation SummarizationSetBy = Automatic

	column WarrantyClaim
		dataType: string
		lineageTag: f200c471-2441-4426-8ae0-21e503373f7d
		summarizeBy: none
		sourceColumn: WarrantyClaim

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 48e63e45-0328-4b41-89b5-17c4ed0256af
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_SpareReplacements = m
		mode: import
		source = ```
				let
				    Source = fnSource("SparePart_Replacements"),
				    Typed = Table.TransformColumnTypes(Source, {{"ReplacementID", type text}, {"SourceType", type text}, {"SourceID", type text}, {"RequestID", type text}, {"MachineID", type text}, {"MachineName", type text}, {"CellID", type text}, {"MachineType", type text}, {"PartNo", type text}, {"PartName", type text}, {"Category", type text}, {"UOM", type text}, {"QtyReplaced", Int64.Type}, {"UnitCostINR", type number}, {"TotalCostINR", type number}, {"ReplacedByTechID", type text}, {"ReplacedByName", type text}, {"ReplacedDate", type date}, {"OldPartCondition", type text}, {"WarrantyClaim", type text}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
