/// Cell hour counter month by month: opening, added, closing, trigger, carry-over.
table Fact_HourLedger
	lineageTag: 49ff97d4-d398-419d-be4e-fcf5a1f17e61

	column MonthKey
		dataType: string
		lineageTag: cfb94170-4dad-4c0e-8a4b-9619658d4053
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 1dd29dad-55c3-40b2-b5a9-d47f786c5712
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 48bfed39-aebd-4f83-a726-d655c5bd418c
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column OpeningStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: cfcb8e79-42fc-4651-ba1e-fbf701ab88f5
		summarizeBy: none
		sourceColumn: OpeningStdHrs

		annotation SummarizationSetBy = Automatic

	column StdHoursAdded
		dataType: double
		formatString: #,0.0
		lineageTag: 5839e6e1-c8bf-485a-95dc-0be630bb43ea
		summarizeBy: none
		sourceColumn: StdHoursAdded

		annotation SummarizationSetBy = Automatic

	column ClosingStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: 021f9401-0f44-4fff-8107-6ec76c69ee15
		summarizeBy: none
		sourceColumn: ClosingStdHrs

		annotation SummarizationSetBy = Automatic

	column PMIntervalStdHrs
		dataType: int64
		formatString: #,0
		lineageTag: d6c0aa47-02c6-4635-9008-862944121491
		summarizeBy: none
		sourceColumn: PMIntervalStdHrs

		annotation SummarizationSetBy = Automatic

	column PMTriggered
		dataType: string
		lineageTag: 5d837cc2-b3e4-4f71-a1df-263a39cdf03b
		summarizeBy: none
		sourceColumn: PMTriggered

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: 217e4be3-6ac6-4875-9478-1319f09dc29d
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column CarryOverAfterPM
		dataType: double
		formatString: #,0.0
		lineageTag: 7309bca1-2425-4e11-9380-8d5f61cfa24a
		summarizeBy: none
		sourceColumn: CarryOverAfterPM

		annotation SummarizationSetBy = Automatic

	column MonthsSinceLastPM
		dataType: int64
		formatString: #,0
		lineageTag: e80b1207-c40c-458e-83c5-d0aaf03e8c4f
		summarizeBy: none
		sourceColumn: MonthsSinceLastPM

		annotation SummarizationSetBy = Automatic

	column Scenario
		dataType: string
		lineageTag: 8a78e55a-ed6f-4356-907f-e957e935f26f
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

	column MonthStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 841de090-109d-469e-bc42-ae111db8ae9d
		summarizeBy: none
		sourceColumn: MonthStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PctOfThreshold
		dataType: double
		formatString: #,0.0
		lineageTag: f5ed6639-b21c-4a35-a51d-4c100a31bb41
		summarizeBy: none
		sourceColumn: PctOfThreshold

		annotation SummarizationSetBy = Automatic

	partition Fact_HourLedger = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_Hour_Ledger"),
				    Typed = Table.TransformColumnTypes(Source, {{"MonthKey", type text}, {"CellID", type text}, {"CellName", type text}, {"OpeningStdHrs", type number}, {"StdHoursAdded", type number}, {"ClosingStdHrs", type number}, {"PMIntervalStdHrs", Int64.Type}, {"PMTriggered", type text}, {"TriggerType", type text}, {"CarryOverAfterPM", type number}, {"MonthsSinceLastPM", Int64.Type}, {"Scenario", type text}}, "en-US"),
				    AddMonthStart = Table.AddColumn(Typed, "MonthStartDate", each Date.FromText([MonthKey] & "-01"), type date),
				    AddPct = Table.AddColumn(AddMonthStart, "PctOfThreshold", each if [PMIntervalStdHrs] = null or [PMIntervalStdHrs] = 0 then null else [ClosingStdHrs] / [PMIntervalStdHrs], type number)
				in
				    AddPct
				```

	annotation PBI_ResultType = Table
