/// One row per machine per PM cycle. The core transactional table.
table Fact_WorkOrders
	lineageTag: 9d757a91-027b-45f2-a333-7bd817c86bea

	column WOID
		dataType: string
		lineageTag: d19db104-e3ae-4a57-8ccf-1268e21d76a7
		summarizeBy: none
		sourceColumn: WOID

		annotation SummarizationSetBy = Automatic

	column CycleID
		dataType: string
		lineageTag: 38f8b76e-4bec-4504-9ab3-afa4eb70f3a6
		summarizeBy: none
		sourceColumn: CycleID

		annotation SummarizationSetBy = Automatic

	column CellID
		dataType: string
		lineageTag: 03cf0e80-23e0-4452-882c-07d7866d3884
		summarizeBy: none
		sourceColumn: CellID

		annotation SummarizationSetBy = Automatic

	column CellName
		dataType: string
		lineageTag: 67274890-1af9-402c-b197-8f7f68a0f748
		summarizeBy: none
		sourceColumn: CellName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: f012f92b-1272-470f-ba7b-2c9be3f7ce56
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column MachineID
		dataType: string
		lineageTag: b4b23edf-bb8f-428a-abbb-4c7b8db6c38d
		summarizeBy: none
		sourceColumn: MachineID

		annotation SummarizationSetBy = Automatic

	column MachineName
		dataType: string
		lineageTag: a27607ca-c8f1-40b5-99fe-a0a4ddfc497a
		summarizeBy: none
		sourceColumn: MachineName

		annotation SummarizationSetBy = Automatic

	column MachineType
		dataType: string
		lineageTag: 017eebe5-3d6c-4a61-af7c-928bbf4c9e84
		summarizeBy: none
		sourceColumn: MachineType

		annotation SummarizationSetBy = Automatic

	column Criticality
		dataType: string
		lineageTag: 738621c8-01fa-4f2b-a04a-164a8335120e
		summarizeBy: none
		sourceColumn: Criticality

		annotation SummarizationSetBy = Automatic

	column PMType
		dataType: string
		lineageTag: 8d9d3360-96e6-4613-a6de-dfd8f0ad0b92
		summarizeBy: none
		sourceColumn: PMType

		annotation SummarizationSetBy = Automatic

	column TriggerType
		dataType: string
		lineageTag: 3e419904-ea0e-4df7-811e-209a78a58e8a
		summarizeBy: none
		sourceColumn: TriggerType

		annotation SummarizationSetBy = Automatic

	column TriggerStdHrs
		dataType: double
		formatString: #,0.0
		lineageTag: dcaaf30f-6cee-4029-9b86-34791d49ce0d
		summarizeBy: none
		sourceColumn: TriggerStdHrs

		annotation SummarizationSetBy = Automatic

	column PlanMonth
		dataType: string
		lineageTag: 4a94bd14-8e79-4912-bd7c-e962d83ffdf4
		summarizeBy: none
		sourceColumn: PlanMonth

		annotation SummarizationSetBy = Automatic

	column PlannedDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 27b946ac-dc5f-4133-b352-23a224c158dc
		summarizeBy: none
		sourceColumn: PlannedDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 17f03fe2-e40a-4fef-9b3a-c0dc27bc8c71
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column AssignedTechID
		dataType: string
		lineageTag: a2aedff6-ad89-458e-afc8-82d8be436bf5
		summarizeBy: none
		sourceColumn: AssignedTechID

		annotation SummarizationSetBy = Automatic

	column AssignedTechName
		dataType: string
		lineageTag: e872a05a-7a96-4475-a6c0-39337be939c9
		summarizeBy: none
		sourceColumn: AssignedTechName

		annotation SummarizationSetBy = Automatic

	column Shift
		dataType: string
		lineageTag: a1e86390-21c9-489c-8d54-857b56e280be
		summarizeBy: none
		sourceColumn: Shift

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 5b7085fa-a8e0-4761-ba95-891a71b8fa97
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column ActualStartDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 6b44a843-92c6-411b-b8ae-d6b95657007e
		summarizeBy: none
		sourceColumn: ActualStartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ActualEndDate
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 34e77cc5-52c4-49bb-90c3-2aea5a29e77f
		summarizeBy: none
		sourceColumn: ActualEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DurationMin
		dataType: int64
		formatString: #,0
		lineageTag: 1b6a1ffe-e1b4-417e-b875-f61dd06b7d76
		summarizeBy: none
		sourceColumn: DurationMin

		annotation SummarizationSetBy = Automatic

	column ChecklistTotalTasks
		dataType: int64
		formatString: #,0
		lineageTag: 173058d2-54c4-4635-bed3-2e000f8917fe
		summarizeBy: none
		sourceColumn: ChecklistTotalTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistDoneTasks
		dataType: int64
		formatString: #,0
		lineageTag: 757d4956-4264-4df0-a034-56a2955232e2
		summarizeBy: none
		sourceColumn: ChecklistDoneTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistFailTasks
		dataType: int64
		formatString: #,0
		lineageTag: 7c25dff3-bfb2-4c10-8dd4-f7a2ba169805
		summarizeBy: none
		sourceColumn: ChecklistFailTasks

		annotation SummarizationSetBy = Automatic

	column ChecklistCompletionPct
		dataType: double
		formatString: #,0.0
		lineageTag: 106a0421-3e9a-4af4-a7b5-0d8c5166dcc6
		summarizeBy: none
		sourceColumn: ChecklistCompletionPct

		annotation SummarizationSetBy = Automatic

	column MachineQRScanned
		dataType: string
		lineageTag: e56e0af9-c063-4e59-9753-41eef8b8c43f
		summarizeBy: none
		sourceColumn: MachineQRScanned

		annotation SummarizationSetBy = Automatic

	column PMResult
		dataType: string
		lineageTag: 313e68fb-a536-4139-acba-6f4b390d5e94
		summarizeBy: none
		sourceColumn: PMResult

		annotation SummarizationSetBy = Automatic

	column OnTimeFlag
		dataType: string
		lineageTag: c6d0883c-fd9b-4194-856a-60b8f3ad2d5b
		summarizeBy: none
		sourceColumn: OnTimeFlag

		annotation SummarizationSetBy = Automatic

	column StdMinutes
		dataType: int64
		formatString: #,0
		lineageTag: cf0c819f-8807-4efe-bc06-d79ec9dd51d3
		summarizeBy: none
		sourceColumn: StdMinutes

		annotation SummarizationSetBy = Automatic

	column Remarks
		dataType: string
		lineageTag: 2164a208-20b2-4fce-ac85-f753b709bce2
		summarizeBy: none
		sourceColumn: Remarks

		annotation SummarizationSetBy = Automatic

	partition Fact_WorkOrders = m
		mode: import
		source = ```
				let
				    Source = fnSource("PM_WorkOrders"),
				    Typed = Table.TransformColumnTypes(Source, {{"WOID", type text}, {"CycleID", type text}, {"CellID", type text}, {"CellName", type text}, {"Area", type text}, {"MachineID", type text}, {"MachineName", type text}, {"MachineType", type text}, {"Criticality", type text}, {"PMType", type text}, {"TriggerType", type text}, {"TriggerStdHrs", type number}, {"PlanMonth", type text}, {"PlannedDate", type date}, {"DueDate", type date}, {"AssignedTechID", type text}, {"AssignedTechName", type text}, {"Shift", type text}, {"Status", type text}, {"ActualStartDate", type date}, {"ActualEndDate", type date}, {"DurationMin", Int64.Type}, {"ChecklistTotalTasks", Int64.Type}, {"ChecklistDoneTasks", Int64.Type}, {"ChecklistFailTasks", Int64.Type}, {"ChecklistCompletionPct", type number}, {"MachineQRScanned", type text}, {"PMResult", type text}, {"OnTimeFlag", type text}, {"StdMinutes", Int64.Type}, {"Remarks", type text}}, "en-US")
				in
				    Typed
				```

	annotation PBI_ResultType = Table
