"""Markdown for the GitHub approval issue and the manual posting kit."""
from __future__ import annotations

from datetime import datetime

from .compliance import Report
from .config import config
from .metadata import _fmt_ts, description, tags, titles
from .script import Script, build_timeline
from .tts import clean_markup

COMMANDS = """### ✅ Approve or reject
Reply to this issue (or to the notification email) with one command:

| Command | What happens |
|---|---|
| `/approve` | publish both videos at the next free daily slot |
| `/approve now` | publish immediately |
| `/approve short` · `/approve long` | publish only one format |
| `/reject <reason>` | skip this topic; the next topic renders tomorrow |
| `/rerender` | render again after you edit the script file (link above) |
"""


def _slot_text(dt: datetime) -> str:
    return dt.strftime("%a %d %b %Y, %I:%M %p IST").replace(" 0", " ")


def issue_body(s: Script, infos: dict, rep: Report, assets_url: str, repo_url: str, slot: datetime) -> str:
    t = titles(s)
    lines = [f"<!-- video-id: {s.id} -->",
             f"## 🎬 #{int(s.id)} · {s['title_ta']}",
             f"**{s.get('title_en', '')}** · {s.cat['ta']} ({s.cat['en']})",
             "",
             "### 👀 Preview",
             "Tap a link to download and watch on your phone or computer."]
    if "short" in infos:
        lines.append(f"- 📱 **Short** ({_fmt_ts(infos['short']['duration'])}): [{s.id}-short.mp4]({assets_url}{s.id}-short.mp4)")
    if "long" in infos:
        lines.append(f"- 🖥️ **Long video** ({_fmt_ts(infos['long']['duration'])}): [{s.id}-long.mp4]({assets_url}{s.id}-long.mp4)")
        lines += ["", f"![thumbnail]({assets_url}{s.id}-thumb.png)"]
    lines += ["", f"📅 If approved, goes live at the next free slot: **{_slot_text(slot)}**",
              f"📝 Script: [{s.path.name}]({repo_url}/blob/HEAD/finance-channel/content/{s.path.name})"
              + (" · ⚠️ *written by Claude, please read it*" if "Generated by Claude" in s.path.read_text(encoding='utf-8')[:200] else ""),
              "", "### 🛡️ Compliance check"]
    lines.append("✅ No named stocks/funds/brokers · ✅ No buy/sell calls or targets · ✅ No return promises · "
                 "✅ Disclaimer spoken, on screen and in the description"
                 + (" · ✅ SEBI F&O risk statement" if s.category == "fno" else ""))
    if rep.warnings:
        lines += ["", "**Please double-check:**"] + [f"- ⚠️ {w}" for w in rep.warnings]
    lines += ["", "### 🏷️ Titles"]
    for f in infos:
        lines.append(f"- {f}: `{t[f]}`")
    for f in infos:
        tl = build_timeline(s, f)
        said = "\n".join(f"{i}. {clean_markup(seg.text)}" for i, seg in enumerate(tl.segments, 1))
        lines += ["", f"<details><summary>🗣️ What the voice says ({f})</summary>\n\n{said}\n\n</details>"]
    lines += ["", f"<details><summary>📄 Description (long)</summary>\n\n```\n{description(s, 'long', infos.get('long', {}))}\n```\n</details>",
              "", COMMANDS]
    return "\n".join(lines)


def manual_kit(s: Script, infos: dict, assets_url: str, slot: datetime | None) -> str:
    """Posting instructions for when automatic YouTube upload isn't enabled yet."""
    t = titles(s)
    when = _slot_text(slot) if slot else "now"
    out = [f"### 📤 Ready to post: #{int(s.id)} {s['title_ta']}",
           "Automatic upload is off (`publish.mode: manual` in config.yaml), so here is everything you need. "
           "In the YouTube app: **+ → Upload a video**, pick the file, paste the title and description, set "
           f"**Audience → No, it's not made for kids**, and **Visibility → Schedule → {when}**.", ""]
    for f in infos:
        out += [f"#### {'📱 Short' if f == 'short' else '🖥️ Long video'}",
                f"1. Download: [{s.id}-{f}.mp4]({assets_url}{s.id}-{f}.mp4)"
                + (f" · thumbnail: [{s.id}-thumb.png]({assets_url}{s.id}-thumb.png)" if f == "long" else ""),
                "2. Title:", f"```\n{t[f]}\n```",
                "3. Description:", f"```\n{description(s, f, infos[f])}\n```",
                "4. Tags:", f"```\n{', '.join(tags(s))}\n```", ""]
    out.append("Close this issue once both are posted.")
    return "\n".join(out)


def published_comment(s: Script, uploaded: dict, slot: datetime | None) -> str:
    when = f"scheduled for **{_slot_text(slot)}**" if slot else "**live now**"
    lines = [f"### 🚀 Uploaded to YouTube, {when}"]
    for f, vid in uploaded.items():
        url = f"https://youtu.be/{vid}"
        lines.append(f"- {'📱 Short' if f == 'short' else '🖥️ Long'}: {url} · [YouTube Studio](https://studio.youtube.com/video/{vid}/edit)")
    if not config()["publish"].get("audited", False):
        lines.append("\n> If YouTube Studio shows the video as **Private (locked)**, your Google Cloud project hasn't "
                     "passed YouTube's API audit yet. See docs/SETUP.md, step 5.")
    return "\n".join(lines)
