"""masters.py - the fictional plant. All master data lives here."""

from datetime import date
from pm_core import Cell, Machine, Technician

PLANT = "Unit-1 Coimbatore"

CELLS = [
    Cell("CELL-01", "CNC Turning Line A",  "Machine Shop",   PLANT, "A", 4000, 12, 1180, "CC-1010"),
    Cell("CELL-02", "CNC Turning Line B",  "Machine Shop",   PLANT, "A", 4000, 12,  980, "CC-1011"),
    Cell("CELL-03", "Gear Cutting Cell",   "Machine Shop",   PLANT, "A", 4000, 12,  760, "CC-1020"),
    Cell("CELL-04", "Heat Treatment",      "Heat Treat",     PLANT, "A", 4000, 12, 1400, "CC-1030"),
    Cell("CELL-05", "Assembly Line 1",     "Assembly",       PLANT, "B", 4000, 12,  890, "CC-1040"),
    Cell("CELL-06", "Paint & Finishing",   "Finishing",      PLANT, "B", 4000, 12,  420, "CC-1050"),
    Cell("CELL-07", "Robotic Welding Bay", "Fabrication",    PLANT, "A", 4000, 12,  640, "CC-1060"),
    Cell("CELL-08", "Press Shop",          "Fabrication",    PLANT, "B", 4000, 12,  330, "CC-1070"),
]

# machine_type -> (checklist_id, standard PM minutes)
MACHINE_TYPES = {
    "CNC Turning Center":   ("CL-CNC-TURN", 150),
    "CNC Machining Center": ("CL-CNC-MILL", 165),
    "Gear Hobbing Machine": ("CL-GEAR",     180),
    "Gear Shaving Machine": ("CL-GEAR",     150),
    "Sealed Quench Furnace":("CL-FURNACE",  240),
    "Tempering Furnace":    ("CL-FURNACE",  180),
    "Assembly Station":     ("CL-ASSY",      90),
    "Leak Test Rig":        ("CL-ASSY",     110),
    "Paint Booth":          ("CL-PAINT",    200),
    "Curing Oven":          ("CL-PAINT",    160),
    "Robotic Welding Cell": ("CL-WELD",     190),
    "Hydraulic Press":      ("CL-PRESS",    175),
    "Conveyor System":      ("CL-UTIL",      80),
    "Air Compressor":       ("CL-UTIL",     120),
    "Chiller Unit":         ("CL-UTIL",     130),
}

# (machine_name, cell, type, make, model, criticality)
_M = [
    ("CNC Lathe TL-01",        "CELL-01", "CNC Turning Center",   "Doosan",     "Puma 2600SY", "A"),
    ("CNC Lathe TL-02",        "CELL-01", "CNC Turning Center",   "Doosan",     "Puma 2600SY", "A"),
    ("CNC Lathe TL-03",        "CELL-01", "CNC Turning Center",   "Mazak",      "QTN 250MY",   "A"),
    ("Bar Feeder BF-01",       "CELL-01", "Conveyor System",      "LNS",        "Quick6",      "C"),
    ("Chip Conveyor CC-01",    "CELL-01", "Conveyor System",      "Hennig",     "HC-400",      "C"),
    ("CNC Lathe TL-04",        "CELL-02", "CNC Turning Center",   "Haas",       "ST-30",       "A"),
    ("CNC Lathe TL-05",        "CELL-02", "CNC Turning Center",   "Haas",       "ST-30",       "B"),
    ("VMC MC-01",              "CELL-02", "CNC Machining Center", "Makino",     "PS95",        "A"),
    ("VMC MC-02",              "CELL-02", "CNC Machining Center", "Makino",     "PS95",        "B"),
    ("Gear Hobber GH-01",      "CELL-03", "Gear Hobbing Machine", "Liebherr",   "LC180",       "A"),
    ("Gear Hobber GH-02",      "CELL-03", "Gear Hobbing Machine", "Mitsubishi", "GE15A",       "A"),
    ("Gear Shaver GS-01",      "CELL-03", "Gear Shaving Machine", "Gleason",    "Genesis 160", "B"),
    ("Deburring Unit DB-01",   "CELL-03", "Conveyor System",      "Rosler",     "R320",        "C"),
    ("Sealed Quench SQ-01",    "CELL-04", "Sealed Quench Furnace","Ipsen",      "T-6",         "A"),
    ("Sealed Quench SQ-02",    "CELL-04", "Sealed Quench Furnace","Ipsen",      "T-6",         "A"),
    ("Tempering Furnace TF-01","CELL-04", "Tempering Furnace",    "Aichelin",   "TF-900",      "A"),
    ("Quench Oil Chiller CH-01","CELL-04","Chiller Unit",         "Voltas",     "VC-60TR",     "B"),
    ("HT Compressor AC-01",    "CELL-04", "Air Compressor",       "Atlas Copco","GA55",        "A"),
    ("Assembly Stn AS-01",     "CELL-05", "Assembly Station",     "In-house",   "ASSY-1",      "B"),
    ("Assembly Stn AS-02",     "CELL-05", "Assembly Station",     "In-house",   "ASSY-1",      "B"),
    ("Assembly Stn AS-03",     "CELL-05", "Assembly Station",     "In-house",   "ASSY-2",      "B"),
    ("Leak Test Rig LT-01",    "CELL-05", "Leak Test Rig",        "ATEQ",       "F620",        "A"),
    ("Assy Conveyor CV-01",    "CELL-05", "Conveyor System",      "Interroll",  "IR-2000",     "C"),
    ("Paint Booth PB-01",      "CELL-06", "Paint Booth",          "Nordson",    "NB-4",        "A"),
    ("Curing Oven CO-01",      "CELL-06", "Curing Oven",          "Eisenmann",  "CO-12",       "B"),
    ("Paint Chiller CH-02",    "CELL-06", "Chiller Unit",         "Blue Star",  "BS-30TR",     "C"),
    ("Robot Weld Cell RW-01",  "CELL-07", "Robotic Welding Cell", "Fanuc",      "ARC Mate 120","A"),
    ("Robot Weld Cell RW-02",  "CELL-07", "Robotic Welding Cell", "Fanuc",      "ARC Mate 120","A"),
    ("Positioner PZ-01",       "CELL-07", "Conveyor System",      "Fanuc",      "2AX-500",     "C"),
    ("Weld Compressor AC-02",  "CELL-07", "Air Compressor",       "Elgi",       "EG37",        "B"),
    ("Hyd Press HP-01",        "CELL-08", "Hydraulic Press",      "Schuler",    "MSD-250",     "A"),
    ("Hyd Press HP-02",        "CELL-08", "Hydraulic Press",      "Schuler",    "MSD-160",     "B"),
    ("Press Feeder PF-01",     "CELL-08", "Conveyor System",      "Bruderer",   "BSV-75",      "C"),
]

MACHINES: list[Machine] = []
for i, (name, cell, mtype, make, model, crit) in enumerate(_M, start=1):
    chk, mins = MACHINE_TYPES[mtype]
    MACHINES.append(
        Machine(
            machine_id=f"MC-{i:03d}",
            machine_name=name,
            cell_id=cell,
            machine_type=mtype,
            make=make,
            model=model,
            serial_no=f"SN{2015 + (i % 9)}{i:04d}",
            install_date=date(2015 + (i % 9), ((i * 5) % 12) + 1, ((i * 7) % 27) + 1),
            criticality=crit,
            location=f"{cell} / Bay {((i - 1) % 4) + 1}",
            checklist_id=chk,
            pm_std_minutes=mins,
        )
    )

TECHNICIANS = [
    Technician("TECH-01", "Arun Kumar",      "arun.kumar@example.com",      "Shift A", "Mechanical",   "Machine Shop", 420),
    Technician("TECH-02", "Suresh Babu",     "suresh.babu@example.com",     "Shift A", "Electrical",   "Machine Shop", 420),
    Technician("TECH-03", "Mohammed Rafi",   "mohammed.rafi@example.com",   "Shift B", "Mechanical",   "Machine Shop", 420),
    Technician("TECH-04", "Vignesh S",       "vignesh.s@example.com",       "Shift B", "Hydraulics",   "Fabrication",  420),
    Technician("TECH-05", "Prakash R",       "prakash.r@example.com",       "Shift A", "Furnace",      "Heat Treat",   420),
    Technician("TECH-06", "Deepak Nair",     "deepak.nair@example.com",     "Shift C", "Electrical",   "Heat Treat",   360),
    Technician("TECH-07", "Ramesh Chandran", "ramesh.chandran@example.com", "Shift A", "Mechanical",   "Assembly",     420),
    Technician("TECH-08", "Karthik V",       "karthik.v@example.com",       "Shift B", "Automation",   "Fabrication",  420),
    Technician("TECH-09", "Sathish Kumar",   "sathish.kumar@example.com",   "Shift A", "Utilities",    "Finishing",    420),
    Technician("TECH-10", "Naveen Raj",      "naveen.raj@example.com",      "Shift B", "Automation",   "Assembly",     420),
]

# Which technicians can be assigned to which area
AREA_TECHS = {
    "Machine Shop": ["TECH-01", "TECH-02", "TECH-03"],
    "Heat Treat":   ["TECH-05", "TECH-06", "TECH-02"],
    "Assembly":     ["TECH-07", "TECH-10"],
    "Finishing":    ["TECH-09", "TECH-07"],
    "Fabrication":  ["TECH-04", "TECH-08", "TECH-09"],
}

# ---------------------------------------------------------------------------
# PM checklist master  (checklist_id -> list of tasks)
# task = (task_no, task_desc, task_type, standard, mandatory, safety_critical)
# ---------------------------------------------------------------------------
CHECKLISTS = {
    "CL-CNC-TURN": [
        (1,  "Lock out / tag out verified before start",           "Safety",      "LOTO applied",           "Yes", "Yes"),
        (2,  "Clean chip conveyor, coolant tank and chip tray",    "Cleaning",    "No chip accumulation",   "Yes", "No"),
        (3,  "Check coolant concentration",                        "Measurement", "6 - 9 %",                "Yes", "No"),
        (4,  "Check way lube level and top up",                    "Lubrication", "Above MIN mark",         "Yes", "No"),
        (5,  "Inspect way covers and wipers for damage",           "Visual",      "No tear / no leak",      "Yes", "No"),
        (6,  "Spindle vibration check",                            "Measurement", "<= 2.8 mm/s RMS",        "Yes", "No"),
        (7,  "Spindle temperature after 30 min run",               "Measurement", "<= 55 deg C",            "Yes", "No"),
        (8,  "Check hydraulic pressure",                           "Measurement", "35 - 40 bar",            "Yes", "No"),
        (9,  "Turret indexing time and repeatability",             "Measurement", "<= 1.2 s",               "Yes", "No"),
        (10, "Tailstock / chuck clamping pressure",                "Measurement", "18 - 22 bar",            "Yes", "Yes"),
        (11, "Check air filter / regulator / lubricator (FRL)",    "Visual",      "Bowl clean, no water",   "Yes", "No"),
        (12, "Verify E-stop and door interlock function",          "Safety",      "Stops within 1 s",       "Yes", "Yes"),
        (13, "Backlash check X and Z axis",                        "Measurement", "<= 0.01 mm",             "No",  "No"),
        (14, "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
    ],
    "CL-CNC-MILL": [
        (1,  "Lock out / tag out verified before start",           "Safety",      "LOTO applied",           "Yes", "Yes"),
        (2,  "Clean work enclosure, chip auger and coolant tank",  "Cleaning",    "No chip accumulation",   "Yes", "No"),
        (3,  "Check coolant concentration",                        "Measurement", "6 - 9 %",                "Yes", "No"),
        (4,  "Grease ball screws and linear guides",               "Lubrication", "As per lube chart",      "Yes", "No"),
        (5,  "Spindle taper cleaning and condition check",         "Visual",      "No fretting / burr",     "Yes", "No"),
        (6,  "Spindle vibration check",                            "Measurement", "<= 2.8 mm/s RMS",        "Yes", "No"),
        (7,  "ATC arm alignment and tool clamp force",             "Measurement", "Within OEM spec",        "Yes", "Yes"),
        (8,  "Check hydraulic / pneumatic pressure",               "Measurement", "5.5 - 6.5 bar",          "Yes", "No"),
        (9,  "Verify axis home position repeatability",            "Measurement", "<= 0.005 mm",            "No",  "No"),
        (10, "Verify E-stop and door interlock function",          "Safety",      "Stops within 1 s",       "Yes", "Yes"),
        (11, "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
        (12, "Check chiller for spindle - temp and level",         "Measurement", "20 +/- 2 deg C",         "Yes", "No"),
    ],
    "CL-GEAR": [
        (1,  "Lock out / tag out verified before start",           "Safety",      "LOTO applied",           "Yes", "Yes"),
        (2,  "Clean machine bed, swarf tray and coolant filter",   "Cleaning",    "Filter clear",           "Yes", "No"),
        (3,  "Hob head / cutter spindle runout",                   "Measurement", "<= 0.008 mm",            "Yes", "No"),
        (4,  "Work spindle bearing temperature",                   "Measurement", "<= 60 deg C",            "Yes", "No"),
        (5,  "Check and top up gearbox oil",                       "Lubrication", "Between MIN and MAX",    "Yes", "No"),
        (6,  "Inspect timing belts / drive couplings",             "Visual",      "No crack, correct tension","Yes","No"),
        (7,  "Index table backlash check",                         "Measurement", "<= 0.01 deg",            "No",  "No"),
        (8,  "Coolant flow at cutting zone",                       "Measurement", ">= 40 L/min",            "Yes", "No"),
        (9,  "Check guarding and interlocks",                      "Safety",      "All interlocks active",  "Yes", "Yes"),
        (10, "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
        (11, "Hydraulic power pack pressure and leak check",       "Measurement", "45 - 55 bar, no leak",   "Yes", "No"),
    ],
    "CL-FURNACE": [
        (1,  "Lock out / tag out and gas isolation verified",      "Safety",      "LOTO + gas isolated",    "Yes", "Yes"),
        (2,  "Thermocouple calibration check (all zones)",         "Measurement", "+/- 3 deg C of master",   "Yes", "Yes"),
        (3,  "Inspect heating elements / radiant tubes",           "Visual",      "No bulge, no crack",     "Yes", "Yes"),
        (4,  "Door seal and curtain condition",                    "Visual",      "No gap, no burn-through","Yes", "Yes"),
        (5,  "Quench oil level, temperature and condition",        "Measurement", "Level OK, <= 80 deg C",  "Yes", "No"),
        (6,  "Quench agitator motor current and vibration",        "Measurement", "<= FLC, <= 4.5 mm/s",    "Yes", "No"),
        (7,  "Atmosphere gas flow and carbon potential probe",     "Measurement", "Probe mV stable",        "Yes", "Yes"),
        (8,  "Burner flame condition and flame-failure trip test", "Safety",      "Trips within 3 s",       "Yes", "Yes"),
        (9,  "Refractory / insulation inspection",                 "Visual",      "No spalling",            "Yes", "No"),
        (10, "Cooling water flow and chiller performance",         "Measurement", ">= 60 L/min",            "Yes", "No"),
        (11, "Exhaust fan / flue condition",                       "Visual",      "Free flow",              "Yes", "No"),
        (12, "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
        (13, "Emergency stop and over-temperature trip test",      "Safety",      "Trips at setpoint +20",  "Yes", "Yes"),
    ],
    "CL-ASSY": [
        (1,  "Lock out / tag out verified before start",           "Safety",      "LOTO applied",           "Yes", "Yes"),
        (2,  "Clean station, fixtures and locating pins",          "Cleaning",    "No debris",              "Yes", "No"),
        (3,  "Torque tool calibration verification",               "Measurement", "+/- 3 % of setpoint",    "Yes", "Yes"),
        (4,  "Poka-yoke sensor function test",                     "Functional",  "All sensors respond",    "Yes", "Yes"),
        (5,  "Pneumatic FRL check and drain",                      "Visual",      "Bowl clean, no water",   "Yes", "No"),
        (6,  "Fixture clamp wear and repeatability",               "Measurement", "<= 0.05 mm",             "Yes", "No"),
        (7,  "Leak test rig master part verification",             "Functional",  "Pass master, reject NG", "Yes", "Yes"),
        (8,  "Check station lighting and andon",                   "Visual",      ">= 500 lux",             "No",  "No"),
        (9,  "Verify E-stop and light curtain",                    "Safety",      "Stops within 1 s",       "Yes", "Yes"),
        (10, "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
    ],
    "CL-PAINT": [
        (1,  "Lock out / tag out verified before start",           "Safety",      "LOTO applied",           "Yes", "Yes"),
        (2,  "Replace / clean intake and exhaust filters",         "Cleaning",    "dP <= 250 Pa",           "Yes", "No"),
        (3,  "Booth air velocity check",                           "Measurement", "0.4 - 0.6 m/s",          "Yes", "Yes"),
        (4,  "Spray gun / applicator cleaning and nozzle wear",     "Visual",      "No orifice wear",        "Yes", "No"),
        (5,  "Paint circulation pump pressure",                    "Measurement", "3 - 5 bar",              "Yes", "No"),
        (6,  "Oven zone temperature uniformity survey",            "Measurement", "+/- 5 deg C",            "Yes", "No"),
        (7,  "Conveyor chain lubrication and tension",             "Lubrication", "Sag <= 15 mm",           "Yes", "No"),
        (8,  "Fire suppression and gas detection check",           "Safety",      "System armed, no fault", "Yes", "Yes"),
        (9,  "Exhaust stack and scrubber condition",               "Visual",      "No blockage",            "Yes", "No"),
        (10, "Electrical panel cleaning (flame-proof integrity)",  "Electrical",  "Glands intact",          "Yes", "Yes"),
    ],
    "CL-WELD": [
        (1,  "Lock out / tag out verified before start",           "Safety",      "LOTO applied",           "Yes", "Yes"),
        (2,  "Torch / nozzle / contact tip replacement",           "Replacement", "New tip fitted",         "Yes", "No"),
        (3,  "Wire feeder rollers and liner condition",            "Visual",      "No wear groove",         "Yes", "No"),
        (4,  "Shielding gas flow and leak check",                  "Measurement", "15 - 20 L/min",          "Yes", "Yes"),
        (5,  "Robot TCP calibration check",                        "Measurement", "<= 0.5 mm deviation",    "Yes", "Yes"),
        (6,  "Robot axis grease level / battery voltage",          "Lubrication", "Battery >= 3.4 V",       "Yes", "No"),
        (7,  "Fume extraction flow rate",                          "Measurement", ">= 1000 m3/h",           "Yes", "Yes"),
        (8,  "Positioner rotation and clamp function",             "Functional",  "Smooth, no slip",        "Yes", "No"),
        (9,  "Weld cell light curtain and door interlock",         "Safety",      "Stops within 1 s",       "Yes", "Yes"),
        (10, "Water cooling circuit flow and leak check",          "Measurement", ">= 4 L/min, no leak",    "Yes", "No"),
        (11, "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
    ],
    "CL-PRESS": [
        (1,  "Lock out / tag out and ram blocked",                 "Safety",      "Safety block inserted",  "Yes", "Yes"),
        (2,  "Hydraulic oil level, temperature and sample",        "Measurement", "<= 55 deg C, ISO 18/16/13","Yes","No"),
        (3,  "Replace / inspect return-line filter",               "Replacement", "dP indicator green",     "Yes", "No"),
        (4,  "Check for hydraulic leaks at hoses and manifolds",   "Visual",      "Zero leak",              "Yes", "Yes"),
        (5,  "Ram parallelism and slide gib clearance",            "Measurement", "<= 0.10 mm",             "Yes", "No"),
        (6,  "Brake / clutch response time test",                  "Safety",      "<= 250 ms",              "Yes", "Yes"),
        (7,  "Bolster and die clamp integrity",                    "Visual",      "No crack, torque OK",    "Yes", "Yes"),
        (8,  "Lubrication system function and grease lines",       "Lubrication", "All points receiving",   "Yes", "No"),
        (9,  "Two-hand control and light curtain test",            "Safety",      "Stops within spec",      "Yes", "Yes"),
        (10, "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
    ],
    "CL-UTIL": [
        (1,  "Lock out / tag out verified before start",           "Safety",      "LOTO applied",           "Yes", "Yes"),
        (2,  "General cleaning and housekeeping",                  "Cleaning",    "No debris",              "Yes", "No"),
        (3,  "Belt / chain tension and alignment",                 "Measurement", "As per OEM",             "Yes", "No"),
        (4,  "Bearing greasing as per lube chart",                 "Lubrication", "All points",             "Yes", "No"),
        (5,  "Motor current and vibration check",                  "Measurement", "<= FLC, <= 4.5 mm/s",    "Yes", "No"),
        (6,  "Air / oil filter condition",                         "Visual",      "Clean or replace",       "Yes", "No"),
        (7,  "Condensate drain and moisture trap",                 "Cleaning",    "Free draining",          "Yes", "No"),
        (8,  "Safety guard and E-stop check",                      "Safety",      "Functional",             "Yes", "Yes"),
        (9,  "Electrical panel cleaning and terminal tightness",   "Electrical",  "No dust, no loose lug",  "Yes", "Yes"),
    ],
}

# ---------------------------------------------------------------------------
# Spare parts master
# ---------------------------------------------------------------------------
# (part_no, part_name, category, uom, unit_cost_inr, min_stock, current_stock, lead_days, store_bin, applies_to)
SPARES = [
    ("SP-1001", "Spindle bearing set 7014",       "Bearing",     "Set", 18500, 4,  6, 45, "A-01-03", "CNC Turning Center"),
    ("SP-1002", "Way wiper kit X/Z",              "Seal",        "Kit",  2400, 6,  9, 21, "A-01-05", "CNC Turning Center"),
    ("SP-1003", "Coolant pump 0.75 kW",           "Pump",        "No",  12800, 2,  1, 30, "A-02-01", "CNC Turning Center"),
    ("SP-1004", "Hydraulic solenoid valve 4/3",   "Hydraulic",   "No",   8600, 3,  4, 25, "A-02-04", "CNC Turning Center"),
    ("SP-1005", "Chuck jaw set 8 inch",           "Tooling",     "Set",  9200, 4,  7, 20, "A-03-02", "CNC Turning Center"),
    ("SP-1010", "ATC cam follower",               "Mechanical",  "No",   5400, 4,  5, 28, "A-03-06", "CNC Machining Center"),
    ("SP-1011", "Ball screw support bearing",     "Bearing",     "No",  14200, 2,  2, 40, "A-01-07", "CNC Machining Center"),
    ("SP-1012", "Spindle chiller compressor",     "Chiller",     "No",  46000, 1,  1, 60, "B-01-01", "CNC Machining Center"),
    ("SP-1020", "Hob spindle bearing",            "Bearing",     "No",  22400, 2,  3, 50, "A-01-09", "Gear Hobbing Machine"),
    ("SP-1021", "Index table oil seal",           "Seal",        "No",   1800, 8, 12, 15, "A-01-11", "Gear Hobbing Machine"),
    ("SP-1022", "Timing belt HTD 8M",             "Belt",        "No",   3600, 6,  4, 18, "A-04-02", "Gear Hobbing Machine"),
    ("SP-1030", "Radiant tube 150 mm",            "Furnace",     "No",  74000, 2,  2, 75, "B-02-01", "Sealed Quench Furnace"),
    ("SP-1031", "K-type thermocouple 1200 mm",    "Instrument",  "No",   4200, 8, 11, 20, "B-02-03", "Sealed Quench Furnace"),
    ("SP-1032", "Door seal rope 25 mm",           "Seal",        "Mtr",   650, 20, 34, 14, "B-02-05", "Sealed Quench Furnace"),
    ("SP-1033", "Quench agitator seal kit",       "Seal",        "Kit",  6800, 3,  2, 35, "B-02-07", "Sealed Quench Furnace"),
    ("SP-1034", "Carbon potential probe",         "Instrument",  "No",  58000, 1,  1, 90, "B-02-09", "Sealed Quench Furnace"),
    ("SP-1035", "Burner ignition electrode",      "Furnace",     "No",   5600, 4,  6, 30, "B-03-01", "Tempering Furnace"),
    ("SP-1040", "Torque transducer 30 Nm",        "Instrument",  "No",  32000, 1,  2, 55, "C-01-01", "Assembly Station"),
    ("SP-1041", "Poka-yoke proximity sensor",     "Electrical",  "No",   2200, 10, 15, 12, "C-01-03", "Assembly Station"),
    ("SP-1042", "Fixture clamp cylinder",         "Pneumatic",   "No",   7400, 4,  3, 24, "C-01-05", "Assembly Station"),
    ("SP-1043", "Leak test seal head",            "Seal",        "No",  11200, 2,  2, 38, "C-01-07", "Leak Test Rig"),
    ("SP-1050", "Booth intake filter 600x600",    "Filter",      "No",    950, 24, 40, 10, "C-02-01", "Paint Booth"),
    ("SP-1051", "Spray gun nozzle set",           "Tooling",     "Set",  8800, 3,  4, 22, "C-02-03", "Paint Booth"),
    ("SP-1052", "Paint circulation pump seal",    "Seal",        "Kit",  4600, 3,  5, 26, "C-02-05", "Paint Booth"),
    ("SP-1053", "Oven conveyor chain 3 mtr",      "Chain",       "Mtr",  2800, 10, 14, 20, "C-02-07", "Curing Oven"),
    ("SP-1060", "Welding contact tip 1.2 mm",     "Consumable",  "No",    120, 100, 260, 7, "D-01-01", "Robotic Welding Cell"),
    ("SP-1061", "Welding nozzle 16 mm",           "Consumable",  "No",    480, 40, 62, 10, "D-01-03", "Robotic Welding Cell"),
    ("SP-1062", "Wire feed roller set",           "Mechanical",  "Set",  3400, 6,  8, 18, "D-01-05", "Robotic Welding Cell"),
    ("SP-1063", "Robot axis battery pack",        "Electrical",  "No",   2600, 8, 10, 15, "D-01-07", "Robotic Welding Cell"),
    ("SP-1064", "Torch cable assembly 3 mtr",     "Cable",       "No",  16800, 2,  1, 35, "D-01-09", "Robotic Welding Cell"),
    ("SP-1070", "Hydraulic return filter element","Filter",      "No",   3900, 8, 10, 16, "D-02-01", "Hydraulic Press"),
    ("SP-1071", "Ram gib liner",                  "Mechanical",  "No",  21000, 2,  2, 48, "D-02-03", "Hydraulic Press"),
    ("SP-1072", "Hydraulic hose 1 inch x 2 mtr",  "Hydraulic",   "No",   4800, 6,  9, 14, "D-02-05", "Hydraulic Press"),
    ("SP-1073", "Brake friction disc",            "Mechanical",  "No",  27500, 2,  1, 52, "D-02-07", "Hydraulic Press"),
    ("SP-1080", "V-belt SPB 2500",                "Belt",        "No",   1400, 12, 18, 10, "E-01-01", "Air Compressor"),
    ("SP-1081", "Compressor air/oil separator",   "Filter",      "No",   9600, 3,  4, 28, "E-01-03", "Air Compressor"),
    ("SP-1082", "Compressor oil 20 L",            "Lubricant",   "Can",  7200, 4,  6, 12, "E-01-05", "Air Compressor"),
    ("SP-1083", "Chiller expansion valve",        "Chiller",     "No",  13400, 2,  2, 40, "E-02-01", "Chiller Unit"),
    ("SP-1084", "Conveyor roller 50 mm",          "Mechanical",  "No",   1100, 20, 26, 12, "E-03-01", "Conveyor System"),
    ("SP-1085", "Drive motor 2.2 kW",             "Motor",       "No",  18900, 2,  3, 32, "E-03-03", "Conveyor System"),
    ("SP-1086", "Gear reducer 1:30",              "Mechanical",  "No",  24600, 1,  1, 45, "E-03-05", "Conveyor System"),
    ("SP-1087", "Lubrication grease NLGI-2 1 kg", "Lubricant",   "No",    620, 30, 48,  7, "E-04-01", "All"),
]

FAILURE_MODES = [
    ("Bearing failure",          "Mechanical"),
    ("Hydraulic leak",           "Hydraulic"),
    ("Sensor / proximity fault", "Electrical"),
    ("Drive / VFD trip",         "Electrical"),
    ("Coolant pump failure",     "Mechanical"),
    ("Spindle overheating",      "Mechanical"),
    ("Belt / chain breakage",    "Mechanical"),
    ("PLC communication loss",   "Automation"),
    ("Pneumatic pressure drop",  "Pneumatic"),
    ("Thermocouple drift",       "Instrument"),
    ("Seal / gasket leak",       "Mechanical"),
    ("Limit switch damage",      "Electrical"),
    ("Tool clamp malfunction",   "Mechanical"),
    ("Motor winding failure",    "Electrical"),
    ("Software / parameter loss", "Automation"),
]

ROOT_CAUSES = [
    "Normal wear-out beyond service life",
    "Inadequate lubrication",
    "Contamination ingress",
    "Loose electrical termination",
    "Overload / abnormal process condition",
    "Missed PM task in previous cycle",
    "Poor quality spare fitted earlier",
    "Coolant ingress into panel",
    "Operator handling error",
    "Ageing component - end of life",
]

ABNORMALITY_CATEGORIES = [
    "Abnormal noise",
    "Abnormal vibration",
    "Oil / coolant leak",
    "Overheating",
    "Loose / missing fastener",
    "Damaged guard or cover",
    "Wiring / cable damage",
    "Air leak",
    "Corrosion / rust",
    "Housekeeping / 5S issue",
    "Safety device bypassed",
    "Warning lamp / alarm active",
]
